@extends($layoutMeta['layout'])
@section($layoutMeta['title_section'] ?? 'title', 'Travel Reports')
@section($layoutMeta['content_section'] ?? 'content')
<style>
.et-travel-hub{width:100%;max-width:1480px;margin:0 auto;color:#17243a}.et-travel-hub *{box-sizing:border-box}.et-travel-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-end;margin-bottom:16px}.et-travel-kicker{font-size:10px;font-weight:800;color:#1769d2;text-transform:uppercase;letter-spacing:.08em}.et-travel-hub h1{margin:4px 0;font-size:24px}.et-travel-sub{font-size:11px;color:#718096}.et-travel-note{font-size:10px;color:#718096;text-align:right}.et-travel-strip{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:9px;margin-bottom:16px}.et-travel-kpi,.et-travel-section{background:#fff;border:1px solid #dfe7f0;border-radius:8px}.et-travel-kpi{padding:11px}.et-travel-kpi small{display:block;color:#718096;font-size:9px;font-weight:800;text-transform:uppercase}.et-travel-kpi strong{display:block;margin-top:6px;font-size:18px}.et-travel-section{padding:14px;margin-bottom:14px}.et-travel-section h2{margin:0 0 4px;font-size:15px}.et-travel-section>p{margin:0 0 11px;color:#718096;font-size:10px}.et-travel-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px}.et-travel-card{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:11px;border:1px solid #e4ebf2;border-radius:7px;background:#fbfcfe}.et-travel-card strong{display:block;font-size:11px}.et-travel-card span{display:block;margin-top:3px;color:#718096;font-size:9px}.et-travel-card a{flex:0 0 auto;color:#1769d2;font-size:10px;font-weight:800;text-decoration:none}.et-travel-card a:hover,.et-travel-card a:focus{text-decoration:underline}.et-travel-category{margin-top:13px}.et-travel-category h3{margin:0 0 7px;font-size:11px;color:#52627a;text-transform:uppercase;letter-spacing:.05em}@media(max-width:1000px){.et-travel-strip{grid-template-columns:repeat(4,minmax(0,1fr))}.et-travel-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){.et-travel-head{display:block}.et-travel-note{text-align:left;margin-top:6px}.et-travel-strip,.et-travel-grid{grid-template-columns:1fr}.et-travel-card{align-items:flex-start}}
</style>
<div class="et-travel-hub" data-et-travel-reports="1">
 <header class="et-travel-head"><div><div class="et-travel-kicker">Reports / Travel Reports</div><h1>Travel Reports</h1><div class="et-travel-sub">Operational travel activity, passenger, product, movement and dimension reporting.</div></div><div class="et-travel-note">Financial fields are intentionally excluded.</div></header>
 <section class="et-travel-strip" aria-label="Operational summary">@foreach([['bookings','Bookings'],['passengers','Passengers'],['air','Air / Ticketing'],['hotels','Hotel'],['visas','Visa'],['transport','Transport'],['group-umrah','Group Umrah']] as [$key,$label])<div class="et-travel-kpi"><small>{{ $label }}</small><strong>{{ $counts[$key] ?? 0 }}</strong></div>@endforeach</section>
 <section class="et-travel-section" aria-labelledby="et-movement-reports"><h2 id="et-movement-reports">Movement &amp; Intimation Reports</h2><p>Operational movement visibility for arrivals, hotel transitions and departure.</p><div class="et-travel-grid">@foreach($movements as $key=>$label)<article class="et-travel-card"><div><strong>{{ $key==='arrival'?'Arrival Intimation':$label }}</strong><span>Operational movement report</span></div><a href="{{ route('travel-reports.group-umrah.'.$key) }}">Open Report</a></article>@endforeach</div></section>
 @php($categories=['BOOKING & PASSENGER'=>['bookings','passengers','group-umrah'],'PRODUCT / SERVICE'=>['air','hotels','visas','transport'],'DIMENSION / ANALYSIS'=>['customers','suppliers','branches','agents','airlines','sectors']])
 <section class="et-travel-section" aria-labelledby="et-standard-reports"><h2 id="et-standard-reports">Operational Reports</h2><p>Read-only operational dimensions and product activity.</p>@foreach($categories as $category=>$keys)<div class="et-travel-category"><h3>{{ $category }}</h3><div class="et-travel-grid">@foreach($keys as $key) @if(isset($reports[$key]))<article class="et-travel-card"><div><strong>{{ $reports[$key] }}</strong><span>Operational report</span></div><a href="{{ route('travel-reports.'.$key) }}">Open Report</a></article>@endif @endforeach</div></div>@endforeach</section>
</div>
@endsection
