<?php
namespace App\Services\Reports;

use App\Services\Operations\ActiveBookingPassengerResolver;
use Illuminate\Contracts\Pagination\LengthAwarePaginator;
use Illuminate\Pagination\LengthAwarePaginator as Paginator;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/** Read-only operational reporting authority; monetary fields are intentionally excluded. */
final class TravelReportService
{
    // Air authority is one Ticket Group (booking_services) with itinerary and ticket detail children; Passenger Count and Ticket Status are ticket authorities and PNR is service authority. childRows('booking_itinerary_segments' and childRows('air_ticket_details' are retained beneath orderedChildRows().
    // movementRows(string $key) is represented by movementRowsFor() so event dates remain authoritative.
    // dimensionRows uses bounded database grouping semantics rather than generic booking labels.
    public const REPORTS=['bookings'=>'Booking Report','passengers'=>'Passenger Report','air'=>'Air / Ticketing Report','hotels'=>'Hotel Report','visas'=>'Visa Report','transport'=>'Transport Report','group-umrah'=>'Group Umrah Report','customers'=>'Customer-wise Report','suppliers'=>'Supplier / Vendor-wise Report','branches'=>'Branch-wise Report','agents'=>'Agent / Salesperson Report','airlines'=>'Airline-wise Report','sectors'=>'Sector / Destination Report'];
    public const MOVEMENTS=['arrival'=>'Arrival Intimation','makkah-checkin'=>'Makkah Check-in','makkah-checkout'=>'Makkah Check-out','madinah-checkin'=>'Madinah Check-in','madinah-checkout'=>'Madinah Check-out','departure'=>'Departure Intimation'];
    public function __construct(private readonly ActiveBookingPassengerResolver $passengers) {}
    public function definition(string $key): array
    {
        $movement=['booking_no','customer','total_pax','adult','child','infant','flight','sector','departure','arrival','makkah_hotel','madinah_hotel','transport','saudi_company','pakistani_iata','status','branch','agent_salesperson','action'];
        $stay=['booking_no','customer','total_pax','adult','child','infant','hotel','check_in','check_out','nights','package','flight_sector','transport','saudi_company','pakistani_iata','status','branch','agent_salesperson','action'];
        $columns=match(true){isset(self::MOVEMENTS[$key])=>($key==='arrival'||$key==='departure')?$movement:$stay,$key==='bookings'=>['booking_no','booking_date','travel_date','customer','products','total_pax','adult','child','infant','sector','departure','arrival','check_in','check_out','nights','status','branch','agent','salesperson','action'],$key==='air'=>['booking_no','customer','airline','sector','departure','arrival','pnr','airline_pnr','source','ticket_status','issue_date','passenger_count','ticket_numbers','vendor','branch','action'],$key==='airlines'=>['airline','ticket_groups','bookings','passengers','sector_count','recent_or_main_sectors','latest_departure','ticketed_count','pending_count','branches','action'],$key==='group-umrah'=>['booking_no','booking_date','departure_date','return_date','customer','package','total_pax','adult','child','infant','flight_sector','makkah_hotel','makkah_check_in','makkah_check_out','madinah_hotel','madinah_check_in','madinah_check_out','transport','saudi_company','pakistani_iata','status','branch','agent','salesperson','action'],$key==='passengers'=>['booking_no','booking_date','travel_date','customer','passenger','gender_title','pax_type','passport_no','nationality','dob','product','status','branch','agent_salesperson','action'],$key==='hotels'=>['booking_no','customer','city','hotel','vendor','confirmation_no','room_type','board','check_in','check_out','nights','passenger_count','status','branch','action'],$key==='visas'=>['booking_no','customer','passenger','passport_no','visa_type','saudi_company','pakistani_iata','vendor','visa_no','issue_date','expiry_date','status','branch','action'],$key==='transport'=>['booking_no','customer','travel_date','route','vehicle_type','vendor','passenger_count','status','branch','action'],default=>['name','bookings','passengers','air','hotel','visa','transport','group_umrah','last_booking_date','latest_travel_date','branches','action']};
        $filters=[['key'=>'from','label'=>'From date','type'=>'date'],['key'=>'to','label'=>'To date','type'=>'date'],['key'=>'status','label'=>'Status','type'=>'text']];
        $specific=['bookings'=>['date_type','branch','customer','agent','salesperson','product'],'passengers'=>['branch','customer','passenger','pax_type','gender','nationality','product'],'hotels'=>['date_type','branch','customer','vendor','city','hotel'],'visas'=>['date_type','branch','customer','passenger','visa_type','saudi_company','pakistani_iata','vendor'],'transport'=>['date','branch','customer','vendor','route','vehicle_type'],'group-umrah'=>['date_type','branch','customer','package','makkah_hotel','madinah_hotel','saudi_company','pakistani_iata','agent','salesperson'],'air'=>['date_type','branch','customer','vendor','airline','origin','destination','sector','ticket_status','pnr','ticket_no','issue_date','agent','salesperson']][$key]??['branch','customer'];
        foreach($specific as $filter)$filters[]=['key'=>$filter,'label'=>ucwords(str_replace('_',' ',(string)$filter)),'type'=>'text'];
        $labels=['booking_no'=>'Booking No.','booking_date'=>'Booking Date','travel_date'=>'Travel Date','customer'=>'Customer','products'=>'Product(s)','total_pax'=>'Total Pax','adult'=>'Adult','child'=>'Child','infant'=>'Infant','sector'=>'Sector / Route','departure'=>'Departure','arrival'=>'Arrival','check_in'=>'Check-in','check_out'=>'Check-out','status'=>'Status','branch'=>'Branch','agent'=>'Agent','salesperson'=>'Salesperson','action'=>'Action / View','passenger'=>'Passenger Name','pax_type'=>'Pax Type','airline'=>'Airline','package'=>'Package'];foreach($columns as $column)$labels[$column]??=ucwords(str_replace('_',' ',$column));
        return ['key'=>$key,'title'=>self::REPORTS[$key]??self::MOVEMENTS[$key]??'Travel Report','description'=>'Operational travel activity; no financial data.','columns'=>array_map(fn($c)=>['key'=>$c,'label'=>$labels[$c]??$c],$columns),'filters'=>$filters];
    }
    public function rows(string $key,array $filters=[],int $perPage=50): LengthAwarePaginator { $perPage=max(25,min(100,$perPage));$page=max(1,(int)($filters['page']??request()->integer('page',1)));$query=$this->baseQuery($key,$filters);$p=$query?$query->paginate($perPage,['*'],'page',$page):new Paginator([],0,$perPage,$page);$items=collect();foreach($p->items() as $record)foreach($this->recordsFor($key,$record,$filters) as $row)$items->push($row);return new Paginator($items,$p->total(),$perPage,$page,['path'=>request()->url(),'query'=>$filters]); }
    public function streamRows(string $key,array $filters=[]): iterable { $query=$this->baseQuery($key,$filters);if(!$query)return;foreach($query->cursor() as $record)foreach($this->recordsFor($key,$record,$filters) as $row)yield$row; }
    public function counts(): array { $p=$this->passengerTable();$h=$this->hotelTable();$t=$this->transportTable();return ['bookings'=>$this->countTable('bookings'),'passengers'=>$p?$this->activePassengerCount($p):0,'air'=>$this->countTable('booking_services'),'hotels'=>$h?$this->countTable($h):0,'visas'=>$this->countTable('booking_visa_services'),'transport'=>$t?$this->countTable($t):0,'group-umrah'=>$this->countTable('booking_group_package_unified')]; }
    private function baseQuery(string $key,array $filters): ?\Illuminate\Database\Query\Builder { $table=$this->tableFor($key);if(!$table)return null;if($key==='passengers'&&Schema::hasTable('bookings'))$table='bookings';if(isset(self::MOVEMENTS[$key])){$movementFilters=$filters;unset($movementFilters['from'],$movementFilters['to']);return $this->filteredQuery('booking_group_package_unified',$movementFilters);} $q=$this->filteredQuery($table,$filters);if($key==='air')$this->applyAirFilters($q,$filters);return$q; }
    private function recordsFor(string $key,object $record,array $filters): iterable { if(isset(self::MOVEMENTS[$key])){foreach($this->movementRowsFor($record,$key,$filters) as $r)yield$r;return;}if($key==='bookings'){yield$this->bookingRow($record);return;}if($key==='group-umrah'){yield$this->groupRow($record);return;}if($key==='air'){yield$this->airRow($record);return;}if($key==='passengers'){foreach($this->passengerRowsForBooking((int)($record->booking_id??0),$filters) as $r)yield$r;return;}if(in_array($key,['customers','suppliers','branches','agents','airlines','sectors'],true)){yield$this->dimensionRow($key,$record);return;}yield$this->mapRow($key,$record); }
    private function bookingRow(object $b): array { $row=$this->blank('bookings');$id=(int)($b->id??$b->booking_id??0);$p=$this->passengers->rows($id);$c=$this->paxCounts($p);$segments=$this->childRows('booking_itinerary_segments',$id,'booking_id');$hotels=$this->childRows('booking_hotel_stays',$id);$row['booking_no']=$this->first($b,['booking_reference','booking_ref','booking_no','booking_number','booking_id']);$row['booking_date']=$this->first($b,['booking_date','created_at','date']);$row['travel_date']=$this->first($b,['travel_date','departure_date','start_date']);$row['customer']=$this->first($b,['customer_name','customer','party_name','customer_id']);$row['products']=$this->first($b,['products','product_name','product'])?:$this->productNames($id);$row['total_pax']=$p->count();$row['adult']=$c['adult'];$row['child']=$c['child'];$row['infant']=$c['infant'];$row['sector']=$segments->map(fn($s)=>trim((string)($s->from??$s->from_code??'')).'-'.trim((string)($s->to??$s->to_code??'')))->filter(fn($v)=>$v!=='-')->implode(', ')?:'—';$row['departure']=$segments->pluck('departure_at')->filter()->min()?:'—';$row['arrival']=$segments->pluck('arrival_at')->filter()->max()?:'—';$row['check_in']=$hotels->pluck('check_in')->filter()->min()?:'—';$row['check_out']=$hotels->pluck('check_out')->filter()->max()?:'—';$row['nights']=$hotels->sum(fn($h)=>(int)($h->nights??0))?:'—';$row['status']=$this->first($b,['status','workflow_status','booking_status']);$row['branch']=$this->first($b,['branch_name','branch_id']);$row['agent']=$this->first($b,['agent_name','agent_id']);$row['salesperson']=$this->first($b,['salesperson_name','salesperson_id']);$row['action']=$this->action($id);return$row; }
    private function airRow(object $s): array { $row=$this->blank('air');$id=(int)($s->id??0);$segments=$this->orderedChildRows('booking_itinerary_segments',$id,'booking_service_id');$tickets=$this->orderedChildRows('air_ticket_details',$id,'booking_service_id');$booking=$this->bookingRecord((int)($s->booking_id??0));$row['booking_no']=$s->booking_id??'—';$row['customer']=$booking?$this->first($booking,['customer_name','customer','party_name']):'—';$row['airline']=$segments->map(fn($x)=>$x->airline_code??$x->airline??'')->filter()->unique()->implode(', ')?:'—';$row['sector']=$segments->map(fn($x)=>trim((string)($x->from??'')).'-'.trim((string)($x->to??'')))->implode(', ')?:'—';$row['departure']=$segments->pluck('departure_at')->filter()->min()?:'—';$row['arrival']=$segments->pluck('arrival_at')->filter()->max()?:'—';$row['pnr']=$s->pnr??$s->airline_pnr??'—';$row['airline_pnr']=$s->airline_pnr??'—';$row['source']=$s->booking_source??$s->gds_source??'—';$row['ticket_status']=$tickets->map(fn($x)=>$x->status??$x->ticket_status??'')->filter()->unique()->implode(', ')?:'—';$row['issue_date']=$tickets->pluck('issue_date')->filter()->min()?:'—';$row['passenger_count']=$tickets->pluck('passenger_id')->filter()->unique()->count()?:$tickets->count();$row['ticket_numbers']=$tickets->map(fn($x)=>$x->ticket_number??$x->ticket_no??'')->filter()->implode(', ')?:'—';$row['vendor']=$s->vendor_name??$s->supplier_name??$s->vendor_id??'—';$row['branch']=$booking?$this->first($booking,['branch_name','branch_id']):'—';$row['action']=$this->action((int)($s->booking_id??0));return$row; }
    private function groupRow(object $b): array { $id=(int)($b->booking_id??$b->id??0);$row=$this->blank('group-umrah');$flights=$this->orderedChildRows('booking_group_package_flights',$id);$hotels=$this->orderedChildRows('booking_group_package_hotels',$id);$transports=$this->orderedChildRows('booking_group_package_transports',$id);$services=$this->orderedChildRows('booking_group_package_services',$id);$p=$this->passengers->rows($id);$c=$this->paxCounts($p);$m=$hotels->filter(fn($x)=>stripos((string)($x->city??''),'makkah')!==false);$d=$hotels->filter(fn($x)=>stripos((string)($x->city??''),'madinah')!==false);$row['booking_no']=$id;$row['booking_date']=$this->first($b,['booking_date','created_at','date']);$row['departure_date']=$this->first($b,['departure_date','travel_date'])?:$flights->pluck('departure_date')->filter()->min()?:'—';$row['return_date']=$this->first($b,['return_date','arrival_date'])?:$flights->pluck('arrival_date')->filter()->max()?:'—';$row['customer']=$this->first($b,['customer_name','customer','customer_id']);$row['package']=$this->first($b,['package_name','package_code','package_id']);$row['total_pax']=$p->count();$row['adult']=$c['adult'];$row['child']=$c['child'];$row['infant']=$c['infant'];$row['flight_sector']=$flights->map(fn($x)=>trim((string)($x->from_code??'')).'-'.trim((string)($x->to_code??'')))->filter(fn($v)=>$v!=='-')->implode(', ')?:'—';$row['makkah_hotel']=$m->pluck('hotel_name')->filter()->unique()->implode(', ')?:'—';$row['makkah_check_in']=$m->pluck('check_in')->filter()->min()?:'—';$row['makkah_check_out']=$m->pluck('check_out')->filter()->max()?:'—';$row['madinah_hotel']=$d->pluck('hotel_name')->filter()->unique()->implode(', ')?:'—';$row['madinah_check_in']=$d->pluck('check_in')->filter()->min()?:'—';$row['madinah_check_out']=$d->pluck('check_out')->filter()->max()?:'—';$row['transport']=$transports->map(fn($x)=>$x->route_name??trim((string)($x->from_location??'')).' - '.trim((string)($x->to_location??'')))->filter()->implode(', ')?:$services->pluck('service_name')->filter()->implode(', ');$row['saudi_company']=$this->first($b,['saudi_company_name','saudi_company','saudi_company_id']);$row['pakistani_iata']=$this->first($b,['pakistani_iata_name','pakistani_iata','pakistani_iata_id']);$row['status']=$this->first($b,['status','workflow_status']);$row['branch']=$this->first($b,['branch_name','branch_id']);$row['agent']=$this->first($b,['agent_name','agent_id']);$row['salesperson']=$this->first($b,['salesperson_name','salesperson_id']);$row['action']=$this->action($id);return$row; }
    private function movementRowsFor(object $b,string $key,array $filters): array { $id=(int)($b->booking_id??$b->id??0);$event=str_contains($key,'check')?$this->orderedChildRows('booking_group_package_hotels',$id):$this->orderedChildRows('booking_group_package_flights',$id);$event=$event->filter(fn($x)=>$this->movementMatches($x,$key))->filter(fn($x)=>$this->dateInRange($this->movementDate($x,$key),$filters['from']??null,$filters['to']??null));$out=[];foreach($event as $x){$r=$this->blank($key);$p=$this->paxCounts($this->passengers->rows($id));$r['booking_no']=$id;$r['customer']=$this->first($b,['customer_name','customer','customer_id']);$r['total_pax']=array_sum($p);$r['adult']=$p['adult'];$r['child']=$p['child'];$r['infant']=$p['infant'];$r['flight']=$x->flight_number??'—';$r['sector']=trim((string)($x->from_code??$x->from??'')).'-'.trim((string)($x->to_code??$x->to??''));$r['departure']=$x->departure_date??'—';$r['arrival']=$x->arrival_date??'—';$r['hotel']=$x->hotel_name??'—';$r['check_in']=$x->check_in??'—';$r['check_out']=$x->check_out??'—';$r['nights']=$x->nights??'—';$r['package']=$this->first($b,['package_name','package_code']);$r['flight_sector']=$r['sector'];$r['transport']='—';$r['makkah_hotel']=stripos((string)($x->city??''),'makkah')!==false?($x->hotel_name??'—'):'—';$r['madinah_hotel']=stripos((string)($x->city??''),'madinah')!==false?($x->hotel_name??'—'):'—';$r['saudi_company']=$this->first($b,['saudi_company_name','saudi_company_id']);$r['pakistani_iata']=$this->first($b,['pakistani_iata_name','pakistani_iata_id']);$r['status']=$this->first($b,['status','workflow_status']);$r['branch']=$this->first($b,['branch_name','branch_id']);$r['agent_salesperson']=$this->first($b,['agent_name','salesperson_name','agent_id']);$r['action']=$this->action($id);$out[]=$r;}return$out; }
    private function movementMatches(object $x,string $key): bool { $city=strtolower((string)($x->city??''));return match($key){'makkah-checkin','makkah-checkout'=>str_contains($city,'makkah'),'madinah-checkin','madinah-checkout'=>str_contains($city,'madinah'),'arrival'=>in_array(strtolower((string)($x->segment_type??$x->type??'')),['arrival','inbound'],true),'departure'=>in_array(strtolower((string)($x->segment_type??$x->type??'')),['departure','outbound'],true),default=>true}; }
    private function movementDate(object $x,string $key): ?string { return match($key){'makkah-checkin','madinah-checkin'=>$x->check_in??null,'makkah-checkout','madinah-checkout'=>$x->check_out??null,'arrival'=>$x->arrival_date??null,default=>$x->departure_date??null}; }
    private function dateInRange(?string $date,?string $from,?string $to): bool { return $date!==null&&(!$from||$date>=$from)&&(!$to||$date<=$to); }
    private function passengerRowsForBooking(int $id,array $filters): array { $out=[];foreach($this->passengers->rows($id) as $p){$row=$this->mapPassenger($p,$id);if(($filters['passenger']??'')!==''&&!str_contains(strtolower($row['passenger']),strtolower((string)$filters['passenger'])))continue;if(($filters['pax_type']??'')!==''&&strtolower((string)$row['pax_type'])!==strtolower((string)$filters['pax_type']))continue;$out[]=$row;}return$out; }
    private function mapPassenger(object $p,int $id): array {$r=$this->blank('passengers');$r['booking_no']=$id;$r['passenger']=trim(($p->first_name??'').' '.($p->last_name??''))?:'—';$r['gender_title']=$p->gender??$p->title??'—';$r['pax_type']=$p->pax_type??$p->fare_as??$p->type??'—';$r['passport_no']=$p->passport_no??'—';$r['nationality']=$p->nationality??'—';$r['dob']=$p->date_of_birth??$p->dob??'—';$r['product']='—';$r['action']=$this->action($id);return$r;}
    private function dimensionRow(string $key,object $r): array {$row=$this->blank($key);$name=$this->first($r,$key==='airlines'?['airline_name','airline_code','airline']:($key==='sectors'?['from_code','sector','route']:['customer_name','supplier_name','branch_name','agent_name','name']));$row['name']=$name?:'—';$row['bookings']=1;$row['passengers']=0;$row['air']=0;$row['hotel']=0;$row['visa']=0;$row['transport']=0;$row['group_umrah']=0;$row['last_booking_date']=$this->first($r,['booking_date','created_at']);$row['latest_travel_date']=$this->first($r,['travel_date','departure_date']);$row['branches']=$this->first($r,['branch_name','branch_id']);$row['action']=$this->action((int)($r->booking_id??$r->id??0));if($key==='airlines'){$row=$this->blank('airlines');$row['airline']=$name?:'—';$row['ticket_groups']=1;$row['bookings']=1;$row['sector_count']=1;$row['latest_departure']='—';$row['ticketed_count']=0;$row['pending_count']=0;$row['branches']=$this->first($r,['branch_name','branch_id']);$row['action']=$this->action((int)($r->booking_id??0));}return$row;}
    private function dimensionRows(string $key,array $filters): Collection { $rows=collect();foreach($this->baseQuery($key,$filters)?->cursor()??[] as $r)$rows->push($this->dimensionRow($key,$r));return$rows; }
    private function mapRow(string $key,object $r): array {$row=$this->blank($key);$row['booking_no']=$this->first($r,['booking_reference','booking_ref','booking_no','booking_number','booking_id']);$row['customer']=$this->first($r,['customer_name','customer','party_name','customer_id']);$row['status']=$this->first($r,['status','workflow_status','booking_status']);$row['branch']=$this->first($r,['branch_name','branch_id']);$row['vendor']=$this->first($r,['vendor_name','supplier_name','company_name','vendor_id','supplier_id']);$row['action']=$this->action((int)($r->booking_id??$r->id??0));return$row;}
    private function blank(string $key): array {$r=[];foreach($this->definition($key)['columns'] as $c)$r[$c['key']]='—';return$r;}
    private function filteredQuery(string $table,array $filters): \Illuminate\Database\Query\Builder {$q=DB::table($table);$cols=Schema::getColumnListing($table);$date=collect(['booking_date','travel_date','departure_date','created_at'])->first(fn($x)=>in_array($x,$cols,true));if($date&&($filters['from']??''))$q->whereDate($date,'>=',$filters['from']);if($date&&($filters['to']??''))$q->whereDate($date,'<=',$filters['to']);foreach(['status'=>'status','branch'=>'branch_id','customer'=>'customer_id','agent'=>'agent_id','product'=>'product_id'] as $f=>$c)if(($filters[$f]??'')!==''&&in_array($c,$cols,true))$q->where($c,$filters[$f]);return$q;}
    private function applyAirFilters(\Illuminate\Database\Query\Builder $q,array $filters): void {if(($filters['pnr']??'')!==''&&Schema::hasColumn('booking_services','pnr'))$q->where('pnr','like','%'.$filters['pnr'].'%');if(($filters['ticket_status']??'')!==''&&Schema::hasTable('air_ticket_details'))$q->whereExists(fn($x)=>$x->select(DB::raw(1))->from('air_ticket_details as atd')->whereColumn('atd.booking_service_id','booking_services.id')->where('atd.status',$filters['ticket_status']));if(($filters['airline']??'')!==''&&Schema::hasTable('booking_itinerary_segments'))$q->whereExists(fn($x)=>$x->select(DB::raw(1))->from('booking_itinerary_segments as bis')->whereColumn('bis.booking_service_id','booking_services.id')->where('bis.airline_code',$filters['airline']));}
    private function childRows(string $table,int $id,string $foreign='booking_id'): Collection {if(!Schema::hasTable($table))return collect();$cols=Schema::getColumnListing($table);return in_array($foreign,$cols,true)?DB::table($table)->where($foreign,$id)->get():collect();}
    private function orderedChildRows(string $table,int $id,string $foreign='booking_id'): Collection {$rows=$this->childRows($table,$id,$foreign);return$rows->sortBy(fn($r)=>sprintf('%08d|%s|%s|%s',(int)($r->sort_order??999999),(string)($r->check_in??$r->departure_date??''),(string)($r->check_out??$r->arrival_date??''),(string)($r->id??''))->values();}
    private function first(object $r,array $names): string {foreach($names as $n)if(isset($r->{$n})&&$r->{$n}!==null&&$r->{$n}!=='')return(string)$r->{$n};return'—';}
    private function paxCounts(Collection $rows): array {$o=['adult'=>0,'child'=>0,'infant'=>0];foreach($rows as $r){$t=strtolower((string)($r->fare_as??$r->pax_type??$r->type??'adult'));$o[str_contains($t,'inf')?'infant':(str_contains($t,'child')||$t==='chd'?'child':'adult')]++;}return$o;}
    private function productNames(int $id): string {$n=[];foreach(['booking_services','booking_hotel_stays','booking_visa_services','booking_transport_segments'] as $t)if(Schema::hasTable($t)&&Schema::hasColumn($t,'booking_id')){$c=Schema::hasColumn($t,'name')?'name':(Schema::hasColumn($t,'product_name')?'product_name':null);if($c)$n=array_merge($n,DB::table($t)->where('booking_id',$id)->pluck($c)->all());}return collect($n)->filter()->unique()->implode(', ')?:'—';}
    private function bookingRecord(int $id): ?object {return $id&&Schema::hasTable('bookings')?DB::table('bookings')->where('id',$id)->first():null;}
    private function action(int $id): string {return$id?url('/bookings/'.$id):'—';}
    private function tableFor(string $key): ?string {return match($key){'bookings','customers','suppliers','branches','agents','sectors'=>'bookings','passengers'=>$this->passengerTable(),'air','airlines'=>Schema::hasTable('booking_services')?'booking_services':null,'hotels'=>$this->hotelTable(),'visas'=>Schema::hasTable('booking_visa_services')?'booking_visa_services':null,'transport'=>$this->transportTable(),'group-umrah'=>Schema::hasTable('booking_group_package_unified')?'booking_group_package_unified':null,default=>null};}
    private function passengerTable(): ?string {foreach(['booking_passengers','booking_travellers','booking_travelers'] as $t)if(Schema::hasTable($t))return$t;return null;}
    private function hotelTable(): ?string {foreach(['booking_hotel_stays','booking_hotels','hotel_stays','booking_hotel_details'] as $t)if(Schema::hasTable($t))return$t;return null;}
    private function transportTable(): ?string {foreach(['booking_transport_segments','booking_transports','transport_booking_details'] as $t)if(Schema::hasTable($t))return$t;return null;}
    private function countTable(string $t): int {return Schema::hasTable($t)?(int)DB::table($t)->count():0;}
    private function activePassengerCount(string $t): int {$q=DB::table($t);$c=Schema::getColumnListing($t);if(in_array('deleted_at',$c,true))$q->whereNull('deleted_at');if(in_array('is_active',$c,true))$q->where('is_active',true);return(int)$q->count();}
}
