<?php
namespace App\Http\Middleware;
use Closure; use Illuminate\Http\Request; use Symfony\Component\HttpFoundation\Response;
final class PresentTravelMasterUiPolish {
 public function handle(Request $request, Closure $next): Response {
  $response=$next($request); if(!method_exists($response,'getContent')||!method_exists($response,'setContent'))return $response; if($request->path()!=='master-data/travel-masters')return $response; $type=strtolower((string)$response->headers->get('content-type','')); if($type!==''&&!str_contains($type,'text/html'))return $response;
  $html=(string)$response->getContent(); if(str_contains($html,'data-et-travel-master-ui="113288"'))return $response;
  $style='<style data-et-travel-master-ui="113288">.et-tm-ui-grid-113288{display:grid;grid-template-columns:repeat(12,minmax(0,1fr));gap:8px;align-items:end}.et-tm-ui-field{min-width:0}.et-tm-ui-actions{display:flex;gap:8px;align-items:center;flex-wrap:wrap;min-width:0}.et-tm-ui-pager{display:flex;gap:6px;align-items:center;justify-content:flex-end;flex-wrap:wrap;margin-top:10px}.et-tm-ui-pager button{min-width:30px;padding:5px 8px;border:1px solid #cbd5e1;border-radius:6px;background:#fff}.et-tm-ui-pager button[aria-current="page"]{background:#2563eb;color:#fff;border-color:#2563eb}.et-tm-page-hidden-113288{display:none!important}@media(max-width:1100px){.et-tm-ui-grid-113288{grid-template-columns:repeat(6,minmax(0,1fr))}}@media(max-width:700px){.et-tm-ui-grid-113288{display:block}.et-tm-ui-field,.et-tm-ui-actions{margin-top:8px}.et-tm-ui-actions>*{flex:1 1 140px}}</style>';
  $script=<<<'HTML'
<script data-et-travel-master-ui="113288">
(()=>{
 const norm=s=>String(s||'').replace(/[^a-z0-9]+/gi,' ').replace(/\s+/g,' ').trim().toLowerCase();
 const safeWrapper=(label,form)=>{if(!label||!form||label.closest('form')!==form)return null;const target=label.htmlFor?document.getElementById(label.htmlFor):label.querySelector('input,select,textarea');const wrapper=target?.closest('.form-group,.field,.grid-item,td,div');if(!wrapper||wrapper===form||wrapper.closest('form')!==form||['BODY','HTML','MAIN','SECTION','ARTICLE'].includes(wrapper.tagName)||wrapper.querySelectorAll('label').length>1)return null;return wrapper};
 const decorateForm=(control,fields,spans,actionSpan)=>{const form=control?.closest('form');if(!form)return false;const labels=[...form.querySelectorAll('label')];const resolved=fields.map(name=>safeWrapper(labels.find(l=>norm(l.textContent).startsWith(norm(name))),form));if(resolved.some(x=>!x))return false;const parent=resolved[0].parentElement;if(!parent||parent===form||parent.closest('form')!==form||resolved.some(x=>x.parentElement!==parent))return false;let action=control;while(action&&action.parentElement!==parent&&action!==form)action=action.parentElement;if(!action||action===form||action.parentElement!==parent||action.closest('form')!==form)return false;parent.classList.add('et-tm-ui-grid-113288');resolved.forEach((x,i)=>{x.classList.add('et-tm-ui-field');x.style.gridColumn='span '+spans[i]});action.classList.add('et-tm-ui-actions');action.style.gridColumn='span '+actionSpan;return true};
 const decorate=()=>{const find=t=>[...document.querySelectorAll('a,button,input[type=submit]')].find(x=>norm(x.textContent||x.value)===t);decorateForm(find('add hotel'),['code','hotel name','city','city iata','country','star rating','phone','default supplier','address','notes','active'],[3,3,3,3,3,3,3,3,4,3,1],4);decorateForm(find('add record'),['code','company','registration','iata','phone','email','website','city','country','default supplier','notes','active'],[3,3,3,3,3,3,3,3,2,4,3,1],2);decorateForm(find('add airline'),['internal code','airline name','iata','icao','accounting prefix','country','default supplier','notes','active'],[3,3,3,3,2,2,3,2,1],2)};
 const eligible=(table,kind)=>{const heads=[...table.querySelectorAll('thead th')].map(x=>norm(x.textContent));if(kind==='hotel')return heads.some(x=>x.includes('hotel'))&&heads.some(x=>x.includes('city'));return heads.some(x=>x==='iata')&&heads.some(x=>x==='icao')&&(heads.some(x=>x.includes('airline'))||heads.some(x=>x.includes('name')))};
 const paginate=(table,kind)=>{if(!eligible(table,kind)||table.dataset.etTmPager==='113288')return false;const body=table.tBodies[0];if(!body)return false;const rows=()=>[...body.rows];const pager=document.createElement('div');pager.className='et-tm-ui-pager';const info=document.createElement('span');const sizeWrap=document.createElement('span');const sizeLabel=document.createElement('span');const size=document.createElement('select');sizeLabel.textContent='Rows: ';[25,50,100].forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;size.insertAdjacentElement('beforeend',o)});sizeWrap.append(sizeLabel,size);const nav=document.createElement('span');pager.append(info,sizeWrap,nav);table.insertAdjacentElement('afterend',pager);let page=1,per=25;const render=()=>{const all=rows();all.forEach(r=>r.classList.remove('et-tm-page-hidden-113288'));const visible=all.filter(r=>getComputedStyle(r).display!=='none');const pages=Math.max(1,Math.ceil(visible.length/per));page=Math.min(page,pages);visible.forEach((r,i)=>{if(i<((page-1)*per)||i>=page*per)r.classList.add('et-tm-page-hidden-113288')});info.textContent=`Showing ${visible.length?((page-1)*per+1):0}–${Math.min(page*per,visible.length)} of ${visible.length}`;nav.textContent='';const add=(txt,p,disabled,active)=>{const b=document.createElement('button');b.type='button';b.textContent=txt;b.disabled=disabled;if(active)b.setAttribute('aria-current','page');if(p)b.onclick=()=>{page=p;render()};nav.insertAdjacentElement('beforeend',b)};add('First',1,page===1);add('Previous',Math.max(1,page-1),page===1);const range=[];for(let p=1;p<=pages;p++)if(p===1||p===pages||Math.abs(p-page)<=1)range.push(p);let last=0;range.forEach(p=>{if(last&&p-last>1){const e=document.createElement('span');e.textContent='…';nav.insertAdjacentElement('beforeend',e)}add(String(p),p,false,p===page);last=p});add('Next',Math.min(pages,page+1),page===pages);add('Last',pages,page===pages)};const refresh=resetPage=>{rows().forEach(r=>r.classList.remove('et-tm-page-hidden-113288'));if(resetPage===true)page=1;render()};size.value='25';size.onchange=()=>{per=Number(size.value)||25;refresh(true)};render();table._etTmPagerRefresh113288=()=>refresh(true);table.dataset.etTmPager='113288';return true};
 const start=()=>{document.documentElement.classList.add('et-tm-ui-113288');decorate();const tab=new URL(location.href).searchParams.get('tab')||'';if(tab!=='hotels'&&tab!=='airlines')return true;const kind=tab==='hotels'?'hotel':'airline';const table=[...document.querySelectorAll('table')].find(t=>eligible(t,kind));return table?paginate(table,kind):false};let observer=null;const run=()=>{if(start()&&observer)observer.disconnect()};observer=window.MutationObserver?new MutationObserver(run):null;if(observer)observer.observe(document.documentElement,{childList:true,subtree:true});run();document.addEventListener('DOMContentLoaded',run,{once:true});document.addEventListener('input',e=>{if(e.target.closest('.et-tm-ui-pager'))return;setTimeout(()=>{const tab=new URL(location.href).searchParams.get('tab')||'';const kind=tab==='hotels'?'hotel':'airline';const table=[...document.querySelectorAll('table')].find(t=>eligible(t,kind));if(table&&table._etTmPagerRefresh113288)table._etTmPagerRefresh113288()},0)});document.addEventListener('change',e=>{if(e.target.closest('.et-tm-ui-pager'))return;setTimeout(()=>{const tab=new URL(location.href).searchParams.get('tab')||'';const kind=tab==='hotels'?'hotel':'airline';const table=[...document.querySelectorAll('table')].find(t=>eligible(t,kind));if(table&&table._etTmPagerRefresh113288)table._etTmPagerRefresh113288()},0)});setTimeout(()=>{if(observer)observer.disconnect()},2200);
})();
</script>
HTML;
  $html=str_contains($html,'</head>')?str_replace('</head>',$style.$script.'</head>',$html):$style.$html.$script;$response->setContent($html);return $response;
 }
}
