<?php
namespace App\Http\Middleware;
use Closure; use Illuminate\Http\Request; use Symfony\Component\HttpFoundation\Response;
final class PresentTravelMasterHierarchy {
 public function handle(Request $request, Closure $next): Response {
  $response=$next($request); if(!method_exists($response,'getContent')||!method_exists($response,'setContent')) return $response;
  $type=strtolower((string)$response->headers->get('content-type','')); if($type!==''&&!str_contains($type,'text/html')) return $response;
  $html=(string)$response->getContent(); if($request->path()!=='master-data/travel-masters'||str_contains($html,'data-et-travel-master-hierarchy="113286"')) return $response;
  $style='<style>.et-tm-primary-113286,.et-tm-child-nav-113286{display:flex;flex-wrap:wrap;gap:8px;margin:10px 0}.et-tm-primary-113286 a,.et-tm-child-nav-113286 a{padding:7px 11px;border:1px solid #cbd5e1;border-radius:7px;text-decoration:none;background:#fff;color:#13233b}.et-tm-active-113286{background:#13233b!important;border-color:#13233b!important;color:#fff!important}.et-tm-hotel-final-row-113286{display:grid;grid-template-columns:minmax(150px,1fr) minmax(150px,1fr) auto auto;gap:8px;align-items:end}.et-tm-hotel-actions-113286{display:flex;gap:8px;align-items:center;flex-wrap:nowrap}@media(max-width:800px){.et-tm-hotel-final-row-113286{grid-template-columns:1fr 1fr}.et-tm-hotel-actions-113286{flex-wrap:wrap}}</style>';
  $script=<<<'HTML'
<script data-et-travel-master-hierarchy="113286">
(()=>{
 const textNorm=value=>String(value||'').replace(/\s+/g,' ').trim().toLowerCase();
 const controlNorm=value=>String(value||'').replace(/[^a-z0-9]+/gi,' ').replace(/\s+/g,' ').trim().toLowerCase();
 const labels=['Overview','Hotels','Transport Companies','Vehicle Types','Transport Routes','Transport Vendor Rates','Saudi Visa Companies','Pakistan Visa / IATA','Airlines','Airline Codes','Booking Sources','Products & Services'];
 const normalizedLabels=new Set(labels.map(textNorm));
 const tabOf=anchor=>{if(!anchor)return null;try{return new URL(anchor.href,location.href).searchParams.get('tab')||null}catch(e){return null}};
 const resolveTravelMasterState=(currentTab,tabs)=>{const current=currentTab||null;const transportTabs=[tabs.transportCompanies,tabs.vehicleTypes,tabs.transportRoutes,tabs.transportVendorRates].filter(Boolean);const airlineTabs=[tabs.airlines,tabs.airlineCodes].filter(Boolean);if(!current)return{effectiveCurrent:null,primaryActive:'Overview',family:null,transportActive:null,airlinesActive:null,normalizeLegacyAirlineCodes:false};if(current===tabs.airlineCodes&&tabs.airlines)return{effectiveCurrent:tabs.airlines,primaryActive:'Airlines',family:'airlines',transportActive:null,airlinesActive:'Airlines',normalizeLegacyAirlineCodes:true};if(transportTabs.includes(current))return{effectiveCurrent:current,primaryActive:'Transport Companies',family:'transport',transportActive:Object.entries({transportCompanies:'Transport Companies',vehicleTypes:'Vehicle Types',transportRoutes:'Transport Routes',transportVendorRates:'Transport Vendor Rates'}).find(([k])=>tabs[k]===current)?.[1]||null,airlinesActive:null,normalizeLegacyAirlineCodes:false};if(airlineTabs.includes(current))return{effectiveCurrent:current,primaryActive:'Airlines',family:'airlines',transportActive:null,airlinesActive:'Airlines',normalizeLegacyAirlineCodes:false};const p=Object.entries({hotels:'Hotels',bookingSources:'Booking Sources',productsServices:'Products & Services'}).find(([k])=>tabs[k]===current)?.[1]||'Overview';return{effectiveCurrent:current,primaryActive:p,family:null,transportActive:null,airlinesActive:null,normalizeLegacyAirlineCodes:false};};
 const nativeLabels=labels,anchors=[...document.querySelectorAll('a')].filter(anchor=>{try{const url=new URL(anchor.href,location.href);return url.pathname==='/master-data/travel-masters'&&normalizedLabels.has(textNorm(anchor.textContent))}catch(e){return false}}),overview=anchors.find(a=>textNorm(a.textContent)==='overview');
 let nativeStrip=null;for(let p=overview?.parentElement;p&&p!==document.body&&p!==document.documentElement;p=p.parentElement){if(anchors.filter(a=>p.contains(a)).length>=8){nativeStrip=p;break}}
 const byLabel=label=>anchors.find(a=>textNorm(a.textContent)===textNorm(label));
 const finalizeHierarchy=()=>{if(!nativeStrip)return;nativeStrip.style.setProperty('display','none','important');if(document.querySelector('[data-et-travel-master-primary="113286"]'))return;const tabs={hotels:tabOf(byLabel('Hotels')),transportCompanies:tabOf(byLabel('Transport Companies')),vehicleTypes:tabOf(byLabel('Vehicle Types')),transportRoutes:tabOf(byLabel('Transport Routes')),transportVendorRates:tabOf(byLabel('Transport Vendor Rates')),airlines:tabOf(byLabel('Airlines')),airlineCodes:tabOf(byLabel('Airline Codes')),bookingSources:tabOf(byLabel('Booking Sources')),productsServices:tabOf(byLabel('Products & Services'))};let current=new URL(location.href).searchParams.get('tab')||null;let state=resolveTravelMasterState(current,tabs);if(state.normalizeLegacyAirlineCodes){const url=new URL(location.href);url.searchParams.set('tab',state.effectiveCurrent);history.replaceState(null,'',url.pathname+url.search+url.hash);current=state.effectiveCurrent;state=resolveTravelMasterState(current,tabs)}const primary=document.createElement('nav');primary.className='et-tm-primary-113286';primary.dataset.etTravelMasterPrimary='113286';['Overview','Hotels','Transport Companies','Visa Management','Airlines','Booking Sources','Products & Services'].forEach(label=>{const source=byLabel(label),a=document.createElement('a');a.href=source?.href||(label==='Visa Management'?'/master-data/travel-masters/visa-management?tab=rates':'#');a.textContent=label;if(label===state.primaryActive){a.className='et-tm-active-113286';a.setAttribute('aria-current','page')}primary.appendChild(a)});nativeStrip.insertAdjacentElement('afterend',primary);const make=(key,items,active)=>{if(state.family!==key)return;const holder=document.createElement('nav');holder.className='et-tm-child-nav-113286';holder.dataset.etTravelMasterChild=key;items.forEach(label=>{const source=byLabel(label),a=document.createElement('a');a.href=source?.href||(label==='Flight Routes'?'/master-data/travel-masters/flight-routes':'#');a.textContent=label;if(label===active)a.className='et-tm-active-113286';holder.appendChild(a)});primary.insertAdjacentElement('afterend',holder)};make('transport',['Transport Companies','Vehicle Types','Transport Routes','Transport Vendor Rates'],state.transportActive);make('airlines',['Airlines','Flight Routes'],state.airlinesActive)};
 const field=(form,label)=>{const l=[...form.querySelectorAll('label')].find(x=>textNorm(x.textContent).startsWith(textNorm(label)));return l?.htmlFor?document.getElementById(l.htmlFor)?.closest('.form-group,.field,.grid-item,div'):l?.parentElement};
 const finalizeHotel=()=>{const hotelTab=tabOf(byLabel('Hotels')),current=new URL(location.href).searchParams.get('tab')||null;if(!hotelTab||current!==hotelTab)return false;const add=[...document.querySelectorAll('a,button')].find(x=>controlNorm(x.textContent)==='add hotel'),form=add?.closest('form'),bulk=document.querySelector('.et-hotel-bulk-import-113272'),address=form&&field(form,'Address'),notes=form&&field(form,'Notes'),active=form&&field(form,'Active');if(!add||!form||!bulk||!address||!notes||!active||document.querySelector('.et-tm-hotel-final-row-113286'))return false;const row=document.createElement('div'),actions=document.createElement('div');row.className='et-tm-hotel-final-row-113286';actions.className='et-tm-hotel-actions-113286';row.append(address,notes,active);actions.append(add,bulk);row.appendChild(actions);form.appendChild(row);return true};
 finalizeHierarchy();if(!finalizeHotel()&&new URL(location.href).searchParams.get('tab')===tabOf(byLabel('Hotels'))&&window.MutationObserver){const observer=new MutationObserver(()=>{if(finalizeHotel())observer.disconnect()});observer.observe(document.body,{childList:true,subtree:true});setTimeout(()=>observer.disconnect(),2500)}
})();
</script>
HTML;
  $html=str_contains($html,'</head>')?str_replace('</head>',$style.'</head>',$html):$style.$html;$html=str_contains($html,'</body>')?str_replace('</body>',$script.'</body>',$html):$html.$script;$response->setContent($html);return $response;
 }
}
