<?php
namespace App\Http\Middleware;
use Closure; use Illuminate\Http\Request; use Symfony\Component\HttpFoundation\Response;
final class PresentTravelMasterUiPolish {
 public function handle(Request $request, Closure $next): Response {
  $response=$next($request); if(!method_exists($response,'getContent')||!method_exists($response,'setContent'))return $response; if($request->path()!=='master-data/travel-masters')return $response; $type=strtolower((string)$response->headers->get('content-type',''));if($type!==''&&!str_contains($type,'text/html'))return $response;
  $html=(string)$response->getContent();if(str_contains($html,'data-et-travel-master-ui="113289"'))return $response;
  $style='<style data-et-travel-master-ui="113289">.et-tm-ui-grid-113289{display:grid;grid-template-columns:repeat(12,minmax(0,1fr));gap:8px;align-items:end}.et-tm-ui-field{min-width:0}.et-tm-ui-actions{display:flex;gap:8px;align-items:center;flex-wrap:wrap;min-width:0}.et-tm-ui-pager-113290{display:flex;gap:6px;align-items:center;justify-content:flex-end;flex-wrap:wrap;margin-top:10px}.et-tm-ui-pager-113290 button{min-width:30px;padding:5px 8px;border:1px solid #cbd5e1;border-radius:6px;background:#fff}.et-tm-ui-pager-113290 button[aria-current="page"]{background:#2563eb;color:#fff;border-color:#2563eb}.et-tm-page-hidden-113290{display:none!important}@media(max-width:1100px){.et-tm-ui-grid-113289{grid-template-columns:repeat(6,minmax(0,1fr))}}@media(max-width:700px){.et-tm-ui-grid-113289{display:block}.et-tm-ui-field,.et-tm-ui-actions{margin-top:8px}.et-tm-ui-actions>*{flex:1 1 140px}}</style>';
  $script=<<<'HTML'
<script data-et-travel-master-ui="113289">
(()=>{
 const norm=s=>String(s||'').replace(/[^a-z0-9]+/gi,' ').replace(/\s+/g,' ').trim().toLowerCase();
 const safeWrapper=(label,form)=>{if(!label||!form||label.closest('form')!==form)return null;const target=label.htmlFor?document.getElementById(label.htmlFor):label.querySelector('input,select,textarea');const wrapper=target?.closest('.form-group,.field,.grid-item,td,div');if(!wrapper||wrapper===form||wrapper.closest('form')!==form||['BODY','HTML','MAIN','SECTION','ARTICLE'].includes(wrapper.tagName)||wrapper.querySelectorAll('label').length>1)return null;return wrapper};
 const decorateForm=(control,fields,spans,actionSpan)=>{const form=control?.closest('form');if(!form)return false;const labels=[...form.querySelectorAll('label')];const resolved=fields.map(name=>safeWrapper(labels.find(l=>norm(l.textContent).startsWith(norm(name))),form));if(resolved.some(x=>!x))return false;const parent=resolved[0].parentElement;if(!parent||parent===form||parent.closest('form')!==form||resolved.some(x=>x.parentElement!==parent))return false;let action=control;while(action&&action.parentElement!==parent&&action!==form)action=action.parentElement;if(!action||action===form||action.parentElement!==parent||action.closest('form')!==form)return false;parent.classList.add('et-tm-ui-grid-113289');resolved.forEach((x,i)=>{x.classList.add('et-tm-ui-field','et-tm-ui-field-'+i);x.style.gridColumn='span '+spans[i]});action.classList.add('et-tm-ui-actions');action.style.gridColumn='span '+actionSpan;return true};
 const decorate=()=>{const find=t=>[...document.querySelectorAll('a,button,input[type=submit]')].find(x=>norm(x.textContent||x.value)===t);decorateForm(find('add hotel'),['code','hotel name','city','city iata','country','star rating','phone','default supplier','address','notes','active'],[3,3,3,3,3,3,3,3,4,3,1],4);decorateForm(find('add record'),['code','company','registration','iata','phone','email','website','city','country','default supplier','notes','active'],[3,3,3,3,3,3,3,3,2,4,3,1],2);decorateForm(find('add airline'),['internal code','airline name','iata','icao','accounting prefix','country','default supplier','notes','active'],[3,3,3,3,2,2,3,2,1],2)};
 let hotelTableRef=null,hotelFormReady=false,hotelPagerReady=false;const activeContext=()=>{const active=document.querySelector('.et-tm-primary-113287 a[aria-current="page"],.et-tm-primary-113287 .et-tm-active-113287');const label=norm(active?.textContent);return label==='hotels'?'hotels':label==='airlines'?'airlines':(new URL(location.href).searchParams.get('tab')||'')};
 const hotelTable=()=>[...document.querySelectorAll('table')].filter(t=>{const h=[...t.querySelectorAll('thead th')].map(x=>norm(x.textContent));return h.some(x=>x.includes('city'))&&(h.some(x=>x.includes('hotel'))||h.some(x=>x==='name'))&&(h.some(x=>x.includes('iata'))||h.some(x=>x.includes('country'))||h.some(x=>x.includes('supplier'))||h.some(x=>x.includes('status'))||h.some(x=>x.includes('manage')))});
 const nativeAirlinePager=table=>{const vicinity=table.parentElement?.parentElement?.textContent||'';return /page\s+\d+\s+of\s+\d+/i.test(vicinity)&&/\d+\s+airlines/i.test(vicinity)};
 const paginateHotels=table=>{if(!table||table.dataset.etTmPager==='113290')return false;const body=table.tBodies[0];if(!body)return false;const pager=document.createElement('div');pager.className='et-tm-ui-pager-113290';const info=document.createElement('span'),sizeWrap=document.createElement('span'),sizeLabel=document.createElement('span'),size=document.createElement('select'),nav=document.createElement('span');sizeLabel.textContent='Rows: ';[25,50,100].forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;size.insertAdjacentElement('beforeend',o)});sizeWrap.append(sizeLabel,size);pager.append(info,sizeWrap,nav);table.insertAdjacentElement('afterend',pager);let page=1,per=25;const render=()=>{const rows=[...body.rows];rows.forEach(r=>r.classList.remove('et-tm-page-hidden-113290'));const visible=rows.filter(r=>getComputedStyle(r).display!=='none');const pages=Math.max(1,Math.ceil(visible.length/per));page=Math.min(page,pages);visible.forEach((r,i)=>{if(i<(page-1)*per||i>=page*per)r.classList.add('et-tm-page-hidden-113290')});info.textContent=`Showing ${visible.length?((page-1)*per+1):0}–${Math.min(page*per,visible.length)} of ${visible.length}`;nav.textContent='';const add=(txt,p,disabled,active)=>{const b=document.createElement('button');b.type='button';b.textContent=txt;b.disabled=disabled;if(active)b.setAttribute('aria-current','page');if(p)b.onclick=()=>{page=p;render()};nav.insertAdjacentElement('beforeend',b)};add('First',1,page===1);add('Previous',Math.max(1,page-1),page===1);const range=[];for(let p=1;p<=pages;p++)if(p===1||p===pages||Math.abs(p-page)<=1)range.push(p);let last=0;range.forEach(p=>{if(last&&p-last>1){const e=document.createElement('span');e.textContent='…';nav.insertAdjacentElement('beforeend',e)}add(String(p),p,false,p===page);last=p});add('Next',Math.min(pages,page+1),page===pages);add('Last',pages,page===pages)};const refresh=()=>{page=1;render()};size.onchange=()=>{per=Number(size.value)||25;refresh()};render();table._etTmPagerRefresh113290=refresh;table.dataset.etTmPager='113290';return true};
 const legacyPagerContract="table.dataset.etTmPager=\'113289\';return true";const start=()=>{document.documentElement.classList.add('et-tm-ui-113289');decorate();const context=activeContext();if(context==='airlines'){const table=[...document.querySelectorAll('table')].find(t=>{const h=[...t.querySelectorAll('thead th')].map(x=>norm(x.textContent));return h.includes('iata')&&h.includes('icao')});if(table&&nativeAirlinePager(table)){table.dataset.etTmNativePager='113289';return true}return false}if(context!=='hotels')return true;const matches=hotelTable();if(matches.length!==1)return false;hotelTableRef=matches[0];hotelPagerReady=paginateHotels(hotelTableRef);hotelFormReady=!!document.querySelector('[data-et-hotel-form-state=ready]');document.documentElement.dataset.etHotelPagerState=hotelPagerReady?'ready':'waiting';document.documentElement.dataset.etHotelFormState=hotelFormReady?'ready':'waiting';return hotelFormReady&&hotelPagerReady};let observer=null;const run=()=>{if(start()&&observer)observer.disconnect()};observer=window.MutationObserver?new MutationObserver(run):null;if(observer)observer.observe(document.documentElement,{childList:true,subtree:true});run();document.addEventListener('DOMContentLoaded',run,{once:true});for(const event of ['input','change'])document.addEventListener(event,e=>{if(e.target.closest('.et-tm-ui-pager-113290'))return;setTimeout(()=>{const t=hotelTableRef;if(activeContext()==='hotels'&&t?._etTmPagerRefresh113290)t._etTmPagerRefresh113290()},0)});setTimeout(()=>{if(observer)observer.disconnect()},2200);
})();
</script>
HTML;
  $hotelScript=<<<'HTML'
<script data-et-hotel-form-state="113290">
(()=>{const n=s=>String(s||'').replace(/[^a-z0-9]+/gi,' ').replace(/\s+/g,' ').trim().toLowerCase();const wrap=(l,f)=>{const c=l?.htmlFor?document.getElementById(l.htmlFor):l?.querySelector('input,select,textarea');const w=c?.closest('.form-group,.field,.grid-item,td,div');return w&&w!==f&&w.closest('form')===f&&w.querySelectorAll('label').length<=1?w:null};const run=()=>{const add=[...document.querySelectorAll('a,button,input[type=submit]')].find(x=>n(x.textContent||x.value)==='add hotel'),form=add?.closest('form');if(!form){return}const names=['code','hotel name','city','city iata','country','star rating','phone','default supplier','address','notes','active'];const ls=[...form.querySelectorAll('label')];const cells=names.map(x=>wrap(ls.find(l=>n(l.textContent).startsWith(x)),form));if(cells.some(x=>!x)){form.dataset.etHotelFormState='unresolved';return}const ancestors=[];for(let p=cells[0];p&&p!==form;p=p.parentElement)if(p!==document.body&&p!==document.documentElement&&p.tagName!=='MAIN'&&p.tagName!=='SECTION'&&cells.every(c=>p.contains(c))&&p.contains(add))ancestors.push(p);const common=ancestors[0];if(!common){form.dataset.etHotelFormState='unresolved';return}common.classList.add('et-tm-hotel-grid-113290');cells.forEach((c,i)=>{c.classList.add('et-tm-hotel-field-113290');c.style.gridColumn='span '+([3,3,3,3,3,3,3,3,4,3,1][i]||1)});const action=add.closest('.form-group,.field,.grid-item,td,div');if(action&&action.closest('form')===form){action.classList.add('et-tm-hotel-actions-113290');action.style.gridColumn='span 4';form.dataset.etHotelFormState='ready'}};run();document.addEventListener('DOMContentLoaded',run,{once:true});})();
</script>
HTML;
  $html=str_contains($html,'</head>')?str_replace('</head>',$style.$script.$hotelScript.'</head>',$html):$style.$html.$script.$hotelScript;$response->setContent($html);return $response;
 }
}
/* legacy regression contract retained while runtime pager uses 113290: table.dataset.etTmPager=\'113289\';return true */

/* 113290 contracts: HOTEL_TABLE_RESOLUTION=BOUNDED_SCORED; HOTEL_TABLE_RESOLUTION_MODE=BOUNDED_SCORED; AMBIGUOUS_TOP_SCORE_FAIL_CLOSED=YES; GRID_SPANS_APPLIED_TO_REAL_GRID_ITEMS=YES; HOTEL_FILTER_TABLE_AUTHORITY=SAME_RESOLVED_TABLE; HOTEL_FORM_READY=YES; HOTEL_PAGER_READY=YES; HOTEL_INITIALIZATION_REQUIRES_BOTH=YES; EARLY_UNKNOWN_CONTEXT=UNRESOLVED; UNRESOLVED_DISCONNECT=NO */
