<?php
namespace App\Http\Middleware;
use Closure; use Illuminate\Http\Request; use Symfony\Component\HttpFoundation\Response;
final class PresentTravelMasterHotelBulkImport {
 public function handle(Request $request, Closure $next): Response {
  $response=$next($request); if(!method_exists($response,'getContent')||!method_exists($response,'setContent'))return $response; $type=strtolower((string)$response->headers->get('content-type','')); if($type!==''&&!str_contains($type,'text/html'))return $response; $html=(string)$response->getContent();$lower=strtolower(strip_tags($html)); if(!str_contains($lower,'travel masters')||!str_contains($lower,'hotels')||!str_contains($lower,'add hotel')||str_contains($html,'data-et-hotel-bulk-import="113272"'))return $response;
  $urls=json_encode(['template'=>route('travel-masters.hotels.bulk-template'),'preview'=>route('travel-masters.hotels.bulk-preview'),'import'=>route('travel-masters.hotels.bulk-import')],JSON_UNESCAPED_SLASHES); $style='<style id="et-hotel-bulk-import-style-113272">.et-hotel-bulk-import-113272{display:inline-flex;gap:8px;align-items:center;margin-left:8px}.et-hotel-bulk-import-113272 button,.et-hotel-bulk-import-113272 a{border:1px solid #cbd5e1;border-radius:6px;padding:7px 10px;background:#fff;color:#17396c;cursor:pointer;text-decoration:none}.et-hotel-bulk-modal-113272{position:fixed;inset:8%;z-index:9999;background:#fff;border:1px solid #cbd5e1;border-radius:10px;padding:20px;box-shadow:0 10px 40px #0003;overflow:auto}.et-hotel-bulk-modal-113272 table{width:100%;border-collapse:collapse}.et-hotel-bulk-modal-113272 th,.et-hotel-bulk-modal-113272 td{border:1px solid #e2e8f0;padding:6px;text-align:left}</style>';
  $script=<<<HTML
<script id="et-hotel-bulk-import-script-113272">(()=>{if(document.querySelector('[data-et-hotel-bulk-import="113272"]'))return;const u={$urls},n=s=>String(s||'').replace(/\s+/g,' ').trim().toLowerCase(),a=[...document.querySelectorAll('a,button')].find(x=>n(x.textContent)==='add hotel');if(!a)return;const w=document.createElement('span');w.className='et-hotel-bulk-import-113272';w.dataset.etHotelBulkImport='113272';const b=document.createElement('button');b.type='button';b.textContent='Bulk Import CSV';const d=document.createElement('a');d.href=u.template;d.textContent='Download Template';w.append(b,d);a.insertAdjacentElement('afterend',w);b.onclick=()=>{const m=document.createElement('div');m.className='et-hotel-bulk-modal-113272';m.innerHTML='<h2>Hotel Master Bulk Import</h2><label>CSV File <input type="file" accept=".csv,text/csv" data-csv-file></label><p>OR</p><textarea rows="8" style="width:100%" placeholder="City,Hotel Name" data-csv-text></textarea><p><button type="button" data-preview>Preview Import</button> <button type="button" data-close>Close</button></p><div data-result></div>';document.body.append(m);m.querySelector('[data-close]').onclick=()=>m.remove();const read=()=>new Promise(r=>{const f=m.querySelector('[data-csv-file]').files[0];if(!f)return r(m.querySelector('[data-csv-text]').value);const q=new FileReader();q.onload=()=>r(q.result);q.readAsText(f);});m.querySelector('[data-preview]').onclick=()=>read().then(csv=>fetch(u.preview,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]')?.content||''},body:JSON.stringify({csv})}).then(x=>x.json()).then(x=>{const s=x.summary||{};m.querySelector('[data-result]').innerHTML='<p>Total Rows: '+s.total+' · New: '+s.new+' · Existing: '+s.existing+' · Alias Matches: '+s.alias_matches+' · Invalid: '+s.invalid+'</p><table><thead><tr><th>Row</th><th>City</th><th>Hotel Name</th><th>Resolved City</th><th>Predicted Code</th><th>Status</th><th>Reason</th></tr></thead><tbody>'+((x.rows||[]).map(r=>'<tr><td>'+r.row+'</td><td>'+r.city+'</td><td>'+r.hotel_name+'</td><td>'+((r.resolved_city)||'')+'</td><td>'+((r.generated_code)||'')+'</td><td>'+r.status+'</td><td>'+r.reason+'</td></tr>').join(''))+'</tbody></table>'+(s.new?'<p><button type="button" data-import>Import New Hotels</button></p>':'');const ib=m.querySelector('[data-import]');if(ib)ib.onclick=()=>{if(!confirm('Import new hotels?'))return;read().then(csv=>fetch(u.import,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]')?.content||''},body:JSON.stringify({csv})}).then(x=>x.json()).then(r=>{m.querySelector('[data-result]').insertAdjacentHTML('afterbegin','<p>Import complete: '+r.rows_created+' created.</p>')}))}}));};})();</script>
HTML;
  $html=str_contains($html,'</head>')?str_replace('</head>',$style.'</head>',$html):$style.$html;$html=str_contains($html,'</body>')?str_replace('</body>',$script.'</body>',$html):$html.$script;$response->setContent($html);return $response;
 }
}
