<?php
namespace App\Http\Middleware;
use Closure; use Illuminate\Http\Request; use Symfony\Component\HttpFoundation\Response;
final class PresentTravelMasterUiPolish {
 public function handle(Request $request, Closure $next): Response {
  $response=$next($request); if(!method_exists($response,'getContent')||!method_exists($response,'setContent')) return $response;
  if($request->path()!=='master-data/travel-masters') return $response;
  $type=strtolower((string)$response->headers->get('content-type','')); if($type!==''&&!str_contains($type,'text/html')) return $response;
  $html=(string)$response->getContent(); if(str_contains($html,'data-et-travel-master-ui="113288"')) return $response;
  $style='<style data-et-travel-master-ui="113288">.et-tm-ui-113288 .et-tm-ui-field{min-width:0}.et-tm-ui-113288 .et-tm-ui-actions{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.et-tm-ui-113288 .et-tm-ui-pager{display:flex;gap:5px;align-items:center;justify-content:flex-end;flex-wrap:wrap;margin-top:10px}.et-tm-ui-113288 .et-tm-ui-pager button{min-width:30px;padding:5px 8px;border:1px solid #cbd5e1;border-radius:6px;background:#fff}.et-tm-ui-113288 .et-tm-ui-pager button[aria-current="page"]{background:#2563eb;color:#fff;border-color:#2563eb}.et-tm-page-hidden-113288{display:none!important}@media(max-width:1100px){.et-tm-ui-113288 .et-tm-ui-actions{width:100%}}@media(max-width:700px){.et-tm-ui-113288 .et-tm-ui-actions>*{flex:1 1 140px}}</style>';
  $script=<<<'HTML'
<script data-et-travel-master-ui="113288">
(()=>{
 const norm=s=>String(s||'').replace(/[^a-z0-9]+/gi,' ').replace(/\s+/g,' ').trim().toLowerCase();
 const bounded=form=>{if(!form||form===document.body||form===document.documentElement)return false;const labels=[...form.querySelectorAll('label')];return labels.length<20};
 const decorate=()=>{for(const text of ['add hotel','add record','add airline']){const control=[...document.querySelectorAll('a,button,input[type=submit]')].find(x=>norm(x.textContent||x.value)===text);const form=control?.closest('form');if(!control||!bounded(form))continue;const cell=control.closest('.form-group,.field,.grid-item,td,div');if(cell&&cell!==form&&cell.querySelectorAll('label').length<=1){cell.classList.add('et-tm-ui-actions');form.classList.add('et-tm-ui-form')}}};
 const eligible=(table,kind)=>{const heads=[...table.querySelectorAll('thead th')].map(x=>norm(x.textContent));if(kind==='hotel')return heads.some(x=>x.includes('hotel'))&&heads.some(x=>x.includes('city'));return heads.some(x=>x==='iata')&&heads.some(x=>x==='icao')&&(heads.some(x=>x.includes('airline'))||heads.some(x=>x.includes('name')))};
 const paginate=(table,kind)=>{if(!eligible(table,kind)||table.dataset.etTmPager==='113288')return;table.dataset.etTmPager='113288';const body=table.tBodies[0];if(!body)return;const all=()=>[...body.rows];const host=document.createElement('div');host.className='et-tm-ui-pager';host.dataset.etTravelMasterPager=kind;const size=document.createElement('select');[25,50,100].forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;o.label=String(v);size.insertAdjacentElement('beforeend',o)});const label=document.createElement('span');label.textContent='Rows: ';label.insertAdjacentElement('afterend',size);host.insertAdjacentElement('afterbegin',label);table.insertAdjacentElement('afterend',host);let page=1,per=25;const render=()=>{const rows=all();rows.forEach(r=>r.classList.remove('et-tm-page-hidden-113288'));const visible=rows.filter(r=>getComputedStyle(r).display!=='none');const pages=Math.max(1,Math.ceil(visible.length/per));page=Math.min(page,pages);visible.forEach((r,i)=>{if(i<((page-1)*per)||i>=page*per)r.classList.add('et-tm-page-hidden-113288')});host.querySelectorAll('button').forEach(b=>b.remove());const info=document.createElement('span');info.textContent=`Showing ${visible.length?((page-1)*per+1):0}–${Math.min(page*per,visible.length)} of ${visible.length}`;host.insertAdjacentElement('afterbegin',info);const add=(txt,p,disabled)=>{const b=document.createElement('button');b.type='button';b.textContent=txt;b.disabled=disabled;if(p)b.onclick=()=>{page=p;render()};host.insertAdjacentElement('beforeend',b)};add('First',1,page===1);add('Previous',Math.max(1,page-1),page===1);for(let p=1;p<=pages;p++){if(p===1||p===pages||Math.abs(p-page)<=1)add(String(p),p,false)}add('Next',Math.min(pages,page+1),page===pages);add('Last',pages,page===pages)};size.value='25';size.onchange=()=>{per=Number(size.value)||25;page=1;render()};render();};
 const start=()=>{document.documentElement.classList.add('et-tm-ui-113288');decorate();const tab=new URL(location.href).searchParams.get('tab')||'';const tables=[...document.querySelectorAll('table')];if(tab==='hotels')tables.filter(t=>eligible(t,'hotel')).slice(0,1).forEach(t=>paginate(t,'hotel'));if(tab==='airlines')tables.filter(t=>eligible(t,'airline')).slice(0,1).forEach(t=>paginate(t,'airline'))};let observer=null;const run=()=>{start()};observer=window.MutationObserver?new MutationObserver(run):null;if(observer)observer.observe(document.documentElement,{childList:true,subtree:true});run();document.addEventListener('DOMContentLoaded',run,{once:true});setTimeout(()=>{if(observer)observer.disconnect()},2200);
})();
</script>
HTML;
  $html=str_contains($html,'</head>')?str_replace('</head>',$style.$script.'</head>',$html):$style.$html.$script;$response->setContent($html);return $response;
 }
}
