@extends($layoutMeta['layout_view'] ?? 'layouts.app')
@section($layoutMeta['title_section'] ?? 'title', 'Party Statement')
@section($layoutMeta['content_section'] ?? 'content')
<div class="et-party-statement">
<style>.et-ps-ledger-table{font-size:9px}.et-ps-ledger-table th,.et-ps-ledger-table td{padding:3px 4px}</style>
 <header class="et-ps-page-head"><div class="et-kicker">Accounting</div><h1>Party Statement</h1><p>Combined customer/vendor commercial statement across posted receivables, payables and advances.</p></header>
 <form method="get" action="{{ route('accounting.party-statement.index') }}" class="et-ps-filters">
  <label>Party Type<select name="party_type" onchange="this.form.submit()"><option value="customer" @selected($filters['type']==='customer')>Customer</option><option value="vendor" @selected($filters['type']==='vendor')>Vendor</option></select></label>
  <label>Party<select name="party_id" required><option value="">Select party</option>@foreach($filters['parties'] as $item)<option value="{{ $item['id'] }}" @selected((int)$filters['partyId']===(int)$item['id'])>{{ $item['name'] }}</option>@endforeach</select></label>
  <label>Date From<input type="date" name="from" value="{{ $filters['from'] }}"></label><label>Date To<input type="date" name="to" value="{{ $filters['to'] }}"></label>
  <div class="et-ps-actions"><button type="submit">Apply &amp; Preview</button><button type="submit" formaction="{{ route('accounting.party-statement.print') }}" formtarget="_blank">Print</button><a href="{{ route('accounting.party-statement.index') }}">Reset</a></div>
 </form>
 @if($statement)
 @include('accounting.party-statement._document-header')
 <section class="et-ps-kpis"><div>Opening Balance<strong>{{ number_format(abs($statement['opening']),2) }} {{ $statement['opening'] < 0 ? 'Cr' : 'Dr' }}</strong></div><div>Total Debit<strong>{{ number_format($statement['total_debit'],2) }}</strong></div><div>Total Credit<strong>{{ number_format($statement['total_credit'],2) }}</strong></div><div>Closing Balance<strong>{{ number_format(abs($statement['closing']),2) }} {{ $statement['closing_side'] }}</strong><small>{{ $statement['caption'] }}</small></div></section>
 <article class="et-ps-document"><div class="et-ps-document-head"><div class="et-ps-company">@if(!empty($companyProfile['logo']))<img src="{{ $companyProfile['logo'] }}" alt="Company logo">@endif<div><strong>{{ $companyProfile['name'] ?? '' }}</strong><small>{{ $companyProfile['subtitle'] ?? '' }}</small></div></div><div><h2>{{ $filters['type']==='vendor' ? 'VENDOR ACCOUNT STATEMENT' : 'CUSTOMER ACCOUNT STATEMENT' }}</h2><p>{{ $filters['from'] }} to {{ $filters['to'] }}</p></div></div>
 <div class="et-ps-party"><strong>{{ $party['name'] ?? '—' }}</strong><span>{{ $filters['type']==='vendor' ? 'Vendor' : 'Customer' }}{{ !empty($party['code']) ? ' · '.$party['code'] : '' }}</span><span>Currency: PKR</span></div>
 <div class="et-ps-table-wrap"><table class="et-ps-ledger-table"><colgroup><col style="width:8%"><col style="width:10%"><col style="width:11%"><col style="width:9%"><col style="width:13%"><col style="width:10%"><col style="width:19%"><col style="width:7%"><col style="width:7%"><col style="width:6%"></colgroup><thead><tr><th>Date</th><th>Type</th><th>Invoice / Ref.</th><th>Product</th><th>Passenger / Group</th><th>Service Ref.</th><th>Sector / Description</th><th>Debit</th><th>Credit</th><th>Balance</th></tr></thead><tbody>@forelse($statement['rows'] as $row)<tr><td>{{ $row['date'] }}</td><td>{{ $row['type'] }}</td><td>{{ $row['reference'] ?: '—' }}</td><td>{{ $row['product'] }}</td><td>{{ $row['party'] }}</td><td>{{ $row['service_ref'] }}</td><td>{{ $row['description'] }}</td><td>{{ number_format($row['debit'],2) }}</td><td>{{ number_format($row['credit'],2) }}</td><td>{{ number_format(abs($row['balance']),2) }} {{ $row['balance'] < 0 ? 'Cr' : 'Dr' }}</td></tr>@empty<tr><td colspan="10">No posted movements found.</td></tr>@endforelse</tbody></table></div>
 <footer>Opening {{ number_format(abs($statement['opening']),2) }} · Debit {{ number_format($statement['total_debit'],2) }} · Credit {{ number_format($statement['total_credit'],2) }} · Closing {{ number_format(abs($statement['closing']),2) }} {{ $statement['closing_side'] }}<br><strong>{{ $statement['caption'] }}</strong></footer></article>
 @endif
</div>
<style>.et-party-statement{width:100%;box-sizing:border-box;padding:24px clamp(14px,2vw,28px) 32px;color:#182536}.et-ps-page-head{margin:0 0 14px}.et-ps-page-head h1{margin:0}.et-ps-page-head p{margin:4px 0 0;color:#60748d}.et-kicker{color:#1769d2;font-weight:800}.et-ps-filters{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;padding:12px;border:1px solid #dbe4ef;border-radius:8px;background:#fff}.et-ps-filters label{display:grid;gap:4px;font-size:12px;font-weight:700}.et-ps-filters input,.et-ps-filters select{min-height:34px;padding:6px;border:1px solid #cbd7e5;border-radius:5px}.et-ps-actions{grid-column:1/-1;display:flex;gap:7px;align-items:center;padding-top:2px}.et-ps-actions button,.et-ps-actions a{padding:7px 11px;border:1px solid #1769d2;border-radius:5px;background:#1769d2;color:#fff;text-decoration:none}.et-ps-actions a{background:#fff;color:#1769d2}.et-ps-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin:12px 0}.et-ps-kpis>div{padding:11px;border:1px solid #dbe4ef;border-radius:8px;background:#fff}.et-ps-kpis strong,.et-ps-kpis small{display:block;margin-top:4px}.et-ps-document{padding:14px;background:#fff;border:1px solid #dbe4ef;border-radius:8px}.et-ps-document-head{display:flex;justify-content:space-between;gap:16px;border-bottom:1px solid #dbe4ef;padding-bottom:9px}.et-ps-company{display:flex;gap:8px;align-items:center}.et-ps-company img{width:40px;height:40px;object-fit:contain}.et-ps-company strong,.et-ps-company small{display:block}.et-ps-document-head h2{margin:0;text-align:right;font-size:16px}.et-ps-document-head p{margin:3px 0 0;text-align:right;color:#60748d}.et-ps-party{display:flex;gap:15px;align-items:center;padding:9px 0}.et-ps-party span{color:#60748d;font-size:12px}.et-ps-table-wrap{overflow:visible}.et-ps-ledger-table{width:100%;max-width:100%;table-layout:fixed;border-collapse:collapse}.et-ps-document th,.et-ps-document td{padding:6px 7px;border-bottom:1px solid #e5ebf2;text-align:left;white-space:nowrap;overflow-wrap:anywhere}.et-ps-document th:nth-last-child(-n+3),.et-ps-document td:nth-last-child(-n+3){text-align:right;white-space:nowrap}.et-ps-document th:nth-child(5),.et-ps-document td:nth-child(5),.et-ps-document th:nth-child(7),.et-ps-document td:nth-child(7){white-space:normal}.et-ps-document footer{padding-top:10px;text-align:right}@media(max-width:900px){.et-ps-filters{grid-template-columns:repeat(2,minmax(0,1fr))}.et-ps-kpis{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:560px){.et-ps-filters,.et-ps-kpis{grid-template-columns:1fr}.et-ps-actions{flex-wrap:wrap}.et-ps-document-head{display:block}.et-ps-document-head h2,.et-ps-document-head p{text-align:left}.et-ps-party{flex-wrap:wrap}}</style>
@endsection
