@extends($layoutMeta['layout'])
@section($layoutMeta['title_section'] ?? 'title',$row ? 'Edit Advance Adjustment' : 'New Advance Adjustment')
@section($layoutMeta['content_section'] ?? 'content')
<style>.aa-wrap{max-width:1250px;margin:0 auto}.aa-head{display:flex;justify-content:space-between;gap:12px;margin-bottom:14px}.aa-card{background:#fff;border:1px solid #dfe6ef;border-radius:10px;padding:16px;margin-bottom:13px}.aa-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:13px}.aa-field label{display:block;font-size:11px;font-weight:800;color:#4b5e73;margin-bottom:5px}.aa-field input,.aa-field select,.aa-field textarea{width:100%;border:1px solid #d3dce7;border-radius:7px;padding:9px;font-size:12px}.aa-field textarea{min-height:80px}.aa-btn{display:inline-flex;padding:9px 14px;border:1px solid #cbd5e1;border-radius:7px;background:#fff;color:#26384e;text-decoration:none!important;font-size:12px;font-weight:700}.aa-primary{background:#0d5bd7;border-color:#0d5bd7;color:#fff!important}.aa-info{padding:10px 12px;background:#f5f9fe;border:1px solid #d7e5f6;border-radius:7px;font-size:12px;color:#536b84}.aa-actions{display:flex;justify-content:flex-end;gap:8px}@media(max-width:700px){.aa-grid{grid-template-columns:1fr}.aa-actions{flex-direction:column}.aa-btn{justify-content:center}}</style>
<div class="aa-wrap"><div class="aa-head"><div><div style="font-size:11px;font-weight:800;color:#0d5bd7">ACCOUNTING</div><h2 style="margin:3px 0">{{ $row ? 'Edit '.$row->adjustment_no : 'Apply an Advance' }}</h2><div style="font-size:12px;color:#718096">Apply an existing advance to an invoice or supplier payable.</div></div><a class="aa-btn" href="{{ route('accounting.cash-vouchers.index') }}#advance-adjustments">Back</a></div>
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<form method="post" action="{{ $row ? route('accounting.advance-adjustments.update',$row->id) : route('accounting.advance-adjustments.store') }}">@csrf @if($row)@method('PUT')@endif
<div class="aa-card"><div class="aa-grid">
<div class="aa-field"><label>Available Advance *</label><select name="advance_voucher_id" id="advanceSelect" required><option value="">Select posted advance</option>@foreach($advances as $a)<option value="{{ $a['id'] }}" @selected((string)old('advance_voucher_id',$row->advance_voucher_id ?? '')===(string)$a['id'])>{{ $a['voucher_no'] }} · {{ $a['party_name'] }} · {{ $a['currency_code'] }} {{ number_format($a['available'],2) }} available</option>@endforeach</select></div>
<div class="aa-field"><label>Target Document *</label><select name="target_id" id="targetSelect" required><option value="">Select advance first</option></select></div>
<div class="aa-field"><label>Adjustment Date *</label><input type="date" name="adjustment_date" value="{{ old('adjustment_date',$row->adjustment_date ?? now()->toDateString()) }}" required></div>
<div class="aa-field"><label>Amount *</label><input type="number" step="0.01" min="0.01" name="amount" id="adjustmentAmount" value="{{ old('amount',$row->amount ?? '0.00') }}" required></div>
<div class="aa-field" style="grid-column:span 2"><label>Remarks</label><textarea name="remarks">{{ old('remarks',$row->remarks ?? '') }}</textarea></div>
</div></div>
<div class="aa-info" id="advanceInfo">Choose a Posted customer/supplier advance. Customer advances can only settle Sales Invoices; supplier advances can only settle Posted Supplier Costing documents.</div>
<div class="aa-actions" style="margin-top:13px"><a class="aa-btn" href="{{ route('accounting.cash-vouchers.index') }}#advance-adjustments">Cancel</a><button class="aa-btn aa-primary">Save Draft</button></div>
</form></div>
<script>
(()=>{const advances=@json($advances),sales=@json($salesInvoices),costs=@json($supplierCostings);const a=document.getElementById('advanceSelect'),t=document.getElementById('targetSelect'),info=document.getElementById('advanceInfo');const selected=@json(old('target_id',$row->target_id ?? ''));
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function refresh(){const av=advances.find(x=>Number(x.id)===Number(a.value));if(!av){t.innerHTML='<option value="">Select advance first</option>';info.textContent='Choose a Posted customer/supplier advance. Customer advances can only settle Sales Invoices; supplier advances can only settle Posted Supplier Costing documents.';return}const docs=(av.party_type==='supplier'?costs:sales).filter(d=>(!av.party_id||!d.party_id||Number(av.party_id)===Number(d.party_id))&&String(d.currency_code||'PKR').toUpperCase()===String(av.currency_code||'PKR').toUpperCase());t.innerHTML='<option value="">Select target document</option>'+docs.map(d=>`<option value="${d.id}" ${Number(selected)===Number(d.id)?'selected':''}>${esc(d.number)} · ${esc(d.currency_code)} ${Number(d.outstanding||0).toFixed(2)} outstanding</option>`).join('');info.innerHTML=`<strong>${esc(av.voucher_no)}</strong> · ${esc(av.party_name)} · ${esc(av.currency_code)} ${Number(av.available||0).toFixed(2)} available · will settle ${av.party_type==='supplier'?'Accounts Payable':'Accounts Receivable'}.`}
a.addEventListener('change',refresh);refresh()})();
</script>
@endsection
