@extends($layoutMeta['layout'])
@section($layoutMeta['title_section'] ?? 'title',$row ? 'Edit Advance Adjustment' : 'New Advance Adjustment')
@section($layoutMeta['content_section'] ?? 'content')
<div class="aa-wrap"><h2>{{ $row ? 'Edit Advance Adjustment' : 'Apply an Advance' }}</h2>
<form method="post" action="{{ $row ? route('accounting.advance-adjustments.update',$row->id) : route('accounting.advance-adjustments.store') }}">@csrf @if($row)@method('PUT')@endif
<label>Advance Source <select name="advance_source_key" id="advance-source" required><option value="">Select source</option>@foreach($advances as $a)<option value="{{ $a['advance_source_type'].':'.$a['advance_source_id'] }}" data-source-type="{{ $a['advance_source_type'] }}" data-source-id="{{ $a['advance_source_id'] }}" data-party="{{ $a['party_type'] }}" data-party-id="{{ $a['party_id'] }}" data-currency="{{ $a['currency_code'] }}" data-available="{{ $a['available_amount'] }}" @selected($row && ($row->advance_source_type ?: 'cash_voucher').':'.($row->advance_source_id ?: $row->advance_voucher_id)===$a['advance_source_type'].':'.$a['advance_source_id'])>{{ $a['source_number'] }} · {{ $a['advance_source_type'] }} · {{ $a['party_name'] }} · {{ $a['currency_code'] }} {{ number_format($a['available_amount'],2) }}</option>@endforeach</select><input type="hidden" name="advance_source_type" id="advance-source-type" value="{{ old('advance_source_type',$row->advance_source_type ?? 'cash_voucher') }}"><input type="hidden" name="advance_source_id" id="advance-source-id" value="{{ old('advance_source_id',$row->advance_source_id ?? $row->advance_voucher_id ?? '') }}"></label>
<label>Target <select name="target_key" id="target" required><option value="">Select target</option></select><input type="hidden" name="target_type" id="target-type" value="{{ old('target_type',$row->target_type ?? '') }}"><input type="hidden" name="target_id" id="target-id" value="{{ old('target_id',$row->target_id ?? '') }}"></label>
<label>Date <input type="date" name="adjustment_date" value="{{ old('adjustment_date',$row->adjustment_date ?? now()->toDateString()) }}" required></label><label>Amount <input type="number" step="0.01" min="0.01" name="amount" value="{{ old('amount',$row->amount ?? '') }}" required></label><label>Remarks <textarea name="remarks">{{ old('remarks',$row->remarks ?? '') }}</textarea></label><button type="submit">Save Draft</button></form></div>
<script>const src=document.getElementById('advance-source'),sourceType=document.getElementById('advance-source-type'),sourceId=document.getElementById('advance-source-id'),target=document.getElementById('target'),targetType=document.getElementById('target-type'),targetId=document.getElementById('target-id');const docs=[...@json(array_merge($salesInvoices,$supplierCostings))];const selectedTargetKey='{{ old('target_type',$row->target_type ?? '').':'.old('target_id',$row->target_id ?? '') }}';function refresh(){const o=src.selectedOptions[0];sourceType.value=o?.dataset.sourceType||'cash_voucher';sourceId.value=o?.dataset.sourceId||'';const party=o?.dataset.party;const currency=o?.dataset.currency;const list=docs.filter(d=>(party==='supplier'?['supplier_costing','party_opening_payable']:['sales_invoice','party_opening_balance']).includes(d.target_type)&&String(d.currency_code||'PKR').toUpperCase()===String(currency||'PKR').toUpperCase()&&(!o?.dataset.partyId||String(d.party_id||'')===String(o.dataset.partyId)));target.innerHTML='<option value="">Select target</option>'+list.map(d=>{const key=`${d.target_type}:${d.id}`;return `<option value="${key}" data-type="${d.target_type}" data-id="${d.id}" ${key===selectedTargetKey?'selected':''}>${d.number} · ${d.target_type} · ${d.currency_code} ${Number(d.outstanding||0).toFixed(2)}</option>`}).join('');syncTarget()}function syncTarget(){const o=target.selectedOptions[0];targetType.value=o?.dataset.type||'';targetId.value=o?.dataset.id||''}src.addEventListener('change',refresh);target.addEventListener('change',syncTarget);refresh();</script>
@endsection
