@extends($layoutMeta['layout'])
@section($layoutMeta['title_section'] ?? 'title',$row->adjustment_no)
@section($layoutMeta['content_section'] ?? 'content')
<style>.aa-wrap{max-width:1300px;margin:0 auto}.aa-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;margin-bottom:14px;flex-wrap:wrap}.aa-actions{display:flex;gap:7px;flex-wrap:wrap}.aa-btn{display:inline-flex;padding:8px 12px;border:1px solid #cbd5e1;border-radius:7px;background:#fff;color:#26384e;text-decoration:none!important;font-size:12px;font-weight:700}.aa-primary{background:#0d5bd7;border-color:#0d5bd7;color:#fff!important}.aa-success{background:#147d64;border-color:#147d64;color:#fff!important}.aa-danger{border-color:#e3a9af;color:#a12835!important}.aa-card{background:#fff;border:1px solid #dfe6ef;border-radius:10px;padding:15px;margin-bottom:13px}.aa-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.aa-item{font-size:12px}.aa-item b{display:block;font-size:10px;color:#6b7b8f;text-transform:uppercase;margin-bottom:3px}.aa-badge{display:inline-flex;padding:4px 8px;background:#eef3f8;border-radius:999px;font-size:10px;font-weight:800;text-transform:uppercase}.aa-table{width:100%;border-collapse:collapse}.aa-table th,.aa-table td{padding:9px;border-bottom:1px solid #edf1f6;text-align:left;font-size:12px}.aa-table th{background:#f8fafc;color:#526174;font-size:10px;text-transform:uppercase}@media(max-width:800px){.aa-grid{grid-template-columns:1fr 1fr}}@media(max-width:540px){.aa-grid{grid-template-columns:1fr}}</style>
<div class="aa-wrap"><div class="aa-head"><div><div style="font-size:11px;font-weight:800;color:#0d5bd7">ADVANCE ADJUSTMENT · ERP-11.3</div><h2 style="margin:3px 0">{{ $row->adjustment_no }}</h2><span class="aa-badge">{{ str_replace('_',' ',$row->status) }}</span></div><div class="aa-actions"><a class="aa-btn" href="{{ route('accounting.cash-vouchers.index') }}#advance-adjustments">Register</a>@if($row->status==='draft')<a class="aa-btn" href="{{ route('accounting.advance-adjustments.edit',$row->id) }}">Edit Draft</a><form method="post" action="{{ route('accounting.advance-adjustments.workflow',[$row->id,'submit']) }}">@csrf<button class="aa-btn aa-primary">Submit</button></form>@elseif($row->status==='pending_approval'&&$canApprove)<form method="post" action="{{ route('accounting.advance-adjustments.workflow',[$row->id,'approve']) }}">@csrf<button class="aa-btn aa-primary">Approve</button></form>@elseif($row->status==='approved'&&$canApprove)<form method="post" action="{{ route('accounting.advance-adjustments.workflow',[$row->id,'post']) }}">@csrf<button class="aa-btn aa-success">Post Adjustment</button></form>@endif</div></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="aa-card"><div class="aa-grid"><div class="aa-item"><b>Source Advance</b><a href="{{ route('accounting.cash-vouchers.show',$source->id) }}">{{ $source->voucher_no }}</a></div><div class="aa-item"><b>Party</b>{{ $row->party_name ?: '—' }}</div><div class="aa-item"><b>Target</b>{{ $row->target_number ?: ucfirst(str_replace('_',' ',$row->target_type)).' #'.$row->target_id }}</div><div class="aa-item"><b>Date</b>{{ \Carbon\Carbon::parse($row->adjustment_date)->format('d/m/Y') }}</div><div class="aa-item"><b>Amount</b><strong>{{ $row->currency_code }} {{ number_format($row->amount,2) }}</strong></div><div class="aa-item"><b>FX Rate</b>{{ number_format($row->exchange_rate,8) }}</div><div class="aa-item"><b>Posting Ref</b>{{ $row->posting_reference ?: '—' }}</div><div class="aa-item"><b>Available Advance Now</b>{{ $availableNow===null?'Posted':$row->currency_code.' '.number_format($availableNow,2) }}</div><div class="aa-item" style="grid-column:span 4"><b>Remarks</b>{{ $row->remarks ?: '—' }}</div></div></div>
@if($postings->isNotEmpty())<div class="aa-card"><h4 style="margin:0 0 8px">Accounting Posting</h4><table class="aa-table"><thead><tr><th>Account</th><th>Narration</th><th>Debit</th><th>Credit</th></tr></thead><tbody>@foreach($postings as $p)<tr><td>{{ $p->account_code }} · {{ $p->account_name }} @if($p->entry_type==='reversal')<span class="aa-badge">Reversal</span>@endif</td><td>{{ $p->narration }}</td><td>{{ number_format($p->debit,2) }}</td><td>{{ number_format($p->credit,2) }}</td></tr>@endforeach</tbody></table></div>@endif
@if($row->status==='posted'&&$canApprove)<div class="aa-card"><h4 style="margin:0 0 7px;color:#9c2735">Controlled Reversal</h4><form method="post" action="{{ route('accounting.advance-adjustments.reverse',$row->id) }}" style="display:flex;gap:7px">@csrf<input name="reason" required placeholder="Reason for reversal" style="flex:1;border:1px solid #d5dde7;border-radius:7px;padding:8px"><button class="aa-btn aa-danger">Reverse Adjustment</button></form></div>@endif
@if($row->status==='reversed')<div class="aa-card" style="background:#fffafa;border-color:#e8b8bd"><strong>Reversed:</strong> {{ $row->reversal_reference }} · {{ $row->reversal_reason }}</div>@endif
<div class="aa-card"><h4 style="margin:0 0 8px">Audit Trail</h4><table class="aa-table"><thead><tr><th>Time</th><th>Action</th><th>Status</th><th>User</th><th>Notes</th></tr></thead><tbody>@foreach($activities as $a)<tr><td>{{ \Carbon\Carbon::parse($a->created_at)->format('d/m/Y H:i') }}</td><td>{{ ucfirst($a->action) }}</td><td>{{ $a->from_status ?: '—' }} → {{ $a->to_status ?: '—' }}</td><td>{{ $a->user_name ?: '—' }}</td><td>{{ $a->notes ?: '—' }}</td></tr>@endforeach</tbody></table></div></div>
@endsection
