<?php

namespace App\Services\Accounting;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use RuntimeException;

/** Controlled opening-balance and customer payment/refund authority. */
final class PartyBalanceLifecycleService
{
    public function __construct(private readonly AccountingPartyRoleResolver $roles, private readonly ChartOfAccountsWorkspaceService $chart, private readonly CashVoucherService $cash, private readonly CashVoucherNativeJournalBridge $native, private readonly PartyAdvanceBalanceService $advances) {}

    public function parties(string $type): array { return $this->roles->options($type === 'vendor' ? 'supplier' : 'customer'); }

    public function assertBranchForUser(int $branchId, mixed $user): void
    {
        $this->assertBranch($branchId);
        foreach (['primary_branch_id','branch_id','home_branch_id'] as $key) {
            $value = $user?->{$key} ?? null;
            if ($value !== null && (int)$value > 0 && (int)$value !== $branchId) throw new RuntimeException('The selected branch is outside your authorized branch scope.');
        }
    }

    public function mapping(string $key): array
    {
        $s = $this->chart->schema();
        if (!$s['control_type']) throw new RuntimeException('Opening Balance / Migration Clearing account is not configured.');
        $row = DB::table($s['table'])->whereRaw('UPPER('.$s['control_type'].') = ?', [strtoupper($key)])->first();
        if (!$row || !$this->isPosting($row, $s) || ($s['control_flag'] ?? null) && property_exists($row, $s['control_flag']) && !((bool)$row->{$s['control_flag']})) throw new RuntimeException('Opening Balance / Migration Clearing account is not configured.');
        return ['id'=>(int)$row->{$s['id']},'code'=>(string)$row->{$s['code']},'name'=>(string)$row->{$s['name']}];
    }

    public function createOpening(array $data, mixed $user): int
    {
        $type=(string)$data['party_type']; $role=$type==='vendor'?'supplier':'customer'; $party=$this->roles->assertRole((int)$data['party_id'],$role); $this->assertOpeningType($type,(string)$data['opening_type']); $this->assertBranch((int)$data['branch_id']); $this->mapping('OPENING_BALANCE_CLEARING');
        $now=now(); $id=DB::table('party_opening_balances')->insertGetId(['document_no'=>'POB-'.date('YmdHis').'-'.random_int(100,999),'party_type'=>$type,'party_id'=>$party['party_id'],'party_name'=>$party['party_name'],'opening_type'=>$data['opening_type'],'opening_date'=>$data['opening_date'],'amount'=>round((float)$data['amount'],2),'currency_code'=>strtoupper($data['currency_code']??'PKR'),'exchange_rate'=>(float)($data['exchange_rate']??1),'branch_id'=>(int)$data['branch_id'],'company_id'=>$data['company_id']??null,'reference'=>$data['reference']??null,'narration'=>$data['narration']??null,'supporting_document'=>$data['supporting_document']??null,'status'=>'draft','created_by'=>$user?->id,'created_at'=>$now,'updated_at'=>$now]); DB::table('party_opening_balance_activities')->insert(['party_opening_balance_id'=>$id,'action'=>'create','to_status'=>'draft','user_id'=>$user?->id,'remarks'=>'Opening balance draft created.','created_at'=>$now,'updated_at'=>$now]); return $id;
    }

    public function transitionOpening(int $id,string $action,mixed $user): void
    {
        DB::transaction(function() use($id,$action,$user): void { $row=DB::table('party_opening_balances')->where('id',$id)->lockForUpdate()->first(); if(!$row) throw new RuntimeException('Opening balance not found.'); $next=['submit'=>'pending_approval','approve'=>'approved','post'=>'posted'][$action]??null; if(!$next) throw new RuntimeException('Unsupported opening balance action.'); if(($action==='submit'&&$row->status!=='draft')||($action==='approve'&&$row->status!=='pending_approval')||($action==='post'&&$row->status!=='approved')) throw new RuntimeException('Opening balance lifecycle transition is not allowed.'); $this->assertBranchForUser((int)$row->branch_id,$user); if($action==='post') $this->postOpening($row,$user); $now=now(); DB::table('party_opening_balances')->where('id',$id)->update(['status'=>$next,$action==='approve'?'approved_by':'posted_by'=>$user?->id,$action==='approve'?'approved_at':'posted_at'=>$now,'updated_at'=>$now]); DB::table('party_opening_balance_activities')->insert(['party_opening_balance_id'=>$id,'action'=>$action,'from_status'=>$row->status,'to_status'=>$next,'user_id'=>$user?->id,'remarks'=>'Workflow transition.','created_at'=>$now,'updated_at'=>$now]); });
    }

    public function reverseOpening(int $id,string $reason,mixed $user): void
    {
        DB::transaction(function() use($id,$reason,$user): void { $row=DB::table('party_opening_balances')->where('id',$id)->lockForUpdate()->first(); if(!$row||$row->status!=='posted') throw new RuntimeException('Only posted opening balances can be reversed.'); $original=DB::table('party_opening_balance_posting_lines')->where('party_opening_balance_id',$id)->where('entry_type','original')->get(); $lines=$this->invert($original); $this->insertOpeningLines($id,$lines,'reversal'); $doc=$this->document($row); $this->native->postControlledDocument($doc,DB::table('party_opening_balance_posting_lines')->where('party_opening_balance_id',$id)->where('entry_type','reversal')->get(),'party_opening_balance_reversal',$id,'POBREV-'.$row->id,'Party opening balance reversal',$user,$row->posting_journal_id,'party_opening_balance','party_opening_balance_posting_line'); $now=now(); DB::table('party_opening_balances')->where('id',$id)->update(['status'=>'reversed','reversal_reference'=>'POBREV-'.$row->id,'reversed_at'=>$now,'reversal_reason'=>$reason,'updated_at'=>$now]); DB::table('party_opening_balance_activities')->insert(['party_opening_balance_id'=>$id,'action'=>'reverse','from_status'=>'posted','to_status'=>'reversed','user_id'=>$user?->id,'remarks'=>$reason,'created_at'=>$now,'updated_at'=>$now]); });
    }

    public function creditSources(int $partyId): array
    {
        $this->roles->resolveCustomer($partyId); $out=[];
        $rows=DB::table('party_opening_balances')->where('party_type','customer')->where('party_id',$partyId)->where('opening_type','customer_credit')->where('status','posted')->orderBy('id')->get();
        foreach($rows as $r){$used=(float)DB::table('customer_payment_allocations')->where('source_type','opening_credit')->where('source_id',$r->id)->whereIn('customer_payment_id',DB::table('customer_payments')->where('status','posted')->pluck('id'))->sum('amount');$available=round((float)$r->amount-$used,2);if($available>0) $out[]=['source_type'=>'opening_credit','source_id'=>(int)$r->id,'source_reference'=>$r->document_no,'original_amount'=>(float)$r->amount,'used_amount'=>$used,'available_amount'=>$available,'currency_code'=>$r->currency_code,'party_id'=>(int)$r->party_id];}
        foreach($this->cash->advanceOptions('customer') as $r) $out[]=['source_type'=>'customer_advance','source_id'=>(int)$r['id'],'source_reference'=>$r['voucher_no'],'original_amount'=>(float)$r['available'],'used_amount'=>0,'available_amount'=>(float)$r['available'],'currency_code'=>$r['currency_code'],'party_id'=>(int)$r['party_id']];
        return $out;
    }

    public function createPayment(array $data,mixed $user): int
    {
        $party=$this->roles->resolveCustomer((int)$data['party_id']); $this->assertBranch((int)$data['branch_id']); $bank=$this->cash->cashBankAccount((string)$data['cash_bank_account']); $this->assertSources((int)$data['party_id'],(array)($data['allocations']??[]),(float)$data['amount'],strtoupper($data['currency_code']??'PKR'));
        $now=now(); $id=DB::table('customer_payments')->insertGetId(['document_no'=>'CPR-'.date('YmdHis').'-'.random_int(100,999),'party_id'=>$party['party_id'],'party_name'=>$party['party_name'],'payment_date'=>$data['payment_date'],'amount'=>round((float)$data['amount'],2),'currency_code'=>strtoupper($data['currency_code']??'PKR'),'exchange_rate'=>(float)($data['exchange_rate']??1),'branch_id'=>(int)$data['branch_id'],'company_id'=>$data['company_id']??null,'cash_bank_account_code'=>$bank['code'],'cash_bank_account_name'=>$bank['name'],'payment_method'=>$data['payment_method']??null,'reference'=>$data['reference']??null,'reason'=>$data['reason'],'narration'=>$data['narration']??null,'status'=>'draft','created_by'=>$user?->id,'created_at'=>$now,'updated_at'=>$now]);
        foreach((array)$data['allocations'] as $i=>$a) DB::table('customer_payment_allocations')->insert(['customer_payment_id'=>$id,'line_no'=>$i+1,'source_type'=>$a['source_type'],'source_id'=>(int)$a['source_id'],'source_reference'=>$a['source_reference'],'original_amount'=>(float)$a['original_amount'],'used_amount'=>(float)($a['used_amount']??0),'amount'=>(float)$a['amount'],'currency_code'=>strtoupper($data['currency_code']??'PKR'),'party_id'=>$party['party_id'],'created_at'=>$now,'updated_at'=>$now]);
        DB::table('customer_payment_activities')->insert(['customer_payment_id'=>$id,'action'=>'create','to_status'=>'draft','user_id'=>$user?->id,'remarks'=>'Customer Payment / Refund draft created.','created_at'=>$now,'updated_at'=>$now]); return $id;
    }

    public function transitionPayment(int $id,string $action,mixed $user): void
    { DB::transaction(function()use($id,$action,$user):void{$r=DB::table('customer_payments')->where('id',$id)->lockForUpdate()->first();if(!$r)throw new RuntimeException('Customer Payment / Refund not found.');$next=['submit'=>'pending_approval','approve'=>'approved','post'=>'posted'][$action]??null;if(!$next||$r->status!==['submit'=>'draft','approve'=>'pending_approval','post'=>'approved'][$action])throw new RuntimeException('Customer Payment / Refund lifecycle transition is not allowed.');$this->assertBranchForUser((int)$r->branch_id,$user);if($action==='post'){$alloc=DB::table('customer_payment_allocations')->where('customer_payment_id',$id)->lockForUpdate()->get();$this->assertSources((int)$r->party_id,$alloc->map(fn($x)=>(array)$x)->all(),(float)$r->amount,$r->currency_code);$this->postPayment($r,$alloc,$user);}$now=now();DB::table('customer_payments')->where('id',$id)->update(['status'=>$next,$action==='approve'?'approved_by':'posted_by'=>$user?->id,$action==='approve'?'approved_at':'posted_at'=>$now,'updated_at'=>$now]);DB::table('customer_payment_activities')->insert(['customer_payment_id'=>$id,'action'=>$action,'from_status'=>$r->status,'to_status'=>$next,'user_id'=>$user?->id,'remarks'=>'Workflow transition.','created_at'=>$now,'updated_at'=>$now]);}); }

    public function reversePayment(int $id,string $reason,mixed $user): void
    { DB::transaction(function()use($id,$reason,$user):void{$r=DB::table('customer_payments')->where('id',$id)->lockForUpdate()->first();if(!$r||$r->status!=='posted')throw new RuntimeException('Only posted customer payments can be reversed.');$orig=DB::table('customer_payment_posting_lines')->where('customer_payment_id',$id)->where('entry_type','original')->get();$this->insertPaymentLines($id,$this->invert($orig),'reversal');$doc=$this->paymentDocument($r);$this->native->postControlledDocument($doc,DB::table('customer_payment_posting_lines')->where('customer_payment_id',$id)->where('entry_type','reversal')->get(),'customer_payment_reversal',$id,'CPRREV-'.$id,'Customer payment reversal',$user,$r->posting_journal_id,'customer_payment','customer_payment_posting_line');$now=now();DB::table('customer_payments')->where('id',$id)->update(['status'=>'reversed','reversal_reference'=>'CPRREV-'.$id,'reversed_at'=>$now,'reversal_reason'=>$reason,'updated_at'=>$now]);DB::table('customer_payment_activities')->insert(['customer_payment_id'=>$id,'action'=>'reverse','from_status'=>'posted','to_status'=>'reversed','user_id'=>$user?->id,'remarks'=>$reason,'created_at'=>$now,'updated_at'=>$now]);}); }

    private function postOpening(object $r,mixed $user): void { $clear=$this->mapping('OPENING_BALANCE_CLEARING');$map=['customer_receivable'=>[['CUSTOMER_AR','Customer Receivables',$r->amount,0],['CLEAR',$clear['name'],0,$r->amount]],'customer_advance'=>[['CLEAR',$clear['name'],$r->amount,0],['CUSTOMER_ADVANCE','Customer Advances',0,$r->amount]],'vendor_payable'=>[['CLEAR',$clear['name'],$r->amount,0],['VENDOR_AP','Vendor Payables',0,$r->amount]],'vendor_advance'=>[['VENDOR_ADVANCE','Vendor Advances',$r->amount,0],['CLEAR',$clear['name'],0,$r->amount]]][$r->opening_type]??null;if(!$map)throw new RuntimeException('Unsupported opening balance type.');$lines=[];foreach($map as $i=>$x){$acct=$x[0]==='CLEAR'?$clear:$this->control($x[0]);$lines[]=['account_code'=>$acct['code'],'account_name'=>$acct['name'],'party_type'=>$x[0]==='CLEAR'?null:$r->party_type,'party_id'=>$x[0]==='CLEAR'?null:$r->party_id,'debit'=>$x[2],'credit'=>$x[3],'currency_code'=>$r->currency_code,'exchange_rate'=>$r->exchange_rate,'narration'=>$r->narration,'line_no'=>$i+1,'id'=>$i+1];}$this->insertOpeningLines($r->id,$lines,'original');$jid=$this->native->postControlledDocument($this->document($r),DB::table('party_opening_balance_posting_lines')->where('party_opening_balance_id',$r->id)->where('entry_type','original')->get(),'party_opening_balance',$r->id,$r->document_no,'Party opening balance',$user,null,'party_opening_balance','party_opening_balance_posting_line');DB::table('party_opening_balances')->where('id',$r->id)->update(['posting_journal_id'=>$jid]); }
    private function postPayment(object $r,$alloc,mixed $user): void { $lines=[];$n=1;foreach($alloc as $a){$acct=$a->source_type==='opening_credit'?$this->control('CUSTOMER_AR'):$this->control('CUSTOMER_ADVANCE');$lines[]=['account_code'=>$acct['code'],'account_name'=>$acct['name'],'party_type'=>'customer','party_id'=>$r->party_id,'debit'=>$a->amount,'credit'=>0,'currency_code'=>$r->currency_code,'exchange_rate'=>$r->exchange_rate,'narration'=>$r->narration,'line_no'=>$n++,'id'=>$n];}$lines[]=['account_code'=>$r->cash_bank_account_code,'account_name'=>$r->cash_bank_account_name,'party_type'=>null,'party_id'=>null,'debit'=>0,'credit'=>$r->amount,'currency_code'=>$r->currency_code,'exchange_rate'=>$r->exchange_rate,'narration'=>$r->narration,'line_no'=>$n,'id'=>$n];$this->insertPaymentLines($r->id,$lines,'original');$jid=$this->native->postControlledDocument($this->paymentDocument($r),DB::table('customer_payment_posting_lines')->where('customer_payment_id',$r->id)->where('entry_type','original')->get(),'customer_payment',$r->id,$r->document_no,'Customer Payment / Refund',$user,null,'customer_payment','customer_payment_posting_line');DB::table('customer_payments')->where('id',$r->id)->update(['posting_journal_id'=>$jid]); }
    private function assertSources(int $partyId,array $alloc,float $amount,string $currency): void {$this->roles->resolveCustomer($partyId);foreach($alloc as $a){if($a['source_type']==='opening_credit')DB::table('party_opening_balances')->where('id',(int)$a['source_id'])->lockForUpdate()->first();if($a['source_type']==='customer_advance')DB::table('cash_vouchers')->where('id',(int)$a['source_id'])->lockForUpdate()->first();}$sources=$this->creditSources($partyId);$sum=0;foreach($alloc as $a){$ok=collect($sources)->first(fn($s)=>(string)$s['source_type']===(string)$a['source_type']&&(int)$s['source_id']===(int)$a['source_id']);if(!$ok||strtoupper($ok['currency_code'])!==strtoupper($currency)||(float)$a['amount']>(float)$ok['available_amount']+0.005)throw new RuntimeException('Customer payment exceeds the selected available customer credit.');$sum+=(float)$a['amount'];}if(abs($sum-$amount)>0.005)throw new RuntimeException('Customer Payment / Refund must be fully allocated to eligible customer credit.');}
    private function assertOpeningType(string $partyType,string $openingType): void { $allowed=$partyType==='customer'?['customer_receivable','customer_advance']:['vendor_payable','vendor_advance']; if(!in_array($openingType,$allowed,true))throw new RuntimeException('Opening type does not match the selected party role.'); }
    private function assertBranch(int $branchId): void { if($branchId<=0)throw new RuntimeException('A valid branch is required.'); foreach(['branches','branch_master','branch_masters','offices','office_master','office_masters'] as $table){if(Schema::hasTable($table)&&Schema::hasColumn($table,'id')&&DB::table($table)->where('id',$branchId)->exists())return;} throw new RuntimeException('The selected branch is not available.'); }
    private function control(string $key): array {$defs=['CUSTOMER_AR'=>['CUSTOMER_AR','1130','Customer Receivables'],'CUSTOMER_ADVANCE'=>['CUSTOMER_ADVANCE','2120','Customer Advances'],'VENDOR_AP'=>['VENDOR_AP','2110','Vendor Payables'],'VENDOR_ADVANCE'=>['VENDOR_ADVANCE','1140','Vendor Advances']];$d=$defs[$key]??null;if(!$d)throw new RuntimeException('Required accounting control account is not configured.');$s=$this->chart->schema();if(!$s['control_type'])throw new RuntimeException('Required accounting control account is not configured.');$r=DB::table($s['table'])->whereRaw('UPPER('.$s['control_type'].') = ?',[$key])->first();if(!$r)throw new RuntimeException('Required accounting control account is not configured.');return ['code'=>(string)$r->{$s['code']},'name'=>(string)$r->{$s['name']}];}
    private function isPosting(object $r,array $s): bool {foreach(['active','is_active'] as $c)if($s[$c]&&!((bool)$r->{$s[$c]}))return false;foreach(['is_header','header'] as $c)if(isset($s[$c])&&$s[$c]&&property_exists($r,$s[$c])&&((bool)$r->{$s[$c]}))return false;foreach(['posting','allow_posting','posting_enabled','is_posting'] as $c)if(isset($s[$c])&&$s[$c]&&property_exists($r,$s[$c])&&!((bool)$r->{$s[$c]}))return false;return true;}
    private function invert($rows): array {return collect($rows)->map(function($r){$x=(array)$r;$d=$x['debit'];$x['debit']=$x['credit'];$x['credit']=$d;$d=$x['base_debit']??0;$x['base_debit']=$x['base_credit']??0;$x['base_credit']=$d;return $x;})->all();}
    private function insertOpeningLines(int $id,array $lines,string $entry): void {foreach($lines as $i=>$l)DB::table('party_opening_balance_posting_lines')->insert(['party_opening_balance_id'=>$id,'line_no'=>$i+1,'account_code'=>$l['account_code'],'account_name'=>$l['account_name'],'party_type'=>$l['party_type']??null,'party_id'=>$l['party_id']??null,'debit'=>$l['debit'],'credit'=>$l['credit'],'base_debit'=>$l['debit']*$l['exchange_rate'],'base_credit'=>$l['credit']*$l['exchange_rate'],'currency_code'=>$l['currency_code'],'exchange_rate'=>$l['exchange_rate'],'entry_type'=>$entry,'narration'=>$l['narration']??null,'created_at'=>now(),'updated_at'=>now()]);}
    private function insertPaymentLines(int $id,array $lines,string $entry): void {foreach($lines as $i=>$l)DB::table('customer_payment_posting_lines')->insert(['customer_payment_id'=>$id,'line_no'=>$i+1,'account_code'=>$l['account_code'],'account_name'=>$l['account_name'],'party_type'=>$l['party_type']??null,'party_id'=>$l['party_id']??null,'debit'=>$l['debit'],'credit'=>$l['credit'],'base_debit'=>$l['debit']*$l['exchange_rate'],'base_credit'=>$l['credit']*$l['exchange_rate'],'currency_code'=>$l['currency_code'],'exchange_rate'=>$l['exchange_rate'],'entry_type'=>$entry,'narration'=>$l['narration']??null,'created_at'=>now(),'updated_at'=>now()]);}
    private function document(object $r): object {return (object)['voucher_no'=>$r->document_no,'voucher_date'=>$r->opening_date,'voucher_type'=>'party_opening_balance','branch_id'=>$r->branch_id,'company_id'=>$r->company_id,'party_name'=>$r->party_name,'currency_code'=>$r->currency_code,'exchange_rate'=>$r->exchange_rate,'narration'=>$r->narration,'created_by'=>$r->created_by,'approved_by'=>$r->approved_by,'posted_by'=>$r->posted_by,'created_at'=>$r->created_at];}
    private function paymentDocument(object $r): object {return (object)['voucher_no'=>$r->document_no,'voucher_date'=>$r->payment_date,'voucher_type'=>'customer_payment','branch_id'=>$r->branch_id,'company_id'=>$r->company_id,'party_name'=>$r->party_name,'currency_code'=>$r->currency_code,'exchange_rate'=>$r->exchange_rate,'cash_bank_account_code'=>$r->cash_bank_account_code,'cash_bank_account_name'=>$r->cash_bank_account_name,'narration'=>$r->narration,'created_by'=>$r->created_by,'approved_by'=>$r->approved_by,'posted_by'=>$r->posted_by,'created_at'=>$r->created_at];}
}
