<?php

namespace App\Services\Accounting;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use RuntimeException;

/** One source-aware availability authority for posted advances. */
final class PartyAdvanceBalanceService
{
    public function __construct(private readonly AccountingPartyRoleResolver $roles, private readonly ChartOfAccountsWorkspaceService $chart) {}
    public function advanceSourceSnapshot(string $type,int $id): array { $type=$this->normaliseType($type);$row=$type==='cash_voucher'?DB::table('cash_vouchers')->where('id',$id)->lockForUpdate()->first():DB::table('party_opening_balances')->where('id',$id)->lockForUpdate()->first();if(!$row)throw new RuntimeException('Advance source was not found.');$partyType=$type==='cash_voucher'?(string)$row->party_type:((string)$row->party_type==='vendor'?'supplier':'customer');$domain=$type==='cash_voucher'?(string)$row->voucher_type:(string)$row->balance_type;$eligible=$partyType==='customer'?in_array($domain,['receipt','customer_advance'],true):in_array($domain,['payment','supplier_advance','vendor_advance'],true);if(!$eligible||(string)$row->status!=='posted')throw new RuntimeException('Source is not a Posted party advance.');$partyId=(int)$row->party_id;if($partyId<=0)throw new RuntimeException('Advance source has no canonical party.');$this->roles->assertRole($partyId,$partyType);$available=$this->availableAdvance($type,$id,$row);$original=$type==='cash_voucher'?(float)($row->unallocated_amount??0):(float)$row->amount;$adjusted=max(0,round($original-$available-($type==='cash_voucher'&&((string)$row->party_type)!=='customer'?0:0),2));$returned=Schema::hasTable('customer_advance_return_allocations')?(float)DB::table('customer_advance_return_allocations as a')->join('customer_advance_returns as r','r.id','=','a.customer_advance_return_id')->where('r.status','posted')->where('a.advance_source_type',$type)->where('a.advance_source_id',$id)->sum('a.amount'):0.0;return ['advance_source_type'=>$type,'advance_source_id'=>$id,'source_number'=>(string)($row->voucher_no??$row->opening_no??''),'party_type'=>$partyType,'party_id'=>$partyId,'party_name'=>(string)($row->party_name??''),'currency_code'=>(string)($row->currency_code?:'PKR'),'original_amount'=>$original,'adjusted_amount'=>round(max(0,$original-$available-$returned),2),'returned_amount'=>round($returned,2),'available_amount'=>$available,'source_date'=>(string)($row->voucher_date??$row->opening_date??''),'booking_id'=>$row->booking_id??null]; }
    public function availableAdvance(string $type,int $id,?object $row=null): float { $type=$this->normaliseType($type);$row??=$type==='cash_voucher'?DB::table('cash_vouchers')->where('id',$id)->first():DB::table('party_opening_balances')->where('id',$id)->first();if(!$row||(string)$row->status!=='posted')return 0.0;$base=$type==='cash_voucher'?(float)($row->unallocated_amount??0):(float)$row->amount;$adjusted=Schema::hasTable('advance_adjustments')?(float)DB::table('advance_adjustments')->where('status','posted')->where(function($q)use($type,$id){$q->where(function($x)use($type,$id){$x->where('advance_source_type',$type)->where('advance_source_id',$id);})->orWhere(function($x)use($type,$id){if($type==='cash_voucher')$x->where('advance_voucher_id',$id);else $x->whereRaw('1=0');});})->sum('amount'):0.0;$returned=($type==='cash_voucher'&&((string)$row->party_type)!=='customer')?0.0:(Schema::hasTable('customer_advance_return_allocations')&&Schema::hasTable('customer_advance_returns')?(float)DB::table('customer_advance_return_allocations as a')->join('customer_advance_returns as r','r.id','=','a.customer_advance_return_id')->where('r.status','posted')->where('a.advance_source_type',$type)->where('a.advance_source_id',$id)->sum('a.amount'):0.0);return max(0,round($base-$adjusted-$returned,2)); }
    public function advanceOptions(string $partyType,?int $partyId=null): array { $out=[];if(Schema::hasTable('cash_vouchers'))foreach(DB::table('cash_vouchers')->where('status','posted')->where('party_type',$partyType)->where('unallocated_amount','>',0)->when($partyId,fn($q)=>$q->where('party_id',$partyId))->orderByDesc('id')->limit(500)->get() as $row){try{$s=$this->advanceSourceSnapshot('cash_voucher',(int)$row->id);if($s['available_amount']>0)$out[]=$s;}catch(\Throwable){}}if(Schema::hasTable('party_opening_balances'))foreach(DB::table('party_opening_balances')->where('status','posted')->where('party_type',$partyType==='supplier'?'vendor':'customer')->whereIn('balance_type',$partyType==='supplier'?['vendor_advance']:['customer_advance'])->when($partyId,fn($q)=>$q->where('party_id',$partyId))->orderByDesc('id')->limit(500)->get() as $row){try{$s=$this->advanceSourceSnapshot('party_opening_balance',(int)$row->id);if($s['available_amount']>0)$out[]=$s;}catch(\Throwable){}}return $out; }
    public function lockAdvanceSource(string $type,int $id): object { $table=$this->normaliseType($type)==='cash_voucher'?'cash_vouchers':'party_opening_balances';$row=DB::table($table)->where('id',$id)->lockForUpdate()->first();if(!$row)throw new RuntimeException('Advance source was not found.');return $row; }
    public function controlledAccount(string $key): array { $s=$this->chart->schema();if(!$s['control_type'])throw new RuntimeException('Required accounting control account is not configured.');$r=DB::table($s['table'])->whereRaw('UPPER('.$s['control_type'].')=?',[$key])->first();if(!$r||!$this->isPosting($r,$s)||($s['control_flag']&&property_exists($r,$s['control_flag'])&&!((bool)$r->{$s['control_flag']})))throw new RuntimeException('Required accounting control account is not configured.');return ['code'=>(string)$r->{$s['code']},'name'=>(string)$r->{$s['name']}]; }
    private function normaliseType(string $type): string { return match($type){ 'cash_voucher','receipt','payment','customer_advance','supplier_advance'=>'cash_voucher','party_opening_balance','opening_balance'=>'party_opening_balance',default=>throw new RuntimeException('Unsupported advance source type.')}; }
    private function isPosting(object $r,array $s): bool { $active=$s['active']??null;if($active&&isset($r->{$active})&&!((bool)$r->{$active}))return false;$status=$s['status']??null;if($status&&isset($r->{$status})&&!in_array(strtolower((string)$r->{$status}),['active','enabled','open'],true))return false;$posting=$s['posting']??null;if($posting&&isset($r->{$posting})&&!((bool)$r->{$posting}))return false;$control=$s['control_flag']??null;if($control&&isset($r->{$control})&&!((bool)$r->{$control}))return false;$type=$s['type']??null;if($type&&isset($r->{$type})&&strtolower((string)$r->{$type})==='header')return false;return true; }
}
