<?php

namespace App\Services\Accounting;

use Illuminate\Support\Facades\DB;
use RuntimeException;

/** Controlled, idempotent customer advance return lifecycle. */
final class PartyAdvanceReturnService
{
    public function __construct(private readonly AccountingPartyRoleResolver $roles, private readonly PartyAdvanceBalanceService $advances, private readonly CashVoucherService $cash, private readonly CashVoucherNativeJournalBridge $native) {}

    public function sourceOptions(?int $partyId = null): array { return $this->advances->advanceOptions('customer', $partyId); }

    public function create(array $data, mixed $user): int
    {
        $party=$this->roles->assertRole((int)$data['customer_party_id'],'customer'); $alloc=(array)($data['allocations']??[]); $amount=round((float)$data['amount'],2); $currency=strtoupper($data['currency_code']??'PKR'); if($amount<=0||!$alloc)throw new RuntimeException('A positive return amount and allocation are required.'); $sum=0;
        $seen=[];foreach($alloc as $a){$key=$a['advance_source_type'].':'.(int)$a['advance_source_id'];if(isset($seen[$key]))throw new RuntimeException('A source may appear only once per return.');$seen[$key]=(float)$a['amount'];$s=$this->advances->advanceSourceSnapshot($a['advance_source_type'],(int)$a['advance_source_id']);if($s['party_type']!=='customer'||$s['party_id']!==(int)$party['party_id']||strtoupper($s['currency_code'])!==$currency||(float)$a['amount']>(float)$s['available_amount']+0.005)throw new RuntimeException('Advance source is invalid, mismatched, or exhausted.');$sum+=(float)$a['amount'];}if(abs($sum-$amount)>0.005)throw new RuntimeException('Return must be fully allocated.');
        $bank=$this->cash->cashBankAccount((string)$data['cash_bank_account_code']);$now=now();$id=DB::table('customer_advance_returns')->insertGetId(['return_no'=>$this->nextNumber(),'customer_party_id'=>$party['party_id'],'customer_name'=>$party['party_name'],'return_date'=>$data['return_date'],'value_date'=>$data['value_date']??null,'currency_code'=>$currency,'exchange_rate'=>(float)($data['exchange_rate']??1),'amount'=>$amount,'payment_method'=>$data['payment_method']??null,'cash_bank_account_code'=>$bank['code'],'cash_bank_account_name'=>$bank['name'],'bank_name'=>$data['bank_name']??null,'transaction_reference'=>$data['transaction_reference']??null,'instrument_no'=>$data['instrument_no']??null,'payment_proof_path'=>$data['payment_proof_path']??null,'payment_proof_original_name'=>$data['payment_proof_original_name']??null,'narration'=>$data['narration']??null,'branch_id'=>(int)$data['branch_id'],'company_id'=>$data['company_id']??null,'status'=>'draft','created_by'=>$user?->id,'created_at'=>$now,'updated_at'=>$now]);foreach($alloc as $i=>$a){$s=$this->advances->advanceSourceSnapshot($a['advance_source_type'],(int)$a['advance_source_id']);DB::table('customer_advance_return_allocations')->insert(['customer_advance_return_id'=>$id,'advance_source_type'=>$s['advance_source_type'],'advance_source_id'=>$s['advance_source_id'],'source_number'=>$s['source_number'],'source_date'=>$s['source_date']?:null,'booking_id'=>$s['booking_id'],'available_before_snapshot'=>$s['available_amount'],'amount'=>(float)$a['amount'],'line_no'=>$i+1,'currency_code'=>$currency,'customer_party_id'=>$party['party_id'],'created_at'=>$now,'updated_at'=>$now]);}DB::table('customer_advance_return_activities')->insert(['customer_advance_return_id'=>$id,'action'=>'create','to_status'=>'draft','user_id'=>$user?->id,'remarks'=>'Customer advance return draft created.','created_at'=>$now,'updated_at'=>$now]);return $id;
    }

    public function transition(int $id,string $action,mixed $user): void
    { DB::transaction(function()use($id,$action,$user):void{$r=DB::table('customer_advance_returns')->where('id',$id)->lockForUpdate()->first();if(!$r)throw new RuntimeException('Customer advance return not found.');$next=['submit'=>'pending_approval','approve'=>'approved','post'=>'posted'][$action]??null;if(!$next||$r->status!==['submit'=>'draft','approve'=>'pending_approval','post'=>'approved'][$action])throw new RuntimeException('Invalid customer advance return transition.');if($action==='post'){$alloc=DB::table('customer_advance_return_allocations')->where('customer_advance_return_id',$id)->lockForUpdate()->get();foreach($alloc as $a){$this->advances->lockAdvanceSource($a->advance_source_type,(int)$a->advance_source_id);$s=$this->advances->advanceSourceSnapshot($a->advance_source_type,(int)$a->advance_source_id);if((float)$a->amount>(float)$s['available_amount']+0.005)throw new RuntimeException('Advance availability changed.');}$lines=$this->postingLines($r,$id);$jid=$this->native->postControlledDocument($this->document($r),DB::table('customer_advance_return_posting_lines')->where('customer_advance_return_id',$id)->where('entry_type','original')->get(),'customer_advance_return',$id,$r->return_no,'Customer advance return',$user,null,'customer_advance_return','customer_advance_return_posting_line');DB::table('customer_advance_returns')->where('id',$id)->update(['posting_journal_id'=>$jid]);}$now=now();DB::table('customer_advance_returns')->where('id',$id)->update(['status'=>$next,$action==='approve'?'approved_by':'posted_by'=>$user?->id,$action==='approve'?'approved_at':'posted_at'=>$now,'updated_at'=>$now]);DB::table('customer_advance_return_activities')->insert(['customer_advance_return_id'=>$id,'action'=>$action,'from_status'=>$r->status,'to_status'=>$next,'user_id'=>$user?->id,'remarks'=>'Workflow transition.','created_at'=>$now,'updated_at'=>$now]);}); }

    public function reverse(int $id,string $reason,mixed $user): void
    { DB::transaction(function()use($id,$reason,$user):void{$r=DB::table('customer_advance_returns')->where('id',$id)->lockForUpdate()->first();if(!$r||$r->status!=='posted')throw new RuntimeException('Only posted customer advance returns can be reversed.');$rows=DB::table('customer_advance_return_posting_lines')->where('customer_advance_return_id',$id)->where('entry_type','original')->get();foreach(collect($rows)->map(function($x){$a=(array)$x;$d=$a['debit'];$a['debit']=$a['credit'];$a['credit']=$d;return $a;}) as $i=>$l)DB::table('customer_advance_return_posting_lines')->insert(['customer_advance_return_id'=>$id,'line_no'=>$i+1,'account_code'=>$l['account_code'],'account_name'=>$l['account_name'],'party_type'=>$l['party_type']??null,'party_id'=>$l['party_id']??null,'debit'=>$l['debit'],'credit'=>$l['credit'],'base_debit'=>$l['debit'],'base_credit'=>$l['credit'],'currency_code'=>$l['currency_code'],'exchange_rate'=>$l['exchange_rate'],'entry_type'=>'reversal','narration'=>$reason,'created_at'=>now(),'updated_at'=>now()]);$this->native->postControlledDocument($this->document($r),DB::table('customer_advance_return_posting_lines')->where('customer_advance_return_id',$id)->where('entry_type','reversal')->get(),'customer_advance_return_reversal',$id,'CARREV-'.$id,'Customer advance return reversal',$user,$r->posting_journal_id,'customer_advance_return','customer_advance_return_posting_line');DB::table('customer_advance_returns')->where('id',$id)->update(['status'=>'reversed','reversal_reference'=>'CARREV-'.$id,'reversed_by'=>$user?->id,'reversed_at'=>now(),'reversal_reason'=>$reason,'updated_at'=>now()]);}); }

    private function postingLines(object $r,int $id): array { $clear=$this->advanceAccount('CUSTOMER_ADVANCE'); $lines=[['account_code'=>$clear['code'],'account_name'=>$clear['name'],'party_type'=>'customer','party_id'=>$r->customer_party_id,'debit'=>$r->amount,'credit'=>0],['account_code'=>$r->cash_bank_account_code,'account_name'=>$r->cash_bank_account_name,'party_type'=>null,'party_id'=>null,'debit'=>0,'credit'=>$r->amount]];foreach($lines as $i=>$l)DB::table('customer_advance_return_posting_lines')->insert(['customer_advance_return_id'=>$id,'line_no'=>$i+1,'account_code'=>$l['account_code'],'account_name'=>$l['account_name'],'party_type'=>$l['party_type'],'party_id'=>$l['party_id'],'debit'=>$l['debit'],'credit'=>$l['credit'],'base_debit'=>$l['debit']*$r->exchange_rate,'base_credit'=>$l['credit']*$r->exchange_rate,'currency_code'=>$r->currency_code,'exchange_rate'=>$r->exchange_rate,'entry_type'=>'original','narration'=>$r->narration,'created_at'=>now(),'updated_at'=>now()]);return $lines; }
    private function advanceAccount(string $key): array { return $this->advances->controlledAccount($key); }
    private function nextNumber(): string { $stem='CAR-'.now()->format('Y').'-';$last=DB::table('customer_advance_returns')->where('return_no','like',$stem.'%')->lockForUpdate()->orderByDesc('return_no')->value('return_no');$n=$last&&preg_match('/(\d+)$/',(string)$last,$m)?(int)$m[1]+1:1000;return $stem.$n; }
    private function document(object $r): object { return (object)['voucher_no'=>$r->return_no,'voucher_date'=>$r->return_date,'voucher_type'=>'customer_advance_return','branch_id'=>$r->branch_id,'company_id'=>$r->company_id,'party_name'=>$r->customer_name,'currency_code'=>$r->currency_code,'exchange_rate'=>$r->exchange_rate,'narration'=>$r->narration,'created_by'=>$r->created_by,'approved_by'=>$r->approved_by,'posted_by'=>$r->posted_by,'created_at'=>$r->created_at]; }
}
