@extends($layoutMeta['layout'])
@section($layoutMeta['title_section'] ?? 'title',$row ? 'Edit Supplier Costing' : 'New Supplier Costing')
@section($layoutMeta['content_section'] ?? 'content')
<style>.sc-wrap{max-width:1500px;margin:0 auto}.sc-card{background:#fff;border:1px solid #dfe6ef;border-radius:12px;padding:18px;margin-bottom:14px}.sc-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.sc-field label{display:block;font-size:12px;font-weight:700;margin-bottom:6px}.sc-field input,.sc-field select,.sc-field textarea{width:100%;border:1px solid #d2dbe6;border-radius:7px;padding:9px 10px}.sc-table{width:100%;border-collapse:collapse}.sc-table th,.sc-table td{padding:8px;border:1px solid #e4e9ef}.sc-table input,.sc-table select{width:100%;border:0;outline:0}.sc-actions{display:flex;justify-content:flex-end;gap:10px}.sc-btn{padding:10px 16px;border:1px solid #cad5e1;border-radius:8px;background:#fff}.sc-primary{background:#0d5bd7;color:#fff;border-color:#0d5bd7}@media(max-width:900px){.sc-grid{grid-template-columns:1fr 1fr}}@media(max-width:600px){.sc-grid{grid-template-columns:1fr}}</style>
<div class="sc-wrap"><div style="margin-bottom:16px"><div style="font-size:12px;font-weight:800;color:#0d5bd7">SUPPLIER COSTING · ERP-11.2</div><h2 style="margin:4px 0">{{ $row ? 'Edit '.$row->costing_no : 'New Supplier Cost' }}</h2></div>
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<form method="post" action="{{ $row ? route('purchase.supplier-costing.update',$row->id) : route('purchase.supplier-costing.store') }}">@csrf @if($row) @method('PUT') @endif
<div class="sc-card"><h4>Document Information</h4><div class="sc-grid">
<div class="sc-field"><label>Booking Reference</label><select name="booking_id"><option value="">Select booking</option>@foreach($bookings as $b)<option value="{{ $b['id'] }}" @selected((string)old('booking_id',$row->booking_id ?? '')===(string)$b['id'])>{{ $b['reference'] }}</option>@endforeach</select></div>
<div class="sc-field"><label>Supplier</label><select name="supplier_id"><option value="">Select supplier</option>@foreach($suppliers as $s)<option value="{{ $s['id'] }}" @selected((string)old('supplier_id',$row->supplier_id ?? '')===(string)$s['id'])>{{ $s['name'] }}</option>@endforeach</select><input type="hidden" name="supplier_name" value="{{ old('supplier_name',$row->supplier_name ?? '') }}"></div>
<div class="sc-field"><label>Service Type *</label><select name="service_type">@foreach(['Air Ticket','Hotel','Visa','Transport','Group Umrah','Other Service'] as $s)<option @selected(old('service_type',$row->service_type ?? 'Air Ticket')===$s)>{{ $s }}</option>@endforeach</select></div>
<div class="sc-field"><label>Cost Date *</label><input type="date" name="cost_date" value="{{ old('cost_date',$row->cost_date ?? now()->toDateString()) }}" required></div>
<div class="sc-field"><label>Supplier Invoice No.</label><input name="supplier_invoice_no" value="{{ old('supplier_invoice_no',$row->supplier_invoice_no ?? '') }}"></div>
<div class="sc-field"><label>Supplier Reference</label><input name="supplier_reference" value="{{ old('supplier_reference',$row->supplier_reference ?? '') }}"></div>
<div class="sc-field"><label>Currency *</label><input name="currency_code" value="{{ old('currency_code',$row->currency_code ?? 'PKR') }}" required></div>
<div class="sc-field"><label>Exchange Rate *</label><input type="number" step="0.00000001" min="0.00000001" name="exchange_rate" value="{{ old('exchange_rate',$row->exchange_rate ?? '1.00000000') }}" required></div>
<div class="sc-field"><label>Payment Terms</label><input name="payment_terms" value="{{ old('payment_terms',$row->payment_terms ?? '30 Days') }}"></div>
<div class="sc-field"><label>Due Date</label><input type="date" name="due_date" value="{{ old('due_date',$row->due_date ?? '') }}"></div>
<div class="sc-field" style="grid-column:span 2"><label>Remarks</label><input name="remarks" value="{{ old('remarks',$row->remarks ?? '') }}"></div>
</div></div>
<div class="sc-card"><div style="display:flex;justify-content:space-between"><h4>Cost Details</h4><button type="button" class="sc-btn" id="addLine">+ Add Line</button></div><div style="overflow:auto"><table class="sc-table"><thead><tr><th>Service</th><th>Description</th><th>Passenger / Ref</th><th>Supplier Service Ref</th><th>Base Cost</th><th>Tax</th><th>Other Charges</th><th>Total</th><th></th></tr></thead><tbody id="linesBody"></tbody></table></div><div style="text-align:right;font-weight:800;margin-top:12px">Total Supplier Cost: <span id="grandTotal">0.00</span></div></div>
<div class="sc-actions"><a class="sc-btn" href="{{ route('purchase.supplier-costing.index') }}">Cancel</a><button class="sc-btn sc-primary">Save Draft</button></div></form></div>
<script>
(()=>{const body=document.getElementById('linesBody');let seed=@json(($lines ?? collect())->map(fn($l)=>(array)$l)->values());if(!seed.length)seed=[{service_type:'Air Ticket',description:'',passenger_name:'',supplier_service_ref:'',base_cost:0,tax_amount:0,other_charges:0}];
function esc(v){return String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}function row(v={}){let i=body.children.length,tr=document.createElement('tr');tr.innerHTML=`<td><select name="lines[${i}][service_type]">${['Air Ticket','Hotel','Visa','Transport','Group Umrah','Other Service'].map(x=>`<option ${x===(v.service_type||'Air Ticket')?'selected':''}>${x}</option>`).join('')}</select></td><td><input required name="lines[${i}][description]" value="${esc(v.description)}"></td><td><input name="lines[${i}][passenger_name]" value="${esc(v.passenger_name)}"></td><td><input name="lines[${i}][supplier_service_ref]" value="${esc(v.supplier_service_ref)}"></td><td><input class="money" type="number" min="0" step="0.01" required name="lines[${i}][base_cost]" value="${Number(v.base_cost||0).toFixed(2)}"></td><td><input class="money" type="number" min="0" step="0.01" name="lines[${i}][tax_amount]" value="${Number(v.tax_amount||0).toFixed(2)}"></td><td><input class="money" type="number" min="0" step="0.01" name="lines[${i}][other_charges]" value="${Number(v.other_charges||0).toFixed(2)}"></td><td class="lineTotal">0.00</td><td><button type="button" class="rm">×</button></td>`;body.appendChild(tr);calc();}
function calc(){let g=0;[...body.children].forEach(tr=>{let n=[...tr.querySelectorAll('.money')].reduce((a,e)=>a+Number(e.value||0),0);tr.querySelector('.lineTotal').textContent=n.toFixed(2);g+=n});document.getElementById('grandTotal').textContent=g.toFixed(2)}
seed.forEach(row);document.getElementById('addLine').onclick=()=>row();body.addEventListener('input',calc);body.addEventListener('click',e=>{if(e.target.classList.contains('rm')&&body.children.length>1){e.target.closest('tr').remove();[...body.children].forEach((tr,i)=>tr.querySelectorAll('[name]').forEach(el=>el.name=el.name.replace(/lines\[\d+\]/,`lines[${i}]`)));calc()}})})();
</script>
@endsection
