@extends($layoutMeta['layout'])
@section($layoutMeta['title_section'] ?? 'title',$row ? 'Edit Supplier Costing' : 'New Supplier Costing')
@section($layoutMeta['content_section'] ?? 'content')
<style>
.scb{max-width:1500px;margin:0 auto;color:#17243a}.scb *{box-sizing:border-box}.scb-head{display:flex;justify-content:space-between;gap:15px;align-items:flex-start;margin-bottom:15px}.scb-kicker{font-size:11px;font-weight:800;color:#0d5bd7;text-transform:uppercase}.scb h2{margin:3px 0}.scb-card{background:#fff;border:1px solid #dfe6ef;border-radius:12px;margin-bottom:14px;overflow:hidden}.scb-card-head{padding:13px 15px;border-bottom:1px solid #e8edf3;display:flex;justify-content:space-between;gap:12px}.scb-body{padding:15px}.scb-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:13px}.scb-field label{display:block;font-size:11px;font-weight:800;margin-bottom:5px}.scb-field input,.scb-field select{width:100%;border:1px solid #d2dbe6;border-radius:7px;padding:9px 10px;background:#fff}.scb-field input[readonly]{background:#f3f6fa}.scb-table-wrap{overflow:auto}.scb-table{width:100%;border-collapse:collapse;min-width:850px}.scb-table th,.scb-table td{padding:10px;border-bottom:1px solid #edf1f5;text-align:left;font-size:12px}.scb-table th{background:#f8fafc;color:#53647a;font-size:10px;text-transform:uppercase}.scb-table input{width:100%;border:1px solid #d8e0ea;border-radius:6px;padding:7px}.scb-num{text-align:right!important}.scb-status{display:inline-block;padding:4px 7px;border-radius:999px;background:#edf3fb}.scb-status.available{background:#e7f8ef;color:#087443}.scb-status.posted,.scb-status.already_costed{background:#fff0df;color:#8a5100}.scb-note{padding:10px 12px;border:1px solid #d9e5f4;background:#f6f9fe;border-radius:8px;color:#52677e;font-size:12px}.scb-actions{display:flex;justify-content:flex-end;gap:9px}.scb-btn{display:inline-block;padding:10px 15px;border:1px solid #cad5e1;border-radius:8px;background:#fff;text-decoration:none}.scb-primary{background:#0d5bd7;color:#fff;border-color:#0d5bd7}.scb-primary:disabled{opacity:.5}.scb-total{text-align:right;font-weight:800;padding-top:12px}@media(max-width:950px){.scb-grid{grid-template-columns:1fr 1fr}}@media(max-width:620px){.scb-head{display:block}.scb-grid{grid-template-columns:1fr}.scb-actions{display:grid;grid-template-columns:1fr 1fr}.scb-btn{text-align:center}}
</style>
@php
  $oldLines=collect(old('lines',[]))->keyBy('source_key');
  $bookingReference=collect($bookings)->firstWhere('id',$selectedBookingId)['reference'] ?? null;
@endphp
<div class="scb" data-et-supplier-costing-form="{{ config('et_erp_release.release', 'ERP-11.3') }}">
  <div class="scb-head"><div><div class="scb-kicker">Supplier Costing</div><h2>{{ $row ? 'Edit '.$row->costing_no : 'New Supplier Cost' }}</h2><div>Supplier costs and payable posting.</div></div></div>
  @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
  @if($legacyMode)<div class="scb-note" style="margin-bottom:14px"><strong>Legacy Draft:</strong> this existing document has no deterministic booking-source links. It remains editable without guessed backfill; new documents use the booking-driven flow.</div>@endif

  <form method="post" action="{{ $row ? route('purchase.supplier-costing.update',$row->id) : route('purchase.supplier-costing.store') }}">@csrf @if($row)@method('PUT')@endif
    <section class="scb-card"><div class="scb-card-head"><strong>Document Information</strong><span>{{ $bookingReference ?: 'Select a booking first' }}</span></div><div class="scb-body"><div class="scb-grid">
      <div class="scb-field"><label>Booking Reference *</label><select name="booking_id" id="bookingSelect" required @disabled($legacyMode)><option value="">Select booking</option>@foreach($bookings as $booking)<option value="{{ $booking['id'] }}" @selected((int)$selectedBookingId===(int)$booking['id'])>{{ $booking['reference'] }}</option>@endforeach</select>@if($legacyMode)<input type="hidden" name="booking_id" value="{{ $row->booking_id }}">@endif</div>
      <div class="scb-field"><label>Supplier *</label><select name="supplier_id" id="supplierSelect" required @disabled($legacyMode)><option value="">{{ $selectedBookingId ? 'Select booking supplier' : 'Select booking first' }}</option>@foreach($suppliers as $supplier)<option value="{{ $supplier['id'] }}" @selected((int)$selectedSupplierId===(int)$supplier['id'])>{{ $supplier['name'] }}</option>@endforeach</select>@if($legacyMode)<input type="hidden" name="supplier_id" value="{{ $row->supplier_id }}"><input type="hidden" name="supplier_name" value="{{ $row->supplier_name }}">@endif</div>
      @if($legacyMode)<div class="scb-field"><label>Service Type *</label><select name="service_type">@foreach(['Air Ticket','Hotel','Visa','Transport','Group Umrah','Other Service'] as $service)<option @selected(old('service_type',$row->service_type)===$service)>{{ $service }}</option>@endforeach</select></div>@endif
      <div class="scb-field"><label>Cost Date *</label><input type="date" name="cost_date" value="{{ old('cost_date',$row->cost_date ?? now()->toDateString()) }}" required></div>
      <div class="scb-field"><label>Due Date</label><input type="date" name="due_date" value="{{ old('due_date',$row->due_date ?? '') }}"></div>
      <div class="scb-field"><label>Supplier Invoice No.</label><input name="supplier_invoice_no" value="{{ old('supplier_invoice_no',$row->supplier_invoice_no ?? '') }}"></div>
      <div class="scb-field"><label>Supplier Reference</label><input name="supplier_reference" value="{{ old('supplier_reference',$row->supplier_reference ?? '') }}"></div>
      <div class="scb-field"><label>Currency *</label><input name="currency_code" value="{{ old('currency_code',$row->currency_code ?? 'PKR') }}" required @readonly(!$legacyMode)></div>
      <div class="scb-field"><label>Exchange Rate *</label><input type="number" step="0.00000001" min="0.00000001" name="exchange_rate" value="{{ old('exchange_rate',$row->exchange_rate ?? '1.00000000') }}" required @readonly(!$legacyMode)></div>
      <div class="scb-field"><label>Payment Terms</label><input name="payment_terms" value="{{ old('payment_terms',$row->payment_terms ?? '30 Days') }}"></div>
      <div class="scb-field" style="grid-column:span 2"><label>Remarks</label><input name="remarks" value="{{ old('remarks',$row->remarks ?? '') }}"></div>
    </div></div></section>

    @unless($legacyMode)
      <section class="scb-card"><div class="scb-card-head"><strong>Booking Supplier Obligations</strong><span>Read-only booking authority</span></div><div class="scb-table-wrap"><table class="scb-table"><thead><tr><th>Supplier</th><th>Product</th><th>Source Reference</th><th>Detail</th><th class="scb-num">Source Cost</th><th>Status</th></tr></thead><tbody>
      @forelse($obligations as $obligation)<tr><td>{{ $obligation['supplier_name'] }}</td><td>{{ $obligation['product_type'] }}</td><td>{{ $obligation['source_reference'] }}</td><td>{{ $obligation['detail'] ?: '—' }}</td><td class="scb-num">PKR {{ number_format($obligation['source_cost'],2) }}</td><td><span class="scb-status {{ $obligation['status'] }}">{{ $obligation['status_label'] }}</span></td></tr>@empty<tr><td colspan="6" style="text-align:center;padding:24px">{{ $selectedBookingId ? 'No authoritative supplier obligations were resolved. Complete booking vendor and cost data first.' : 'Select a Booking Reference to load its supplier obligations.' }}</td></tr>@endforelse
      </tbody></table></div></section>

      <section class="scb-card"><div class="scb-card-head"><strong>Cost Details — Selected Supplier</strong><span>Booking Cost is locked; Tax and Other Charges remain Draft inputs.</span></div><div class="scb-table-wrap"><table class="scb-table"><thead><tr><th>Product / Service</th><th>Source Reference</th><th>Passenger / Detail</th><th class="scb-num">Booking Cost</th><th class="scb-num">Tax</th><th class="scb-num">Other Charges</th><th class="scb-num">Total</th></tr></thead><tbody id="bookingLines">
      @forelse($selectedObligations as $index=>$source)
        @php($saved=$oldLines->get($source['source_key'],$lineAdjustments[$source['source_key']] ?? []))
        <tr><td>{{ $source['product_type'] }}<input type="hidden" name="lines[{{ $index }}][source_key]" value="{{ $source['source_key'] }}"></td><td>{{ $source['source_reference'] }}</td><td>{{ $source['detail'] ?: '—' }}</td><td class="scb-num" data-base="{{ $source['source_cost'] }}">{{ number_format($source['source_cost'],2) }}</td><td><input class="line-extra" type="number" min="0" step="0.01" name="lines[{{ $index }}][tax_amount]" value="{{ number_format((float)($saved['tax_amount'] ?? 0),2,'.','') }}"></td><td><input class="line-extra" type="number" min="0" step="0.01" name="lines[{{ $index }}][other_charges]" value="{{ number_format((float)($saved['other_charges'] ?? 0),2,'.','') }}"></td><td class="scb-num line-total">{{ number_format($source['source_cost']+(float)($saved['tax_amount'] ?? 0)+(float)($saved['other_charges'] ?? 0),2) }}</td></tr>
      @empty<tr><td colspan="7" style="text-align:center;padding:24px">Select a supplier with Available obligations. Unrelated suppliers are intentionally excluded.</td></tr>@endforelse
      </tbody></table></div><div class="scb-body"><div class="scb-total">Total Supplier Cost: PKR <span id="grandTotal">0.00</span></div></div></section>
    @else
      <section class="scb-card"><div class="scb-card-head"><strong>Legacy Cost Details</strong><span>Existing document only</span></div><div class="scb-table-wrap"><table class="scb-table"><thead><tr><th>Service</th><th>Description</th><th>Passenger / Ref</th><th>Supplier Ref</th><th>Base Cost</th><th>Tax</th><th>Other</th></tr></thead><tbody>@foreach($lines as $index=>$line)<tr><td><input name="lines[{{ $index }}][service_type]" value="{{ $line->service_type }}"></td><td><input name="lines[{{ $index }}][description]" value="{{ $line->description }}"></td><td><input name="lines[{{ $index }}][passenger_name]" value="{{ $line->passenger_name }}"></td><td><input name="lines[{{ $index }}][supplier_service_ref]" value="{{ $line->supplier_service_ref }}"></td><td><input type="number" step="0.01" name="lines[{{ $index }}][base_cost]" value="{{ $line->base_cost }}"></td><td><input type="number" step="0.01" name="lines[{{ $index }}][tax_amount]" value="{{ $line->tax_amount }}"></td><td><input type="number" step="0.01" name="lines[{{ $index }}][other_charges]" value="{{ $line->other_charges }}"></td></tr>@endforeach</tbody></table></div></section>
    @endunless

    <div class="scb-actions"><a class="scb-btn" href="{{ route('purchase.supplier-costing.index') }}">Cancel</a><button class="scb-btn scb-primary" @disabled(!$legacyMode && count($selectedObligations)===0)>Save Draft</button></div>
  </form>
</div>
@unless($legacyMode)
<script>
(()=>{const booking=document.getElementById('bookingSelect'),supplier=document.getElementById('supplierSelect');function reload(){const url=new URL(window.location.href);url.searchParams.set('booking_id',booking.value||'');url.searchParams.delete('supplier_id');window.location.href=url.toString()}function choose(){const url=new URL(window.location.href);url.searchParams.set('booking_id',booking.value||'');url.searchParams.set('supplier_id',supplier.value||'');window.location.href=url.toString()}booking?.addEventListener('change',reload);supplier?.addEventListener('change',choose);const body=document.getElementById('bookingLines'),total=document.getElementById('grandTotal');function calc(){let grand=0;body?.querySelectorAll('tr').forEach(row=>{const base=Number(row.querySelector('[data-base]')?.dataset.base||0),extras=[...row.querySelectorAll('.line-extra')].reduce((sum,input)=>sum+Number(input.value||0),0),value=base+extras;const cell=row.querySelector('.line-total');if(cell)cell.textContent=value.toFixed(2);grand+=value});if(total)total.textContent=grand.toFixed(2)}body?.addEventListener('input',calc);calc()})();
</script>
@endunless
@endsection
