@extends($layoutMeta['layout'])
@section($layoutMeta['title_section'] ?? 'title','Supplier Costing')
@section($layoutMeta['content_section'] ?? 'content')
<style>.sc-wrap{max-width:1500px;margin:0 auto}.sc-head{display:flex;justify-content:space-between;gap:16px;align-items:center;margin-bottom:18px}.sc-card{background:#fff;border:1px solid #dfe6ef;border-radius:12px;overflow:hidden}.sc-table{width:100%;border-collapse:collapse}.sc-table th,.sc-table td{padding:12px 14px;border-bottom:1px solid #edf1f6;text-align:left}.sc-table th{background:#f8fafc;font-size:12px;color:#526174}.sc-btn{display:inline-block;padding:9px 14px;border-radius:8px;border:1px solid #cfd8e3;text-decoration:none}.sc-primary{background:#0d5bd7;color:#fff;border-color:#0d5bd7}.sc-badge{padding:4px 9px;border-radius:999px;background:#eef3f8;font-size:12px}.sc-tools{display:flex;gap:8px}.sc-tools input,.sc-tools select{border:1px solid #d4dce6;border-radius:8px;padding:9px 11px}</style>
<div class="sc-wrap">
<div class="sc-head"><div><div style="font-size:12px;font-weight:800;color:#0d5bd7">PURCHASE & COSTING · ERP-11.2</div><h2 style="margin:3px 0">Supplier Costing</h2><div class="text-muted">Booking-linked supplier costs and vendor payables</div></div><a class="sc-btn sc-primary" href="{{ route('purchase.supplier-costing.create') }}">+ New Supplier Cost</a></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<form class="sc-tools" method="get" style="margin-bottom:12px"><input name="q" value="{{ request('q') }}" placeholder="Costing no, supplier, invoice"><select name="status"><option value="">All statuses</option>@foreach(['draft'=>'Draft','pending_approval'=>'Pending Approval','approved'=>'Approved','posted'=>'Posted'] as $k=>$v)<option value="{{ $k }}" @selected(request('status')===$k)>{{ $v }}</option>@endforeach</select><button class="sc-btn">Filter</button></form>
<div class="sc-card"><table class="sc-table"><thead><tr><th>Costing No.</th><th>Date</th><th>Booking</th><th>Supplier</th><th>Service</th><th>Supplier Invoice</th><th>Total</th><th>Status</th><th></th></tr></thead><tbody>@forelse($rows as $r)<tr><td><strong>{{ $r->costing_no }}</strong></td><td>{{ \Carbon\Carbon::parse($r->cost_date)->format('d/m/Y') }}</td><td>{{ $r->booking_id ? 'BK #'.$r->booking_id : '—' }}</td><td>{{ $r->supplier_name ?: '—' }}</td><td>{{ $r->service_type }}</td><td>{{ $r->supplier_invoice_no ?: '—' }}</td><td>{{ $r->currency_code }} {{ number_format($r->total_cost,2) }}</td><td><span class="sc-badge">{{ ucwords(str_replace('_',' ',$r->status)) }}</span></td><td><a href="{{ route('purchase.supplier-costing.show',$r->id) }}">Open</a></td></tr>@empty<tr><td colspan="9" style="padding:30px;text-align:center;color:#6b7788">No supplier costing documents yet.</td></tr>@endforelse</tbody></table></div><div style="margin-top:14px">{{ $rows->links() }}</div></div>
@endsection
