@extends($layoutMeta['layout'])
@section($layoutMeta['title_section'] ?? 'title','Supplier Costing')
@section($layoutMeta['content_section'] ?? 'content')
<style>.sci{max-width:1500px;margin:0 auto}.sci-head{display:flex;justify-content:space-between;gap:16px;align-items:center;margin-bottom:18px}.sci-kicker{font-size:11px;font-weight:800;color:#0d5bd7;text-transform:uppercase}.sci-card{background:#fff;border:1px solid #dfe6ef;border-radius:12px;overflow:auto}.sci-table{width:100%;border-collapse:collapse;min-width:950px}.sci-table th,.sci-table td{padding:12px 14px;border-bottom:1px solid #edf1f6;text-align:left}.sci-table th{background:#f8fafc;font-size:11px;color:#526174}.sci-btn{display:inline-block;padding:9px 14px;border-radius:8px;border:1px solid #cfd8e3;text-decoration:none;background:#fff}.sci-primary{background:#0d5bd7;color:#fff;border-color:#0d5bd7}.sci-badge{padding:4px 9px;border-radius:999px;background:#eef3f8;font-size:12px}.sci-tools{display:flex;gap:8px;margin-bottom:12px}.sci-tools input,.sci-tools select{border:1px solid #d4dce6;border-radius:8px;padding:9px 11px}@media(max-width:650px){.sci-head{display:block}.sci-primary{margin-top:10px}.sci-tools{display:grid}}</style>
<div class="sci" data-et-supplier-costing-index="{{ config('et_erp_release.release', 'ERP-11.3') }}">
  <div class="sci-head"><div><div class="sci-kicker">Purchase & Costing · {{ config('et_erp_release.release', 'ERP-11.3') }}</div><h2 style="margin:3px 0">Supplier Costing</h2><div class="text-muted">Booking-driven vendor obligations and controlled payables</div></div><a class="sci-btn sci-primary" href="{{ route('purchase.supplier-costing.create') }}">+ New Supplier Cost</a></div>
  @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
  <form class="sci-tools" method="get"><input name="q" value="{{ request('q') }}" placeholder="Costing no, supplier, invoice"><select name="status"><option value="">All statuses</option>@foreach(['draft'=>'Draft','pending_approval'=>'Pending Approval','approved'=>'Approved','posted'=>'Posted'] as $key=>$label)<option value="{{ $key }}" @selected(request('status')===$key)>{{ $label }}</option>@endforeach</select><button class="sci-btn">Filter</button></form>
  <div class="sci-card"><table class="sci-table"><thead><tr><th>Costing No.</th><th>Date</th><th>Booking</th><th>Supplier</th><th>Products</th><th>Supplier Invoice</th><th>Total</th><th>Status</th><th></th></tr></thead><tbody>@forelse($rows as $row)<tr><td><strong>{{ $row->costing_no }}</strong></td><td>{{ \Carbon\Carbon::parse($row->cost_date)->format('d/m/Y') }}</td><td>{{ $row->booking_id ? 'Booking #'.$row->booking_id : 'Legacy / Manual' }}</td><td>{{ $row->supplier_name ?: '—' }}</td><td>{{ $row->service_type }}</td><td>{{ $row->supplier_invoice_no ?: '—' }}</td><td>{{ $row->currency_code }} {{ number_format($row->total_cost,2) }}</td><td><span class="sci-badge">{{ ucwords(str_replace('_',' ',$row->status)) }}</span></td><td><a href="{{ route('purchase.supplier-costing.show',$row->id) }}">Open</a></td></tr>@empty<tr><td colspan="9" style="padding:30px;text-align:center;color:#6b7788">No supplier costing documents yet.</td></tr>@endforelse</tbody></table></div><div style="margin-top:14px">{{ $rows->links() }}</div>
</div>
@endsection
