@extends($layoutMeta['layout'])
@section($layoutMeta['title_section'] ?? 'title','Supplier Costing '.$row->costing_no)
@section($layoutMeta['content_section'] ?? 'content')
<style>.sc-wrap{max-width:1500px;margin:0 auto}.sc-top{display:flex;justify-content:space-between;align-items:flex-start;gap:16px}.sc-actions{display:flex;gap:8px;flex-wrap:wrap}.sc-btn{padding:9px 14px;border:1px solid #ccd6e2;border-radius:8px;background:#fff;text-decoration:none}.sc-primary{background:#0d5bd7;color:#fff;border-color:#0d5bd7}.sc-card{background:#fff;border:1px solid #dfe6ef;border-radius:12px;padding:16px;margin-top:14px}.sc-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.sc-kpi{background:#fff;border:1px solid #dfe6ef;border-radius:12px;padding:15px}.sc-kpi small{font-weight:800;color:#68778a}.sc-kpi strong{display:block;font-size:22px;margin-top:7px}.sc-grid{display:grid;grid-template-columns:2fr 1fr;gap:14px}.sc-table{width:100%;border-collapse:collapse}.sc-table th,.sc-table td{padding:10px;border-bottom:1px solid #edf1f5;text-align:left}.sc-table th{font-size:12px;background:#f8fafc}.num{text-align:right!important}.badge{display:inline-block;padding:5px 9px;border-radius:999px;background:#edf3fb}.wf{display:flex;gap:4px;align-items:center;margin-top:10px}.wf span{padding:8px 10px;border-radius:7px;background:#f1f4f8;font-size:12px}.wf .on{background:#e7f0ff;color:#0d5bd7;font-weight:800}@media(max-width:1000px){.sc-kpis{grid-template-columns:1fr 1fr}.sc-grid{grid-template-columns:1fr}}</style>
<div class="sc-wrap"><div class="sc-top"><div><div style="font-size:12px;color:#0d5bd7;font-weight:800">SUPPLIER COSTING · ERP-11.2</div><h2 style="margin:4px 0">{{ $row->costing_no }}</h2><div>Booking {{ $row->booking_id ? '#'.$row->booking_id : '—' }} · {{ $row->supplier_name ?: 'Supplier not selected' }}</div></div><div class="sc-actions">@if($row->status==='draft')<a class="sc-btn" href="{{ route('purchase.supplier-costing.edit',$row->id) }}">Edit Draft</a><form method="post" action="{{ route('purchase.supplier-costing.workflow',[$row->id,'submit']) }}">@csrf<button class="sc-btn sc-primary">Submit for Approval</button></form>@elseif($row->status==='pending_approval' && $canApprove)<form method="post" action="{{ route('purchase.supplier-costing.workflow',[$row->id,'approve']) }}">@csrf<button class="sc-btn sc-primary">Approve</button></form>@elseif($row->status==='approved' && $canApprove)<form method="post" action="{{ route('purchase.supplier-costing.workflow',[$row->id,'post']) }}">@csrf<button class="sc-btn sc-primary">Post to Payables</button></form>@endif</div></div>
@if(session('success'))<div class="alert alert-success" style="margin-top:12px">{{ session('success') }}</div>@endif @if($errors->any())<div class="alert alert-danger" style="margin-top:12px">{{ $errors->first() }}</div>@endif
<div class="sc-kpis" style="margin-top:14px"><div class="sc-kpi"><small>TOTAL SUPPLIER COST</small><strong>{{ $row->currency_code }} {{ number_format($row->total_cost,2) }}</strong></div><div class="sc-kpi"><small>SUPPLIER</small><strong style="font-size:17px">{{ $row->supplier_name ?: '—' }}</strong></div><div class="sc-kpi"><small>SERVICE</small><strong style="font-size:17px">{{ $row->service_type }}</strong></div><div class="sc-kpi"><small>STATUS</small><strong style="font-size:17px">{{ ucwords(str_replace('_',' ',$row->status)) }}</strong></div></div>
<div class="sc-grid"><div><div class="sc-card"><h4>Cost Details</h4><table class="sc-table"><thead><tr><th>#</th><th>Service</th><th>Description</th><th>Passenger / Ref</th><th>Supplier Ref</th><th class="num">Base</th><th class="num">Tax</th><th class="num">Other</th><th class="num">Total</th></tr></thead><tbody>@foreach($lines as $l)<tr><td>{{ $l->line_no }}</td><td>{{ $l->service_type }}</td><td>{{ $l->description }}</td><td>{{ $l->passenger_name ?: '—' }}</td><td>{{ $l->supplier_service_ref ?: '—' }}</td><td class="num">{{ number_format($l->base_cost,2) }}</td><td class="num">{{ number_format($l->tax_amount,2) }}</td><td class="num">{{ number_format($l->other_charges,2) }}</td><td class="num"><strong>{{ number_format($l->total_cost,2) }}</strong></td></tr>@endforeach</tbody></table></div>
<div class="sc-card"><h4>Accounting Preview / Posting</h4><p style="color:#66758a">On Post: debit supplier cost / cost of sales and credit supplier accounts payable. Posted documents are immutable.</p><table class="sc-table"><thead><tr><th>Account</th><th>Account Name</th><th class="num">Debit</th><th class="num">Credit</th></tr></thead><tbody>@if($postings->isNotEmpty())@foreach($postings as $p)<tr><td>{{ $p->account_code }}</td><td>{{ $p->account_name }}</td><td class="num">{{ number_format($p->debit,2) }}</td><td class="num">{{ number_format($p->credit,2) }}</td></tr>@endforeach @else<tr><td>5-1000-001</td><td>Cost of Sales / Supplier Cost</td><td class="num">{{ number_format($row->total_cost,2) }}</td><td class="num">—</td></tr><tr><td>2-2000-001</td><td>Accounts Payable - Suppliers</td><td class="num">—</td><td class="num">{{ number_format($row->total_cost,2) }}</td></tr>@endif</tbody><tfoot><tr><th colspan="2">Total</th><th class="num">{{ number_format($row->total_cost,2) }}</th><th class="num">{{ number_format($row->total_cost,2) }}</th></tr></tfoot></table>@if($row->posting_reference)<div style="margin-top:9px"><strong>Posting Ref:</strong> {{ $row->posting_reference }}</div>@endif</div></div>
<div><div class="sc-card"><h4>Document Information</h4><div><strong>Cost Date:</strong> {{ $row->cost_date }}</div><div><strong>Due Date:</strong> {{ $row->due_date ?: '—' }}</div><div><strong>Supplier Invoice:</strong> {{ $row->supplier_invoice_no ?: '—' }}</div><div><strong>Supplier Ref:</strong> {{ $row->supplier_reference ?: '—' }}</div><div><strong>Exchange Rate:</strong> {{ $row->exchange_rate }}</div><div><strong>Payment Terms:</strong> {{ $row->payment_terms ?: '—' }}</div></div>
<div class="sc-card"><h4>Status & Workflow</h4><div class="wf">@foreach(['draft'=>'Draft','pending_approval'=>'Pending Approval','approved'=>'Approved','posted'=>'Posted'] as $k=>$v)<span class="{{ $row->status===$k ? 'on':'' }}">{{ $v }}</span>@endforeach</div></div>
<div class="sc-card"><h4>Activity</h4>@forelse($activities as $a)<div style="padding:9px 0;border-bottom:1px solid #edf1f5"><strong>{{ strtoupper($a->action) }}</strong><div style="font-size:12px;color:#69788b">{{ $a->user_name ?: 'System' }} · {{ $a->created_at }}</div></div>@empty<div>No activity yet.</div>@endforelse</div></div></div></div>
@endsection
