@extends($layoutMeta['layout'])
@section($layoutMeta['title_section'] ?? 'title','Balance Sheet')
@section($layoutMeta['content_section'] ?? 'content')
@php($money=fn($value)=>'PKR '.number_format((float)$value,2))
<style>
.mr{max-width:1150px;margin:0 auto;color:#17243a}.mr *{box-sizing:border-box}.mr-kicker{font-size:10px;font-weight:850;color:#1769d2;text-transform:uppercase}.mr h2{margin:3px 0}.mr-sub{font-size:11px;color:#6d7c91}.mr-nav{display:flex;gap:5px;flex-wrap:wrap;margin:14px 0}.mr-nav a{padding:8px 11px;border:1px solid #d9e2ed;border-radius:7px;background:#fff;color:#34455c;text-decoration:none;font-size:10px;font-weight:800}.mr-nav a.active{background:#1769d2;color:#fff}.mr-filter{display:flex;gap:10px;align-items:end;flex-wrap:wrap;padding:12px;border:1px solid #dfe7f1;border-radius:10px;background:#fff}.mr-field label{display:block;margin-bottom:4px;font-size:9px;font-weight:850;text-transform:uppercase}.mr-field input,.mr-field select{padding:8px;border:1px solid #ced9e6;border-radius:6px}.mr-btn{padding:9px 13px;border:0;border-radius:6px;background:#1769d2;color:#fff;font-weight:800}.mr-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.mr-card{margin-top:12px;border:1px solid #dfe7f1;border-radius:11px;background:#fff;overflow:hidden}.mr-card h3{padding:11px 14px;margin:0;border-bottom:1px solid #e8edf3;font-size:13px}.mr table{width:100%;border-collapse:collapse}.mr td{padding:8px 12px;border-bottom:1px solid #edf1f5;font-size:10px}.mr .num{text-align:right}.mr .section{font-weight:900;background:#f8fafc}.mr .total{font-weight:900;background:#edf4ff}.mr-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:12px}.mr-kpi{padding:13px;border:1px solid #dfe7f1;border-radius:10px;background:#fff}.mr-kpi small{display:block;font-size:8px;font-weight:850;text-transform:uppercase}.mr-kpi strong{display:block;margin-top:7px}.good{color:#128154}.bad{color:#c13d3d}@media(max-width:750px){.mr-grid,.mr-summary{grid-template-columns:1fr}}@media print{.mr-nav,.mr-filter{display:none}.mr{max-width:none}.mr-card{break-inside:avoid}}
</style>
<main class="mr" data-et-balance-sheet="{{ config('et_erp_release.release','ERP-11.3') }}">
  <div class="mr-kicker">Accounting</div><h2>Balance Sheet</h2><div class="mr-sub">Financial position as at {{ $filters['as_of'] }}.</div>
  @include('accounting.management-reporting._navigation')
  <form class="mr-filter" method="get"><div class="mr-field"><label>As Of</label><input type="date" name="as_of" value="{{ $filters['as_of'] }}"></div>@if($filters['branch_supported'])<div class="mr-field"><label>Branch</label><select name="branch_id"><option value="">All Branches</option>@foreach($filters['branches'] as $branch)<option value="{{ $branch['id'] }}" @selected((int)$filters['branch_id']===(int)$branch['id'])>{{ $branch['name'] }}</option>@endforeach</select></div>@endif<button class="mr-btn">Apply</button><button class="mr-btn" type="button" onclick="window.print()">Print</button></form>
  @php($sectionTitles=['current_assets'=>'Current Assets','non_current_assets'=>'Non-Current Assets','current_liabilities'=>'Current Liabilities','non_current_liabilities'=>'Non-Current Liabilities','equity'=>'Equity'])
  <div class="mr-grid"><section class="mr-card"><h3>Assets</h3><table>@foreach(['current_assets','non_current_assets'] as $key)<tr class="section"><td colspan="2">{{ strtoupper($sectionTitles[$key]) }}</td></tr>@forelse($report['sections'][$key] as $line)<tr><td>@if($accountUrls[$line['code']]??null)<a href="{{ $accountUrls[$line['code']] }}">{{ $line['code'] }} · {{ $line['name'] }}</a>@else{{ $line['code'] }} · {{ $line['name'] }}@endif</td><td class="num">{{ $money($line['amount']) }}</td></tr>@empty<tr><td colspan="2">No balance.</td></tr>@endforelse<tr class="total"><td>Total {{ $sectionTitles[$key] }}</td><td class="num">{{ $money(collect($report['sections'][$key])->sum('amount')) }}</td></tr>@endforeach<tr class="total"><td>TOTAL ASSETS</td><td class="num">{{ $money($report['total_assets']) }}</td></tr></table></section>
  <section class="mr-card"><h3>Liabilities &amp; Equity</h3><table>@foreach(['current_liabilities','non_current_liabilities','equity'] as $key)<tr class="section"><td colspan="2">{{ strtoupper($sectionTitles[$key]) }}</td></tr>@forelse($report['sections'][$key] as $line)<tr><td>@if($line['code'] && ($accountUrls[$line['code']]??null))<a href="{{ $accountUrls[$line['code']] }}">{{ $line['code'] }} · {{ $line['name'] }}</a>@else{{ $line['code'] ? $line['code'].' · ' : '' }}{{ $line['name'] }}@endif</td><td class="num">{{ $money($line['amount']) }}</td></tr>@empty<tr><td colspan="2">No balance.</td></tr>@endforelse<tr class="total"><td>Total {{ $sectionTitles[$key] }}</td><td class="num">{{ $money(collect($report['sections'][$key])->sum('amount')) }}</td></tr>@endforeach<tr class="total"><td>TOTAL LIABILITIES &amp; EQUITY</td><td class="num">{{ $money($report['liabilities_equity']) }}</td></tr></table></section></div>
  <section class="mr-summary"><div class="mr-kpi"><small>Total Assets</small><strong>{{ $money($report['total_assets']) }}</strong></div><div class="mr-kpi"><small>Total Liabilities + Equity</small><strong>{{ $money($report['liabilities_equity']) }}</strong></div><div class="mr-kpi"><small>Difference</small><strong class="{{ abs($report['difference'])<0.005?'good':'bad' }}">{{ $money($report['difference']) }} · {{ abs($report['difference'])<0.005?'BALANCED':'REVIEW' }}</strong></div></section>
</main>
@endsection
