@extends($layoutMeta['layout'])
@section($layoutMeta['title_section'] ?? 'title','Management Overview')
@section($layoutMeta['content_section'] ?? 'content')
@php
  $money=fn($value)=>'PKR '.number_format((float)$value,2);
  $signed=fn($value)=>$money(abs((float)$value)).' '.((float)$value<0?'Cr':'Dr');
@endphp
<style>
.mr{max-width:1500px;margin:0 auto;color:#17243a}.mr *{box-sizing:border-box}.mr-head{display:flex;justify-content:space-between;gap:14px;align-items:flex-start}.mr-kicker{font-size:10px;font-weight:850;color:#1769d2;text-transform:uppercase}.mr h2{margin:3px 0;font-size:24px}.mr-sub{font-size:11px;color:#6d7c91}.mr-nav{display:flex;gap:5px;flex-wrap:wrap;margin:14px 0}.mr-nav a{padding:8px 11px;border:1px solid #d9e2ed;border-radius:7px;background:#fff;color:#34455c;text-decoration:none;font-size:10px;font-weight:800}.mr-nav a.active{background:#1769d2;border-color:#1769d2;color:#fff}.mr-filter{display:grid;grid-template-columns:180px minmax(180px,260px) auto 1fr;gap:10px;align-items:end;padding:12px;border:1px solid #dfe7f1;border-radius:10px;background:#fff}.mr-field label{display:block;margin-bottom:4px;font-size:9px;font-weight:850;text-transform:uppercase;color:#68788d}.mr-field input,.mr-field select{width:100%;padding:8px 9px;border:1px solid #ced9e6;border-radius:6px;background:#fff}.mr-btn{padding:9px 13px;border:0;border-radius:6px;background:#1769d2;color:#fff;font-weight:800;cursor:pointer}.mr-print{justify-self:end;background:#fff;color:#34455c;border:1px solid #ced9e6}.mr-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px;margin-top:12px}.mr-kpi{padding:13px;border:1px solid #dfe7f1;border-radius:10px;background:#fff}.mr-kpi small{display:block;font-size:8.5px;font-weight:850;color:#708096;text-transform:uppercase}.mr-kpi strong{display:block;margin-top:7px;font-size:16px}.mr-kpi .good{color:#128154}.mr-kpi .bad{color:#c13d3d}.mr-card{margin-top:12px;border:1px solid #dfe7f1;border-radius:11px;background:#fff;overflow:hidden}.mr-card-head{display:flex;justify-content:space-between;gap:10px;padding:12px 14px;border-bottom:1px solid #e8edf3}.mr-card-head h3{margin:0;font-size:14px}.mr-note{font-size:9px;color:#718096}.mr-body{padding:12px 14px}.mr-table-wrap{overflow:auto}.mr table{width:100%;border-collapse:collapse;min-width:720px}.mr th,.mr td{padding:9px 10px;border-bottom:1px solid #edf1f5;text-align:left;font-size:10px}.mr th{font-size:8px;text-transform:uppercase;color:#6f7e91;background:#f8fafc}.mr .num{text-align:right}.mr .profit{color:#128154;font-weight:850}.mr .loss{color:#c13d3d;font-weight:850}.mr-two{display:grid;grid-template-columns:1fr 1fr;gap:12px}.mr-status{padding:5px 8px;border-radius:999px;background:#e7f8ef;color:#087443;font-size:9px;font-weight:850}.mr-status.bad{background:#ffeded;color:#b93131}@media(max-width:1150px){.mr-grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:800px){.mr-two{grid-template-columns:1fr}.mr-filter{grid-template-columns:1fr 1fr}.mr-print{justify-self:start}.mr-grid{grid-template-columns:1fr 1fr}}@media(max-width:520px){.mr-head{display:block}.mr-filter,.mr-grid{grid-template-columns:1fr}.mr table{min-width:620px}}@media print{.mr-nav,.mr-filter,.mr-print{display:none!important}.mr{max-width:none}.mr-card,.mr-kpi{break-inside:avoid;box-shadow:none}}
</style>
<main class="mr" data-et-management-reporting="{{ config('et_erp_release.release','ERP-11.3') }}">
  <header class="mr-head"><div><div class="mr-kicker">Accounting</div><h2>Management Overview</h2><div class="mr-sub">Daily accounting and financial position.</div></div></header>
  @include('accounting.management-reporting._navigation')
  <form class="mr-filter" method="get"><div class="mr-field"><label>As Of</label><input type="date" name="as_of" value="{{ $filters['as_of'] }}"></div>@if($filters['branch_supported'])<div class="mr-field"><label>Branch</label><select name="branch_id"><option value="">All Branches</option>@foreach($filters['branches'] as $branch)<option value="{{ $branch['id'] }}" @selected((int)$filters['branch_id']===(int)$branch['id'])>{{ $branch['name'] }}</option>@endforeach</select></div>@endif<div><button class="mr-btn">Apply</button></div><button class="mr-btn mr-print" type="button" onclick="window.print()">Print</button></form>

  <section class="mr-grid">
    @foreach([['Revenue Today',$report['today']['revenue']],['Direct Cost Today',$report['today']['direct_cost']],['Gross Profit Today',$report['today']['gross_profit']],['Operating Expenses Today',$report['today']['operating_expenses']],['Net Profit Today',$report['today']['net_profit']]] as [$label,$value])
      <div class="mr-kpi"><small>{{ $label }}</small><strong class="{{ str_contains($label,'Profit') ? ($value>=0?'good':'bad') : '' }}">{{ $money($value) }}</strong></div>
    @endforeach
  </section>
  <section class="mr-grid">
    @foreach([['Cash & Bank',$report['position']['cash_bank']],['Customer Receivables',$report['position']['customer_receivables']],['Vendor Payables',$report['position']['vendor_payables']],['Customer Advances',$report['position']['customer_advances']],['Supplier Advances',$report['position']['supplier_advances']]] as [$label,$value])
      <div class="mr-kpi"><small>{{ $label }}</small><strong>{{ $money($value) }}</strong></div>
    @endforeach
  </section>

  <div class="mr-two">
    <section class="mr-card"><div class="mr-card-head"><div><h3>Posted Profit Comparison</h3><div class="mr-note">Native journal date and posted entries only</div></div></div><div class="mr-table-wrap"><table><thead><tr><th>Period</th><th class="num">Revenue</th><th class="num">Gross Profit</th><th class="num">Operating Expense</th><th class="num">Net Profit</th></tr></thead><tbody>@foreach($report['periods'] as $period)<tr><td><strong>{{ $period['label'] }}</strong><br><small>{{ $period['from'] }} — {{ $period['to'] }}</small></td><td class="num">{{ $money($period['revenue']) }}</td><td class="num {{ $period['gross_profit']>=0?'profit':'loss' }}">{{ $money($period['gross_profit']) }}</td><td class="num">{{ $money($period['operating_expenses']) }}</td><td class="num {{ $period['net_profit']>=0?'profit':'loss' }}">{{ $money($period['net_profit']) }}</td></tr>@endforeach</tbody></table></div></section>
    <section class="mr-card"><div class="mr-card-head"><div><h3>Cash Flow Today</h3><div class="mr-note">Cash received/paid is not revenue/expense</div></div></div><div class="mr-body"><div class="mr-grid" style="grid-template-columns:1fr 1fr;margin:0"><div class="mr-kpi"><small>Cash / Bank Inflow</small><strong>{{ $money($report['cash_inflow_today']) }}</strong></div><div class="mr-kpi"><small>Cash / Bank Outflow</small><strong>{{ $money($report['cash_outflow_today']) }}</strong></div></div><div style="margin-top:12px"><span class="mr-status {{ $report['trial_balance']['balanced']?'':'bad' }}">{{ $report['trial_balance']['balanced']?'Accounting Balanced':'Accounting Difference '.$money($report['trial_balance']['difference']) }}</span></div><div class="mr-note" style="margin-top:9px">Fiscal authority: {{ $report['fiscal_year']['authority'] }}</div></div></section>
  </div>

  <section class="mr-card"><div class="mr-card-head"><div><h3>Cash &amp; Bank Position</h3><div class="mr-note">Opening + selected-day movement = current balance</div></div></div><div class="mr-table-wrap"><table><thead><tr><th>Account</th><th class="num">Opening</th><th class="num">Inflow</th><th class="num">Outflow</th><th class="num">Current Balance</th></tr></thead><tbody>@forelse($report['cash_rows'] as $row)<tr><td>@if($accountUrls[$row['code']] ?? null)<a href="{{ $accountUrls[$row['code']] }}">{{ $row['code'] }} · {{ $row['name'] }}</a>@else{{ $row['code'] }} · {{ $row['name'] }}@endif</td><td class="num">{{ $signed($row['opening']) }}</td><td class="num">{{ $money($row['inflow']) }}</td><td class="num">{{ $money($row['outflow']) }}</td><td class="num"><strong>{{ $signed($row['amount']) }}</strong></td></tr>@empty<tr><td colspan="5">No active Cash/Bank posting accounts resolved.</td></tr>@endforelse</tbody></table></div></section>

  <section class="mr-card"><div class="mr-card-head"><div><h3>Posted Product Profitability — Today</h3><div class="mr-note">Accounting journals, not booking commercial snapshots</div></div></div><div class="mr-table-wrap"><table><thead><tr><th>Product</th><th class="num">Revenue</th><th class="num">Direct Cost</th><th class="num">Gross Profit</th><th class="num">Margin %</th></tr></thead><tbody>@foreach($report['products'] as $product)<tr><td><strong>{{ $product['name'] }}</strong></td><td class="num">{{ $money($product['revenue']) }}</td><td class="num">{{ $money($product['direct_cost']) }}</td><td class="num {{ $product['gross_profit']>=0?'profit':'loss' }}">{{ $money($product['gross_profit']) }}</td><td class="num">{{ $product['margin_percent']===null?'—':number_format($product['margin_percent'],2).'%' }}</td></tr>@endforeach</tbody></table></div></section>

  <div class="mr-two">
    @foreach([['Top Customer Receivables',$report['top_customers'],$customerLedgerUrl],['Top Vendor Payables',$report['top_vendors'],$vendorLedgerUrl]] as [$title,$rows,$ledgerUrl])
      <section class="mr-card"><div class="mr-card-head"><h3>{{ $title }}</h3></div><div class="mr-table-wrap"><table style="min-width:420px"><thead><tr><th>Party</th><th class="num">Outstanding</th><th></th></tr></thead><tbody>@forelse($rows as $row)<tr><td>{{ $row['party_name'] }}</td><td class="num">{{ $money(abs($row['outstanding'])) }} {{ $row['side'] }}</td><td class="num">@if($ledgerUrl)<a href="{{ $ledgerUrl }}&party_id={{ $row['party_id'] }}">Open Ledger</a>@endif</td></tr>@empty<tr><td colspan="3">No posted outstanding balances.</td></tr>@endforelse</tbody></table></div></section>
    @endforeach
  </div>
</main>
@endsection
