@extends($layoutMeta['layout'])
@section($layoutMeta['title_section'] ?? 'title','Customer Payment / Refund')
@section($layoutMeta['content_section'] ?? 'content')
<div style="max-width:900px;margin:auto"><h2>Customer Payment / Refund</h2>@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<form method="post" action="{{ route('accounting.customer-payments.store') }}">@csrf
<p><label>Customer * <select name="party_id" id="customer"><option value="">Select customer</option>@foreach($parties as $p)<option value="{{ $p['id'] }}">{{ $p['name'] }}</option>@endforeach</select></label> <label>Payment Date * <input type="date" name="payment_date" value="{{ now()->toDateString() }}" required></label> <label>Branch * <input type="number" name="branch_id" min="1" required></label></p>
<p><label>Amount * <input id="amount" type="number" name="amount" step="0.01" min="0.01" required></label> <label>Currency <input name="currency_code" value="PKR" required></label> <label>Exchange Rate <input name="exchange_rate" value="1" step="0.00000001" min="0.00000001"></label></p>
<p><label>Cash / Bank Account * <input name="cash_bank_account" required></label> <label>Payment Method <input name="payment_method"></label></p><p><label>Reference <input name="reference"></label> <label>Reason * <input name="reason" required></label></p><p><label>Narration / Remarks <textarea name="narration"></textarea></label></p>
<h3>Eligible customer credit sources</h3><div id="sources">Select a customer.</div><div id="hidden"></div><button type="submit">Save Draft</button></form></div>
<script>const c=document.getElementById('customer'),s=document.getElementById('sources'),h=document.getElementById('hidden');c.addEventListener('change',async()=>{h.innerHTML='';if(!c.value){s.textContent='Select a customer.';return}const j=await fetch('{{ route('accounting.customer-payments.sources') }}?party_id='+c.value).then(r=>r.json());s.innerHTML=(j.sources||[]).map((x,i)=>'<label style="display:block"><input type="number" min="0" step="0.01" max="'+x.available_amount+'" data-i="'+i+'" placeholder="0.00"> '+x.source_reference+' · '+x.source_type+' · available '+Number(x.available_amount).toFixed(2)+'</label>').join('')||'No eligible credit.';s.querySelectorAll('input').forEach((el)=>el.addEventListener('input',()=>{const x=j.sources[Number(el.dataset.i)];h.innerHTML='';s.querySelectorAll('input').forEach((q,k)=>{if(Number(q.value)>0){const z=j.sources[Number(q.dataset.i)],p=Number(q.value);h.insertAdjacentHTML('beforeend','<input type="hidden" name="allocations['+k+'][source_type]" value="'+z.source_type+'"><input type="hidden" name="allocations['+k+'][source_id]" value="'+z.source_id+'"><input type="hidden" name="allocations['+k+'][source_reference]" value="'+z.source_reference+'"><input type="hidden" name="allocations['+k+'][original_amount]" value="'+z.original_amount+'"><input type="hidden" name="allocations['+k+'][used_amount]" value="'+z.used_amount+'"><input type="hidden" name="allocations['+k+'][amount]" value="'+p+'">')}})}))});</script>
@endsection
