@extends($layoutMeta['layout'])
@section($layoutMeta['title_section'] ?? 'title','Party Opening Balance')
@section($layoutMeta['content_section'] ?? 'content')
<style>.et378-form{max-width:980px;margin:auto;color:#17243a}.et378-form *{box-sizing:border-box}.et378-form h1{font-size:26px;margin:4px 0}.et378-sub{font-size:12px;color:#708197}.et378-card{background:#fff;border:1px solid #dce5ef;border-radius:11px;box-shadow:0 4px 14px #1c2d4408;padding:18px;margin-top:16px}.et378-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.et378-field label{display:block;margin-bottom:5px;font-size:10px;font-weight:800;color:#607087;text-transform:uppercase}.et378-field input,.et378-field select,.et378-field textarea{width:100%;min-height:38px;border:1px solid #d3deea;border-radius:7px;padding:8px 10px;color:#26384e;background:#fff}.et378-field textarea{min-height:84px;resize:vertical}.et378-actions{display:flex;gap:9px;justify-content:flex-end;margin-top:16px}.et378-btn{display:inline-flex;align-items:center;min-height:37px;padding:8px 14px;border:1px solid #cbd8e6;border-radius:8px;background:#fff;color:#24405f;text-decoration:none;font-size:12px;font-weight:800}.et378-btn.primary{background:#1469d2;border-color:#1469d2;color:#fff}.et378-alert{padding:10px 12px;border-radius:8px;background:#fff0f0;color:#a43f47;font-size:12px}@media(max-width:650px){.et378-grid{grid-template-columns:1fr}}</style>
<div class="et378-form"><div><div class="et378-sub">Party balances · Controlled setup</div><h1>New opening balance</h1><div class="et378-sub">Create a draft opening position for approval and posting.</div></div>@if($errors->any())<div class="et378-alert">{{ $errors->first() }}</div>@endif
<form class="et378-card" method="post" action="{{ route('accounting.party-opening-balances.store') }}">@csrf
<div class="et378-grid">
<div class="et378-field"><label>Party type *</label><select name="party_type" id="partyType"><option value="customer">Customer</option><option value="vendor">Vendor / Supplier</option></select></div><div class="et378-field"><label>Party *</label><select name="party_id" id="party"><option value="">Select party</option></select></div><div class="et378-field"><label>Balance type *</label><select name="balance_type">@foreach($openingTypes as $k=>$v)<option value="{{ $k }}">{{ $v }}</option>@endforeach</select></div><div class="et378-field"><label>Opening date *</label><input type="date" name="opening_date" value="{{ $openingDate ?? now()->toDateString() }}" required></div><div class="et378-field"><label>Branch *</label><select name="branch_id" required>@foreach(($branches ?? []) as $branch)<option value="{{ $branch['id'] }}">{{ $branch['name'] }}</option>@endforeach</select></div><div class="et378-field"><label>Amount *</label><input type="number" name="amount" min="0.01" step="0.01" required></div><div class="et378-field"><label>Currency</label><input name="currency_code" value="PKR" required></div><div class="et378-field"><label>Exchange rate</label><input type="number" name="exchange_rate" value="1" step="0.00000001" min="0.00000001"></div><div class="et378-field"><label>Legacy reference</label><input name="legacy_reference"></div><div class="et378-field"><label>External account reference</label><input name="external_account_reference"></div><div class="et378-field" style="grid-column:1/-1"><label>Narration / notes</label><textarea name="narration"></textarea></div></div><div class="et378-actions"><a class="et378-btn" href="{{ route('accounting.party-opening-balances.index') }}">Cancel</a><button class="et378-btn primary" type="submit">Save draft</button></div></form></div>
<script>const c=@json($parties),v=@json($vendorParties),t=document.getElementById('partyType'),p=document.getElementById('party');function fill(){p.innerHTML='<option value="">Select party</option>'+((t.value==='vendor'?v:c).map(x=>'<option value="'+x.id+'">'+String(x.name).replace(/[&<>]/g,'')+'</option>').join(''))}t.addEventListener('change',fill);fill();</script>
@endsection
