@extends($layoutMeta['layout'])
@section($layoutMeta['title_section'] ?? 'title',$row->opening_no)
@section($layoutMeta['content_section'] ?? 'content')
<style>.et378-show{max-width:980px;margin:auto;color:#17243a}.et378-show h1{margin:4px 0;font-size:26px}.et378-sub{font-size:12px;color:#708197}.et378-card{background:#fff;border:1px solid #dce5ef;border-radius:11px;box-shadow:0 4px 14px #1c2d4408;padding:18px;margin-top:16px}.et378-meta{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.et378-meta div{padding:12px;border:1px solid #e4ebf3;border-radius:8px;background:#f8fafc}.et378-meta small{display:block;color:#708197;font-size:10px;text-transform:uppercase;font-weight:800}.et378-meta strong{display:block;margin-top:4px;font-size:13px}.et378-actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:18px}.et378-btn{display:inline-flex;align-items:center;min-height:37px;padding:8px 14px;border:1px solid #cbd8e6;border-radius:8px;background:#fff;color:#24405f;text-decoration:none;font-size:12px;font-weight:800}.et378-btn.primary{background:#1469d2;border-color:#1469d2;color:#fff}.et378-alert{padding:10px 12px;border-radius:8px;background:#fff0f0;color:#a43f47;font-size:12px}@media(max-width:700px){.et378-meta{grid-template-columns:repeat(2,1fr)}}@media(max-width:460px){.et378-meta{grid-template-columns:1fr}}</style>
<div class="et378-show"><div class="et378-sub">Party balances · Opening balance</div><h1>{{ $row->opening_no }}</h1><div class="et378-sub">Review lifecycle status and controlled workflow actions.</div>@if($errors->any())<div class="et378-alert">{{ $errors->first() }}</div>@endif
<section class="et378-card"><div class="et378-meta"><div><small>Party</small><strong>{{ $row->party_name }}</strong></div><div><small>Balance type</small><strong>{{ ucwords(str_replace('_',' ',$row->balance_type)) }}</strong></div><div><small>Amount</small><strong>{{ number_format($row->amount,2) }} {{ $row->currency_code }}</strong></div><div><small>Status</small><strong>{{ ucwords(str_replace('_',' ',$row->status)) }}</strong></div></div><div class="et378-actions">
@if($row->status==='draft'&&$canUpdate)<form method="post" action="{{ route('accounting.party-opening-balances.workflow',[$row->id,'submit']) }}" style="display:inline">@csrf<button>Submit</button></form>@endif
@if($row->status==='pending_approval'&&$canApprove)<form method="post" action="{{ route('accounting.party-opening-balances.workflow',[$row->id,'approve']) }}" style="display:inline">@csrf<button>Approve</button></form>@endif
@if($row->status==='approved'&&$canPost)<form method="post" action="{{ route('accounting.party-opening-balances.workflow',[$row->id,'post']) }}" style="display:inline">@csrf<button>Post</button></form>@endif
@if($row->status==='posted'&&$canReverse)<form method="post" action="{{ route('accounting.party-opening-balances.reverse',$row->id) }}">@csrf<input name="reason" placeholder="Reversal reason" required><button class="et378-btn">Reverse</button></form>@endif</div></section></div>
@endsection
