<?php

namespace App\Services\Operations;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/** Atomic append-only native projection for approved supplementary batches. */
final class GeneralBookingAdditionalServiceMaterializer
{
    private array $existingServiceIds = [];
    public function __construct(
        private readonly GeneralBookingAdditionalServiceMaterializationPlanner $planner,
        private readonly GeneralBookingAdditionalServiceSnapshotIntegrity $integrity,
        private readonly NativeProductServiceResolver $products,
        private readonly ActiveBookingPassengerResolver $passengers,
        private readonly GeneralBookingHotelNativeStoreResolver $hotelStore,
        private readonly BookingEditLockResolver $locks,
    ) {}

    public function materialize(int $bookingId, int $batchId, int $userId = 0): array
    {
        return DB::transaction(function () use ($bookingId, $batchId, $userId): array {
            $booking = DB::table('bookings')->where('id',$bookingId)->lockForUpdate()->first();
            if (!$booking) return $this->blocked('booking_missing');
            $batch = DB::table('general_booking_billing_batches')->where('id',$batchId)->where('booking_id',$bookingId)->lockForUpdate()->first();
            if (!$batch) return $this->blocked('batch_missing');
            $items = DB::table('general_booking_billing_batch_items')->where('batch_id',$batchId)->where('booking_id',$bookingId)->orderBy('line_no')->orderBy('id')->lockForUpdate()->get();
            $existingServiceIds = Schema::hasTable('booking_services')
                ? DB::table('booking_services')->where('booking_id',$bookingId)->pluck('id')->map(fn($id)=>(int)$id)->all()
                : [];
            $this->existingServiceIds = $existingServiceIds;
            $plan = $this->planner->plan($bookingId,$batchId);
            if (($plan['code']??null)==='already_materialized') { $this->verifyLinks($bookingId,$plan,$items); return ['ok'=>true,'code'=>'already_materialized','idempotent'=>true,'materialization_state'=>'already_materialized','travel_ready_reset'=>false]; }
            if (($plan['ready']??false)!==true || ($plan['materialization_state']??'')!=='unmaterialized') return $this->blocked((string)($plan['code']??'materialization_blocked'));
            if ($items->isEmpty() || $items->contains(fn($item): bool=>$this->partiallyLinked($item))) return $this->blocked('partial_materialization_link');
            $air=$this->prepareAirGroups($bookingId,$booking,$plan,$items,$userId);
            foreach ($plan['items'] as $itemPlan) {
                $item=$items->firstWhere('id',(int)($itemPlan['id']??0)); if(!$item)throw new \RuntimeException('Locked supplementary item disappeared.');
                $product=strtolower((string)$item->product_type); $runtime=$product==='air'?($air[$this->airGroupKeyForItem((int)$item->id,$plan['product_groups']??[])]??null):null;
                if ($product !== 'air' && (($itemPlan['service_strategy'] ?? '') !== 'new_service' || ($itemPlan['existing_booking_service_id'] ?? null) !== null)) {
                    throw new \RuntimeException('Unmaterialized supplementary items must use new_service.');
                }
                $link=$this->materializeItem($bookingId,$booking,$item,$itemPlan,$runtime,$userId);
                if ($product !== 'air' && in_array((int)($link['booking_service_id'] ?? 0), $this->existingServiceIds, true)) {
                    throw new \RuntimeException('Supplementary service was not newly created.');
                }
                $updated=DB::table('general_booking_billing_batch_items')->where('id',$item->id)->where('batch_id',$batchId)->whereNull('source_table')->whereNull('source_id')->whereNull('booking_service_id')->whereNull('product_service_id')->update($link+['updated_at'=>now()]);
                if($updated!==1)throw new \RuntimeException('Supplementary item link was concurrently changed.');
            }
            $this->verifyLinks($bookingId,$plan,DB::table('general_booking_billing_batch_items')->where('batch_id',$batchId)->where('booking_id',$bookingId)->lockForUpdate()->get());
            $final=$this->planner->plan($bookingId,$batchId);
            if(($final['ready']??false)!==true||($final['code']??'')!=='already_materialized'||($final['materialization_state']??'')!=='already_materialized'||(int)($final['pending_count']??1)!==0||(int)($final['materialized_count']??-1)!==(int)($final['item_count']??-2))throw new \RuntimeException('Final supplementary materialization verification failed.');
            $reset=false;
            if (($plan['would_reset_travel_ready']??false)===true) {
                $locked=$this->locks->fromRow((array)DB::table('bookings')->where('id',$bookingId)->lockForUpdate()->first());
                if (strtolower(trim((string)($locked['travel_status']??'')))!=='ready') throw new \RuntimeException('Travel Ready authority changed.');
                $this->resetTravelReady($bookingId); $reset=true;
            }
            return ['ok'=>true,'code'=>'materialized','materialization_state'=>'materialized','travel_ready_reset'=>$reset];
        });
    }

    private function prepareAirGroups(int $bookingId,object $booking,array $plan,iterable $items,int $userId): array { $rows=[];$runtime=[];foreach($items as $row)$rows[(int)$row->id]=$row;foreach($plan['product_groups']??[] as $group){if(($group['product_type']??'')!=='air')continue;$key=trim((string)($group['group_key']??''));$ids=array_values(array_unique(array_map('intval',$group['item_ids']??[])));if($key===''||!$ids)throw new \RuntimeException('Air planner group is incomplete.');$members=[];foreach($ids as $id){if(!isset($rows[$id])||strtolower((string)$rows[$id]->product_type)!=='air')throw new \RuntimeException('Air planner group item mismatch.');$members[]=$rows[$id];}$master=$this->masterFor('air');$contract=$this->passengerContract($master,'air');if((int)$master['id']!==(int)($group['target_product_service_id']??0))throw new \RuntimeException('Air Product Service authority changed.');$service=$this->appendBookingService($booking,$master,$this->commercialAggregate($members,$master,$contract['pricing_basis']),$contract,$userId);$first=json_decode((string)$members[0]->product_snapshot,true)?:[];$segment=$this->appendAirItinerary($service,$first);$passengers=[];foreach($members as $member){$s=json_decode((string)$member->product_snapshot,true)?:[];$pid=(int)($s['booking_passenger_id']??$member->booking_passenger_id??0);if($pid>0)$passengers[]=$pid;}$runtime[$key]=['service_id'=>$service,'segment_id'=>$segment,'passenger_ids'=>array_values(array_unique($passengers))];$this->appendPassengerLinks($bookingId,$service,$contract,$runtime[$key]['passenger_ids'],'air');}return$runtime; }

    private function materializeItem(int $bookingId,object $booking,object $item,array $plan,?array $runtime,int $userId): array { $s=json_decode((string)$item->product_snapshot,true)?:[];$product=strtolower((string)$item->product_type);if($product==='air'){if(!$runtime)throw new \RuntimeException('Air item has no unique planner group.');$serviceId=(int)$runtime['service_id'];$source=$this->appendAirTicket($bookingId,$serviceId,(int)$runtime['segment_id'],$s,$item);}else{$master=$this->masterFor($product);$contract=$this->passengerContract($master,$product);if((int)$master['id']!==(int)($plan['target_product_service_id']??0))throw new \RuntimeException('Product Service authority changed.');$serviceId=(int)($plan['existing_booking_service_id']??0);if(($plan['service_strategy']??'')==='new_service')$serviceId=$this->appendBookingService($booking,$master,$this->commercialAggregate([$item],$master,$contract['pricing_basis']),$contract,$userId);if($serviceId<=0)throw new \RuntimeException('Native booking service could not be resolved.');$source=match($product){'hotel'=>$this->appendHotel($bookingId,$serviceId,(string)($plan['native_table']??''),$s),'transport'=>$this->appendTransport($bookingId,$serviceId,(string)($plan['native_table']??''),$s),'visa'=>$this->appendVisa($bookingId,$serviceId,$s,$item),default=>throw new \RuntimeException('Unsupported supplementary product.')};$ids=$product==='visa'?[(int)($s['booking_passenger_id']??$item->booking_passenger_id??0)]:$this->passengerIdsFor($bookingId,$contract,$product);$this->appendPassengerLinks($bookingId,$serviceId,$contract,$ids,$product);}return['source_table'=>$source['table'],'source_id'=>$source['id'],'booking_service_id'=>$serviceId,'product_service_id'=>(int)($plan['target_product_service_id']??0)]; }

    private function masterFor(string $product): array { $m=match($product){'air'=>$this->products->findAir(),'hotel'=>$this->products->findHotel(),'transport'=>$this->products->findTransport(),'visa'=>$this->products->findVisa(),default=>null};if(!$m)throw new \RuntimeException('Native Product Service is unresolved.');return$m; }
    private function commercialAggregate(array $items,array $master,string $pricingBasis): array { $q=0.0;$sale=0.0;$cost=0.0;$currency=null;$fx=null;foreach($items as $item){$q+=(float)$this->frozen($item,['quantity','qty'],1);$sale+=(float)$this->frozen($item,['sale_amount','customer_total','selling_total','line_total'],0);$cost+=(float)$this->frozen($item,['supplier_cost_snapshot','supplier_total','vendor_total'],0);$currency=$currency??$this->frozen($item,['currency_code'],null);$fx=$fx??$this->frozen($item,['exchange_rate'],null);} $basis=$pricingBasis;if(in_array($basis,['PER_SERVICE','FLAT','FIXED'],true))$q=1.0;if(!in_array($basis,['PER_SERVICE','FLAT','FIXED','PER_PERSON','PER_PASSENGER','PER_PAX'],true))throw new \RuntimeException('Unsupported pricing basis.');$unit=$q>0?round($sale/$q,2):0.0;if(abs(round($unit*$q,2)-round($sale,2))>=.01)throw new \RuntimeException('Frozen commercial total cannot be represented exactly.');return['quantity'=>$q,'unit_price'=>$unit,'sale_amount'=>round($sale,2),'supplier_cost'=>round($cost,2),'margin'=>round($sale-$cost,2),'currency_code'=>$currency,'exchange_rate'=>$fx]; }
    private function frozen(object $item,array $keys,mixed $fallback): mixed { foreach($keys as $key)if(isset($item->{$key})&&$item->{$key}!=='')return$item->{$key};return$fallback; }
    private function appendBookingService(object $booking,array $master,array $commercial,array $contract,int $userId): int { if(!Schema::hasTable('booking_services'))throw new \RuntimeException('Native booking service schema unavailable.');$columns=Schema::getColumnListing('booking_services');$source=(array)($master['row']??[]);$row=['booking_id'=>(int)$booking->id,'product_service_id'=>(int)$master['id']];foreach(['company_id','branch_id','customer_id','agent_id','salesperson_id','currency_id','tenant_id','office_id'] as $field)if(in_array($field,$columns,true)&&property_exists($booking,$field))$row[$field]=$booking->{$field};$this->putFirst($row,$columns,['service_name','name','title','description'],$this->first($source,['name','service_name','title','label','description']));$this->putFirst($row,$columns,['service_code','product_code','code','slug'],$this->first($source,['code','service_code','product_code','slug']));$this->putFirst($row,$columns,['revenue_mapping_key','revenue_mapping_key_snapshot','accounting_mapping_key','accounting_mapping_key_snapshot','mapping_key','mapping_key_snapshot','revenue_key'],$this->first($source,['revenue_mapping_key','revenue_mapping_key_snapshot','revenue_mapping','accounting_mapping_key','mapping_key','revenue_key']));foreach(['revenue_account_id','income_account_id','sales_account_id','service_revenue_account_id','account_id','ledger_account_id'] as $field)if(in_array($field,$columns,true)&&isset($source[$field]))$row[$field]=(int)$source[$field];$this->putFirst($row,$columns,['passenger_link_mode_snapshot','passenger_link_mode'],strtoupper((string)$contract['mode']));$this->putFirst($row,$columns,['pricing_basis_snapshot','pricing_basis'],strtoupper((string)$contract['pricing_basis']));$this->putAll($row,$columns,['quantity','qty'],$commercial['quantity']);$this->putAll($row,$columns,['unit_price'],$commercial['unit_price']);$this->putAll($row,$columns,['line_total','customer_total','selling_total','sale_amount'],$commercial['sale_amount']);$this->putAll($row,$columns,['supplier_total','vendor_total','net_supplier_cost','cost_total','total_cost'],$commercial['supplier_cost']);$this->putAll($row,$columns,['margin','gross_margin','net_margin','profit'],$commercial['margin']);if($commercial['currency_code']!==null)$this->putAll($row,$columns,['currency_code'],$commercial['currency_code']);if($commercial['exchange_rate']!==null)$this->putAll($row,$columns,['exchange_rate'],$commercial['exchange_rate']);foreach(['created_by','updated_by'] as $field)if(in_array($field,$columns,true)&&$userId>0)$row[$field]=$userId;$this->putActiveStatus($row,$columns);if(in_array('created_at',$columns,true))$row['created_at']=now();if(in_array('updated_at',$columns,true))$row['updated_at']=now();$this->requiredColumnsSafe('booking_services',$row);return(int)DB::table('booking_services')->insertGetId($row); }
    private function putActiveStatus(array &$row,array $columns): void { if(!in_array('status',$columns,true))return;$value=$this->enumCompatible('booking_services','status',['pending','Pending','active','Active','unissued','Unissued']);if($value===null)throw new \RuntimeException('No compatible active native booking service status.');$row['status']=$value; }
    private function appendAirItinerary(int $serviceId,array $s): int { $this->projectAirServiceContext($serviceId,$s);$segments=is_array($s['segments']??null)&&$s['segments']!==[]?$s['segments']:[$s];$first=0;$seen=[];foreach($segments as $segment){if(!is_array($segment))continue;$key=hash('sha256',json_encode([$segment['from']??null,$segment['to']??null,$segment['departure_at']??null,$segment['arrival_at']??null,$segment['flight_number']??null],JSON_UNESCAPED_SLASHES));if(isset($seen[$key]))continue;$seen[$key]=true;$id=$this->insertNative('booking_itinerary_segments',['booking_service_id'=>$serviceId,'from'=>$segment['from']??null,'to'=>$segment['to']??null,'from_code'=>$segment['from_code']??$segment['from']??null,'to_code'=>$segment['to_code']??$segment['to']??null,'departure_at'=>$segment['departure_at']??null,'arrival_at'=>$segment['arrival_at']??null,'flight_number'=>$segment['flight_number']??null,'airline_id'=>$segment['airline_id']??null,'airline_code'=>$segment['airline_code']??null,'airline_name'=>$segment['airline_name']??$segment['airline']??null])['id'];$first=$first?:$id;}return $first; }
    private function projectAirServiceContext(int $serviceId,array $s): void { if(!Schema::hasTable('booking_services'))return;$cols=Schema::getColumnListing('booking_services');$row=[];$this->putFirst($row,$cols,['vendor_id','supplier_id'],$s['vendor_id']??null);$this->putFirst($row,$cols,['pnr','booking_reference','reference'],$s['pnr']??null);$this->putFirst($row,$cols,['airline_pnr','airline_booking_reference'],$s['airline_pnr']??null);if(in_array('updated_at',$cols,true))$row['updated_at']=now();if($row)DB::table('booking_services')->where('id',$serviceId)->update($row); }
    private function appendAirTicket(int $bookingId,int $serviceId,int $segmentId,array $s,object $item): array { $row=['booking_service_id'=>$serviceId,'booking_id'=>$bookingId,'booking_passenger_id'=>$s['booking_passenger_id']??$item->booking_passenger_id,'airline_id'=>$s['airline_id']??null,'airline_code'=>$s['airline_code']??null,'airline_name'=>$s['airline_name']??null,'flight_number'=>$s['flight_number']??null,'pnr'=>$s['pnr']??null,'airline_pnr'=>$s['airline_pnr']??null,'from'=>$s['from']??null,'to'=>$s['to']??null,'departure_at'=>$s['departure_at']??null,'arrival_at'=>$s['arrival_at']??null,'booking_class'=>$s['booking_class']??null,'baggage'=>$s['baggage']??null];$cols=Schema::getColumnListing('air_ticket_details');$this->putFirst($row,$cols,['ticket_number','ticket_no','e_ticket_number','eticket_number','document_number','document_no'],$s['ticket_number']??$s['ticket_no']??null);$this->putFirst($row,$cols,['sale_amount','customer_total','selling_total','sale_price'],$this->frozen($item,['sale_amount','customer_total','selling_total'],0));$this->putFirst($row,$cols,['supplier_cost','supplier_total','vendor_total','cost_amount','cost_price'],$this->frozen($item,['supplier_cost_snapshot','supplier_total','vendor_total'],0));foreach(['booking_itinerary_segment_id','itinerary_segment_id'] as $f)if($segmentId>0&&in_array($f,$cols,true))$row[$f]=$segmentId;foreach(['ticket_status','status'] as $statusColumn)if(in_array($statusColumn,$cols,true)){$status=$this->enumCompatible('air_ticket_details',$statusColumn,['pending','Pending','unissued','Unissued','open','Open','draft','Draft']);if($status===null)throw new \RuntimeException('No compatible pending Air ticket status.');$row[$statusColumn]=$status;}return['table'=>'air_ticket_details','id'=>$this->insertNative('air_ticket_details',$row)['id']]; }
    private function appendHotel(int $bookingId,int $serviceId,string $plannedTable,array $s): array { $resolved=$this->hotelStore->resolve();if(!$resolved||$resolved['table']!==$plannedTable)throw new \RuntimeException('Hotel plan/store authority changed.');$table=$resolved['table'];$cols=Schema::getColumnListing($table);$row=[];$this->putFirst($row,$cols,['hotel_name','name','hotel_name_snapshot'],$s['hotel_name']??$s['name']??null);$this->putFirst($row,$cols,['city','destination','city_name'],$s['city']??$s['destination']??null);$this->putFirst($row,$cols,['room_type','room','room_category'],$s['room_type']??null);$this->putFirst($row,$cols,['board','meal_plan','board_type'],$s['board']??null);$this->putFirst($row,$cols,['check_in','check_in_date','checkin_date'],$s['check_in']??null);$this->putFirst($row,$cols,['check_out','check_out_date','checkout_date'],$s['check_out']??null);$this->putFirst($row,$cols,['confirmation_no','confirmation_number','booking_reference','reference'],$s['confirmation_no']??$s['booking_reference']??null);$this->putFirst($row,$cols,['hotel_id'],$s['hotel_id']??null);$this->putFirst($row,$cols,['vendor_id','supplier_id'],$s['vendor_id']??null);$this->putFirst($row,$cols,['vendor_name','supplier_name'],$s['vendor_name']??null);if(($resolved['booking_column']??null))$row[$resolved['booking_column']]=$bookingId;if(($resolved['service_link_column']??null))$row[$resolved['service_link_column']]=$serviceId;return['table'=>$table,'id'=>$this->insertNative($table,$row)['id']]; }
    private function appendTransport(int $bookingId,int $serviceId,string $plannedTable,array $s): array { if(!$this->transportTableCompatible($plannedTable))throw new \RuntimeException('Transport planner table is no longer compatible.');$cols=Schema::getColumnListing($plannedTable);$row=[];$this->putFirst($row,$cols,['booking_id'],$bookingId);$this->putFirst($row,$cols,['booking_service_id'],$serviceId);$this->putFirst($row,$cols,['from_location','from','origin','pickup'],$s['from_location']??$s['from']??null);$this->putFirst($row,$cols,['to_location','to','destination','dropoff'],$s['to_location']??$s['to']??null);$this->putFirst($row,$cols,['vehicle_type','vehicle_name','vehicle','vehicle_id'],$s['vehicle_type']??null);$this->putFirst($row,$cols,['service_date','date'],$s['service_date']??null);$this->putFirst($row,$cols,['vendor_id','supplier_id'],$s['vendor_id']??null);$this->putFirst($row,$cols,['vendor_name','supplier_name','company_name'],$s['vendor_name']??$s['company_name']??null);return['table'=>$plannedTable,'id'=>$this->insertNative($plannedTable,$row)['id']]; }
    private function transportTableCompatible(string $table): bool { if($table===''||!Schema::hasTable($table))return false;$c=Schema::getColumnListing($table);return in_array('id',$c,true)&&in_array('booking_id',$c,true)&&(bool)array_intersect(['from_location','from','origin','pickup','route_name','route_label','route'],$c)&&(bool)array_intersect(['to_location','to','destination','dropoff','route_name','route_label','route'],$c)&&(bool)array_intersect(['vehicle_type','vehicle_name','vehicle','vehicle_id'],$c); }
    private function appendVisa(int $bookingId,int $serviceId,array $s,object $item): array { $pid=(int)($s['booking_passenger_id']??$item->booking_passenger_id??0);if($pid<=0||!in_array($pid,$this->passengers->ids($bookingId),true))throw new \RuntimeException('Visa passenger does not belong to booking.');if(DB::table('booking_visa_services')->where('booking_id',$bookingId)->where('booking_passenger_id',$pid)->exists())throw new \RuntimeException('Visa passenger already has a native Visa row.');$cols=Schema::getColumnListing('booking_visa_services');$row=['booking_id'=>$bookingId,'booking_passenger_id'=>$pid,'booking_service_id'=>$serviceId];$this->putFirst($row,$cols,['country','country_name'],$s['country']??null);$this->putFirst($row,$cols,['visa_type','type'],$s['visa_type']??null);$this->putFirst($row,$cols,['provider_type'],$s['provider_type']??null);$this->putFirst($row,$cols,['vendor_id','supplier_id'],$s['vendor_id']??null);$this->putFirst($row,$cols,['vendor_name','supplier_name'],$s['vendor_name']??null);$this->putFirst($row,$cols,['sale_pkr','sale_amount','customer_total'],$this->frozen($item,['sale_amount','customer_total','selling_total'],0));$this->putFirst($row,$cols,['vendor_cost_pkr','supplier_cost_snapshot','supplier_total','vendor_total'],$this->frozen($item,['supplier_cost_snapshot','supplier_total','vendor_total'],0));if(in_array('status',$cols,true)){$status=$this->enumCompatible('booking_visa_services','status',['pending','Pending','unissued','Unissued','draft','Draft']);if($status===null)throw new \RuntimeException('No compatible pending Visa status.');$row['status']=$status;}return['table'=>'booking_visa_services','id'=>$this->insertNative('booking_visa_services',$row)['id']]; }
    private function passengerContract(array $master,string $product): array { $row=(array)($master['row']??[]);$mode=strtoupper(trim((string)($master['passenger_link_mode']??$row['passenger_link_mode']??$row['passenger_link_mode_snapshot']??'')));$basis=strtoupper(trim((string)($master['pricing_basis']??$row['pricing_basis']??$row['pricing_basis_snapshot']??'')));[$modes,$bases]=match($product){'air'=>[['NONE','MULTIPLE','REQUIRED'],['PER_SERVICE','FLAT','FIXED']],'hotel','transport'=>[['REQUIRED','MULTIPLE'],['PER_SERVICE']],'visa'=>[['NONE','SINGLE','REQUIRED','MULTIPLE'],['PER_PERSON','PER_PASSENGER','PER_PAX','PER_SERVICE','FLAT','FIXED']],default=>throw new \RuntimeException('Unsupported supplementary product contract.')};if(!in_array($mode,$modes,true))throw new \RuntimeException($product.' passenger-link mode is not supported.');if(!in_array($basis,$bases,true))throw new \RuntimeException($product.' pricing basis is not supported.');return['mode'=>$mode,'pricing_basis'=>$basis]; }
    private function passengerIdsFor(int $bookingId,array $contract,string $product): array { if(in_array($contract['mode'],['REQUIRED','MULTIPLE'],true)&&$contract['pricing_basis']==='PER_SERVICE')return$this->activePassengerIds($bookingId);return[]; }
    private function appendPassengerLinks(int $bookingId,int $serviceId,array $contract,array $ids,string $product): void { $mode=$contract['mode'];$ids=array_values(array_unique(array_map('intval',$ids)));if($mode==='SINGLE'&&count($ids)!==1)throw new \RuntimeException($product.' SINGLE passenger contract is not satisfied.');if(in_array($mode,['REQUIRED','MULTIPLE'],true)&&!$ids)throw new \RuntimeException($product.' required passenger contract is not satisfied.');if($mode==='NONE')return;if(!Schema::hasTable('booking_service_passengers'))throw new \RuntimeException('Required passenger-link table is unavailable.');$cols=Schema::getColumnListing('booking_service_passengers');$serviceCol=in_array('booking_service_id',$cols,true)?'booking_service_id':null;$passengerCol=in_array('booking_passenger_id',$cols,true)?'booking_passenger_id':null;if(!$serviceCol||!$passengerCol)throw new \RuntimeException('Passenger-link schema is incomplete.');$probe=[];if(in_array('created_at',$cols,true))$probe['created_at']=now();if(in_array('updated_at',$cols,true))$probe['updated_at']=now();$this->requiredColumnsSafe('booking_service_passengers',[$serviceCol=>1,$passengerCol=>1]+$probe);foreach($ids as $pid){if(!in_array($pid,$this->passengers->ids($bookingId),true))throw new \RuntimeException('Passenger does not belong to booking.');$where=[$serviceCol=>$serviceId,$passengerCol=>$pid];if(!DB::table('booking_service_passengers')->where($where)->exists())DB::table('booking_service_passengers')->insert($where+$probe);}}
    private function activePassengerIds(int $bookingId): array { return array_values(array_unique(array_map('intval',$this->passengers->ids($bookingId)))); }
    private function verifyLinks(int $bookingId,array $plan,iterable $items): void { $approved=[];foreach($plan['items']??[] as $p)$approved[(int)($p['id']??0)]=$p;foreach($items as $item){if(!$item->source_table||!$item->source_id||!$item->booking_service_id||!$item->product_service_id)throw new \RuntimeException('Incomplete supplementary materialization link.');$master=$this->masterFor((string)$item->product_type);if((int)$master['id']!==(int)$item->product_service_id)throw new \RuntimeException('Product Service link changed.');$p=$approved[(int)$item->id]??[];$source=(array)DB::table($item->source_table)->where('id',$item->source_id)->first();if(!$source)throw new \RuntimeException('Materialized source row is missing.');$product=strtolower((string)$item->product_type);if($product==='hotel'){$resolved=$this->hotelStore->resolve();$mode=strtolower((string)($resolved['ownership_mode']??''));if(!$resolved||$resolved['table']!==$item->source_table)throw new \RuntimeException('Hotel resolver ownership mismatch.');if($mode==='direct_booking'){if(!$resolved['booking_column']||((int)($source[$resolved['booking_column']]??0)!==$bookingId))throw new \RuntimeException('Hotel direct ownership mismatch.');if(($resolved['service_link_column']??null)&&((int)($source[$resolved['service_link_column']]??0)!==(int)$item->booking_service_id))throw new \RuntimeException('Hotel service ownership mismatch.');}elseif($mode==='service_link'){if(!$resolved['service_link_column']||((int)($source[$resolved['service_link_column']]??0)!==(int)$item->booking_service_id))throw new \RuntimeException('Hotel service-link ownership mismatch.');}else throw new \RuntimeException('Unknown Hotel ownership mode.');}else{if(isset($source['booking_id'])&&(int)$source['booking_id']!==$bookingId)throw new \RuntimeException('Materialized source booking ownership is invalid.');if(isset($source['booking_service_id'])&&(int)$source['booking_service_id']!==(int)$item->booking_service_id)throw new \RuntimeException('Materialized source service ownership is invalid.');}$allowed=(string)($p['native_table']??($product==='air'?'air_ticket_details':($product==='visa'?'booking_visa_services':$item->source_table)));if($allowed!==(string)$item->source_table)throw new \RuntimeException('Materialized source table is not planner-approved.');if(!DB::table('booking_services')->where('id',$item->booking_service_id)->where('booking_id',$bookingId)->where('product_service_id',$item->product_service_id)->exists())throw new \RuntimeException('Materialized service link is invalid.');if(in_array($product,['air','visa'],true)&&isset($source['booking_passenger_id'])){$s=json_decode((string)$item->product_snapshot,true)?:[];$pid=(int)($s['booking_passenger_id']??$item->booking_passenger_id??0);if($pid>0&&(int)$source['booking_passenger_id']!==$pid)throw new \RuntimeException('Materialized source passenger ownership is invalid.');}}}
    private function resetTravelReady(int $bookingId): void { $cols=Schema::getColumnListing('bookings');$update=[];foreach(['travel_status','readiness_status','travel_readiness_status'] as $column)if(in_array($column,$cols,true)){ $value=$this->readinessValue($column);if($value===null)throw new \RuntimeException('No proven pending travel value for '.$column);$update[$column]=$value;}if($update)DB::table('bookings')->where('id',$bookingId)->update($update); }
    private function readinessValue(string $column): ?string { return $this->enumCompatible('bookings',$column,['pending','PendingTravel','pending_travel','Pending']); }
    private function enumCompatible(string $table,string $column,array $preferred): ?string { foreach((array)Schema::getColumns($table) as $meta){$name=(string)($meta['name']??$meta->name??'');if($name!==$column)continue;$type=strtolower((string)($meta['type_name']??$meta['type']??$meta->type_name??$meta->type??''));if(str_contains($type,'enum')){preg_match_all("/'([^']+)'/",$type,$m);foreach($preferred as $want)foreach($m[1]??[] as $actual)if(strtolower($actual)===strtolower($want))return$actual;return null;}if($column==='travel_status')return'pending';return null;}return null; }
    private function insertNative(string $table,array $candidate): array { if(!Schema::hasTable($table))throw new \RuntimeException('Native table unavailable: '.$table);$columns=Schema::getColumnListing($table);$row=array_intersect_key($candidate,array_flip($columns));if(in_array('created_at',$columns,true))$row['created_at']=now();if(in_array('updated_at',$columns,true))$row['updated_at']=now();$this->requiredColumnsSafe($table,$row);return['id'=>(int)DB::table($table)->insertGetId($row)]; }
    private function requiredColumnsSafe(string $table,array $row): void { foreach((array)Schema::getColumns($table) as $meta){$name=(string)($meta['name']??$meta->name??'');$nullable=$meta['nullable']??$meta['is_nullable']??$meta->nullable??$meta->is_nullable??null;$nullable=in_array(strtoupper((string)$nullable),['TRUE','YES','Y','1'],true)||$nullable===true;$default=$meta['default']??$meta->default??null;$auto=strtoupper((string)($meta['auto_increment']??$meta['extra']??$meta->extra??''));if($name==='id'||str_contains($auto,'AUTO_INCREMENT')||str_contains($auto,'GENERATED'))continue;if(!$nullable&&$default===null&&!array_key_exists($name,$row))throw new \RuntimeException('Unsupported required native column: '.$table.'.'.$name);}}
    private function putFirst(array &$row,array $columns,array $aliases,mixed $value): void { if($value===null||$value==='')return;foreach($aliases as $alias)if(in_array($alias,$columns,true)){$row[$alias]=$value;return;} }
    private function putAll(array &$row,array $columns,array $aliases,mixed $value): void { foreach($aliases as $alias)if(in_array($alias,$columns,true))$row[$alias]=$value; }
    private function first(array $row,array $keys): mixed { foreach($keys as $key)if(isset($row[$key])&&$row[$key]!=='')return$row[$key];return null; }
    private function airGroupKeyForItem(int $id,array $groups): ?string { $matches=[];foreach($groups as $g)if(($g['product_type']??'')==='air'&&in_array($id,array_map('intval',$g['item_ids']??[]),true))$matches[]=(string)($g['group_key']??'');if(count($matches)!==1||$matches[0]==='')throw new \RuntimeException('Air item must resolve to exactly one planner group.');return$matches[0]; }
    private function partiallyLinked(object $item): bool { $v=[(string)($item->source_table??'')!=='',(int)($item->source_id??0)>0,(int)($item->booking_service_id??0)>0,(int)($item->product_service_id??0)>0];return count(array_unique($v))>1; }
    private function blocked(string $code): array { return['ok'=>false,'code'=>$code,'materialization_state'=>'blocked']; }
}
