@extends($layoutMeta['layout'])
@section($layoutMeta['title_section'] ?? 'title', $booking['booking_reference'] ?? $booking['booking_no'] ?? ('Booking #'.$bookingId))
@section($layoutMeta['content_section'] ?? 'content')
@php($productLabel = $product === 'other-services' ? 'Other Services' : ucfirst($product))
@php($isAirProduct = $product === 'air')
<main class="et-product-workspace etgp-step1{{ $isAirProduct ? '' : ' et-general-progressive-step1-11390' }}" data-etgp-dedicated-product="1" data-etgp-product-key="{{ $product }}" data-booking-id="{{ $bookingId }}" data-booking-reference="{{ $booking['booking_reference'] ?? $booking['booking_no'] ?? ('Booking #'.$bookingId) }}" data-currency="{{ $booking['currency'] ?? $booking['currency_code'] ?? 'PKR' }}" data-etgp-booking-locked="{{ $lock['locked'] ? '1' : '0' }}" data-etgp-booking-status="{{ $lock['status'] }}" data-etgp-selected-products="{{ implode(',', $selectedProducts) }}">
 <header class="et-dedicated-product-header etgp-toolbar" data-et-dedicated-product-header="1" data-etgp-booking-context="1"><div><div class="et-dedicated-product-kicker">GENERAL / MULTI-SERVICE · {{ $productLabel }}</div><h1 class="et-dedicated-product-reference">{{ $booking['booking_reference'] ?? $booking['booking_no'] ?? ('Booking #'.$bookingId) }}</h1><p class="et-dedicated-product-context">{{ $customer['name'] ?? '—' }} · {{ $booking['branch_name'] ?? $booking['office_name'] ?? 'Head Office' }}</p><div class="et-dedicated-product-name">{{ $productLabel }} Workspace</div></div><div class="et-dedicated-product-actions"><span class="et-dedicated-product-status">{{ $lock['status'] }}</span><a href="{{ url('/operations/bookings/'.$bookingId) }}">← Back to Booking</a><a href="{{ route('bookings.review.show',['booking'=>$bookingId]) }}">Review Booking →</a><a href="{{ route('bookings.client-voucher-preview',['booking'=>$bookingId]) }}" target="_blank" rel="noopener noreferrer">Client Preview</a><a href="{{ url('/operations/bookings') }}">Booking Register</a></div></header>
 <section class="et-product-runtime-card"><div data-et-dedicated-notice hidden></div><h2>{{ $productLabel }}</h2>@if($product === 'other-services')<div class="et-dedicated-product-loading">Other Services workspace is not configured yet. Operational workspace not configured yet.</div>@else<div data-etgp-dedicated-product-host><div class="et-dedicated-product-loading" data-et-dedicated-loading>Loading {{ $productLabel }} workspace…</div><div data-etgp-dedicated-product-body></div></div>@endif</section>
</main>
@if(!$isAirProduct)<script>document.addEventListener('DOMContentLoaded',function(){var root=document.querySelector('[data-etgp-dedicated-product="1"]');if(root&&window.etgpMountDedicatedProduct113305)window.etgpMountDedicatedProduct113305(root);});</script>@endif
@endsection
