@extends($layoutMeta['layout'])
@section($layoutMeta['title_section'] ?? 'title','Booking Products')
@section($layoutMeta['content_section'] ?? 'content')
<main class="et-products-hub" data-et-products-hub="1" data-et-booking-smart-overview="1">
  @php($passengerReady = (int) ($passengerCount ?? 0) > 0)
  @php($productsReady = count($selected) > 0)
  @php($approvalStatus = strtolower(trim((string) ($lock['status'] ?? ''))))
  @php($approvalStatus = preg_replace('/\s+/', ' ', str_replace(['_', '-'], ' ', $approvalStatus)) ?: '')
  @php($approvalDone = in_array($approvalStatus, ['approved', 'confirmed', 'travel ready'], true))
  @php($approvalCurrent = in_array($approvalStatus, ['pending', 'pending approval', 'submitted', 'awaiting approval'], true))
  @php($reviewDone = $approvalDone || $approvalCurrent)
  @php($reviewCurrent = !$reviewDone && in_array($approvalStatus, ['draft', 'reopened'], true) && $passengerReady && $productsReady)
  <div class="et-ph-top"><div><div class="et-ph-kicker">Booking Workspace</div><h1>{{ $booking['booking_reference'] ?? $booking['booking_no'] ?? ('Booking #'.$bookingId) }}</h1><div class="et-ph-sub">Products overview · {{ $customer['name'] ?? 'Customer pending' }}</div></div><div class="et-ph-actions"><span class="et-ph-state selected" data-et-booking-status="1">{{ $lock['status'] }}</span><a class="et-ph-btn" href="{{ url('/operations/bookings/'.$bookingId) }}">← Back to Booking</a>@if($lock['locked'])<span class="et-ph-state">Read-only</span>@endif</div></div>
  <section class="et-ph-workflow" aria-label="Booking workflow" data-et-booking-workflow="1"><span class="{{ $passengerReady ? 'done' : 'pending' }}">Passengers {{ $passengerReady ? $passengerCount : 'Required' }}</span><span class="{{ $productsReady ? 'done' : 'pending' }}">Products {{ count($selected) }} Added</span><span class="{{ $reviewDone ? 'done' : ($reviewCurrent ? 'current' : 'pending') }}">Review</span><span class="{{ $approvalDone ? 'done' : ($approvalCurrent ? 'current' : 'pending') }}">Approval {{ $lock['status'] }}</span><span class="pending">Billing / Travel</span></section>
  <section class="et-ph-context"><div><label>Booking Number</label><strong>{{ $booking['booking_reference'] ?? $booking['booking_no'] ?? ('Booking #'.$bookingId) }}</strong></div><div><label>Customer</label><strong>{{ $customer['name'] ?? '—' }}</strong></div><div><label>Booking Type</label><strong>{{ $booking['booking_type'] ?? $booking['type'] ?? 'General' }}</strong></div><div><label>Branch</label><strong>{{ $booking['branch_name'] ?? $booking['office_name'] ?? '—' }}</strong></div><div><label>Status</label><strong>{{ $lock['status'] }}</strong></div></section>
  <nav class="et-ph-steps" aria-label="Booking steps"><a class="et-ph-step done" href="{{ url('/operations/bookings/'.$bookingId) }}"><span class="et-ph-number">1</span>Booking &amp; Passengers</a><span>→</span><span class="et-ph-step current" aria-current="step"><span class="et-ph-number">2</span>Products</span><span>→</span><span class="et-ph-step future"><span class="et-ph-number">3</span>Review</span></nav>
  <div class="et-ph-grid">
  @foreach([['air','AIR','Air / Tickets','itinerary','Open Air'],['hotel','HOTEL','Hotel','stays','Open Hotel'],['transport','TRANSPORT','Transport','transports','Open Transport'],['visa','VISA','Visa','visa_rows','Open Visa']] as $item)
    @php($data=$snapshots[$item[0]] ?? []) @php($count=is_array($data[$item[3]] ?? null)?count($data[$item[3]]):0) @php($summary=$data['summary'] ?? [])
    <article class="et-ph-card" data-et-product-card="{{ $item[0] }}"><div class="et-ph-card-head"><h2>{{ $item[1] }} <span class="et-ph-accessible-label">{{ $item[2] }}</span></h2><span class="et-ph-state {{ in_array($item[0],$selected,true)?'selected':'' }}">{{ in_array($item[0],$selected,true)?'Added':'Not Added' }}</span></div><p>{{ $item[2] }} · {{ in_array($item[0],$selected,true)?'Saved operational data':'Ready to add when permitted' }}</p><div class="et-ph-kv"><div><span>Items</span><strong>{{ $count }}</strong></div><div><span>Booking Value</span><strong>{{ array_key_exists('customer_total',$summary) ? number_format((float)$summary['customer_total'],2) : '—' }}</strong></div><div><span>Supplier Cost</span><strong>{{ array_key_exists('supplier_total',$summary) ? number_format((float)$summary['supplier_total'],2) : (array_key_exists('vendor_total',$summary) ? number_format((float)$summary['vendor_total'],2) : '—') }}</strong></div></div><a class="et-ph-btn primary" href="{{ route('bookings.products.workspace',['booking'=>$bookingId,'product'=>$item[0]]) }}">{{ $lock['locked'] ? 'View' : $item[4] }} →</a></article>
  @endforeach
    <article class="et-ph-card" data-et-product-card="other-services"><div class="et-ph-card-head"><h2>OTHER SERVICES</h2><span class="et-ph-state">Not Configured</span></div><p>Other Services workspace is not configured yet.</p><a class="et-ph-btn" href="{{ route('bookings.products.workspace',['booking'=>$bookingId,'product'=>'other-services']) }}">View</a></article>
  </div>
</main>
@endsection
