@extends($layoutMeta['layout'])
@section($layoutMeta['title_section'] ?? 'title','Booking Products')
@section($layoutMeta['content_section'] ?? 'content')
<style>
.et-products-hub{max-width:1280px;width:calc(100% - 32px);margin:auto;padding:18px 0 72px;color:#17243a}.et-products-hub *{box-sizing:border-box}.et-ph-top,.et-ph-steps,.et-ph-actions{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap}.et-ph-top{margin-bottom:14px}.et-ph-top h1{font-size:22px;margin:0}.et-ph-sub{font-size:12px;color:#718096;margin-top:5px}.et-ph-context,.et-ph-card{background:#fff;border:1px solid #dce8f5;border-radius:14px;box-shadow:0 5px 18px rgba(28,67,111,.07)}.et-ph-context{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:14px;padding:15px;margin-bottom:14px}.et-ph-context label{display:block;text-transform:uppercase;font-size:9px;color:#78889c;font-weight:800}.et-ph-context strong{display:block;font-size:12px;margin-top:4px}.et-ph-steps{justify-content:flex-start;margin-bottom:16px}.et-ph-step{display:inline-flex;align-items:center;gap:7px;text-decoration:none;color:#60748d;font-size:11px;font-weight:800}.et-ph-step.current{color:#1769d2}.et-ph-step.done{color:#168255}.et-ph-step.future{pointer-events:none;opacity:.62}.et-ph-number{width:24px;height:24px;border-radius:50%;display:inline-flex;align-items:center;justify-content:center;background:#edf3fa}.current .et-ph-number{background:#1769d2;color:#fff}.done .et-ph-number{background:#e5f6ed;color:#168255}.et-ph-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.et-ph-card{padding:17px}.et-ph-card h2{font-size:16px;margin:0 0 8px}.et-ph-card p{font-size:11px;color:#718096;margin:0 0 12px}.et-ph-state{display:inline-flex;border-radius:999px;padding:4px 9px;font-size:10px;font-weight:900;background:#f0f4f8;color:#60748d}.et-ph-state.selected{background:#e8f8ef;color:#16764b}.et-ph-kv{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:13px 0}.et-ph-kv span{font-size:10px;color:#718096}.et-ph-kv strong{display:block;color:#17243a;font-size:13px;margin-top:3px}.et-ph-btn{display:inline-flex;min-height:32px;align-items:center;padding:0 11px;border:1px solid #cbd9e8;border-radius:7px;color:#21466f;text-decoration:none;font-size:10px;font-weight:800}.et-ph-btn.primary{background:#1769d2;border-color:#1769d2;color:#fff}@media(max-width:760px){.et-ph-context{grid-template-columns:repeat(2,1fr)}.et-ph-grid{grid-template-columns:1fr}}
</style>
<main class="et-products-hub" data-et-products-hub="1">
 <div class="et-ph-top"><div><h1>Products</h1><div class="et-ph-sub">Choose and manage travel products for this booking.</div></div><div class="et-ph-actions"><a class="et-ph-btn" href="{{ url('/operations/bookings/'.$bookingId) }}">← Booking &amp; Passengers</a>@if($lock['locked'])<span class="et-ph-state">{{ $lock['status'] }} · Read-only</span>@endif</div></div>
 <section class="et-ph-context"><div><label>Booking Number</label><strong>{{ $booking['booking_reference'] ?? $booking['booking_no'] ?? ('Booking #'.$bookingId) }}</strong></div><div><label>Customer</label><strong>{{ $customer['name'] ?? '—' }}</strong></div><div><label>Booking Type</label><strong>{{ $booking['booking_type'] ?? $booking['type'] ?? 'General' }}</strong></div><div><label>Branch</label><strong>{{ $booking['branch_name'] ?? $booking['office_name'] ?? '—' }}</strong></div><div><label>Status</label><strong>{{ $lock['status'] }}</strong></div></section>
 <nav class="et-ph-steps" aria-label="Booking steps"><a class="et-ph-step done" href="{{ url('/operations/bookings/'.$bookingId) }}"><span class="et-ph-number">1</span>Booking &amp; Passengers</a><span>→</span><span class="et-ph-step current" aria-current="step"><span class="et-ph-number">2</span>Products</span><span>→</span><span class="et-ph-step future"><span class="et-ph-number">3</span>Review</span></nav>
 <div class="et-ph-grid">
 @foreach([['air','Air / Tickets','itinerary','tickets','Open Air'],['hotel','Hotel','stays',null,'Open Hotel'],['transport','Transport','transports','services','Open Transport'],['visa','Visa','visa_rows',null,'Open Visa']] as $item)
  @php($data=$snapshots[$item[0]] ?? []) @php($count=is_array($data[$item[2]] ?? null)?count($data[$item[2]]):0) <article class="et-ph-card"><h2>{{ $item[1] }}</h2><span class="et-ph-state {{ in_array($item[0],$selected,true)?'selected':'' }}">{{ in_array($item[0],$selected,true)?'Selected':'Not Selected' }}</span><p>{{ $item[0]==='air' ? 'Saved passengers, segments and tickets from the native Air authority.' : 'Saved data from the native '.ucfirst($item[0]).' authority.' }}</p><div class="et-ph-kv"><div><span>Items</span><strong>{{ $count }}</strong></div><div><span>Customer Total</span><strong>—</strong></div><div><span>Supplier Total</span><strong>—</strong></div></div><a class="et-ph-btn primary" href="{{ url('/operations/bookings/'.$bookingId.'#'.$item[0]) }}">{{ $lock['locked'] ? 'View' : $item[4] }} →</a></article>
 @endforeach
  <article class="et-ph-card"><h2>Other Services</h2><span class="et-ph-state">Not configured</span><p>No stable independent Other Services authority is configured.</p></article>
 </div>
</main>
@endsection
