@extends($layoutMeta['layout'])
@section($layoutMeta['title_section'] ?? 'title', $booking['booking_reference'] ?? $booking['booking_no'] ?? ('Booking #'.$bookingId))
@section($layoutMeta['content_section'] ?? 'content')
<main class="et-product-workspace etgp-step1 et-general-progressive-step1-11390" data-etgp-dedicated-product="1" data-etgp-product-key="{{ $product }}" data-booking-id="{{ $bookingId }}" data-booking-reference="{{ $booking['booking_reference'] ?? $booking['booking_no'] ?? ('Booking #'.$bookingId) }}" data-currency="{{ $booking['currency'] ?? $booking['currency_code'] ?? 'PKR' }}" data-etgp-booking-locked="{{ $lock['locked'] ? '1' : '0' }}" data-etgp-booking-status="{{ $lock['status'] }}" data-etgp-selected-products="{{ implode(',', $selectedProducts) }}">
 <header class="et-booking-focus-context" data-et-booking-focus-context="1"><div class="et-booking-focus-identity"><strong>{{ $booking['booking_reference'] ?? $booking['booking_no'] ?? ('Booking #'.$bookingId) }}</strong><span>{{ $booking['company_name'] ?? $booking['company'] ?? 'Easy Group Of Travels' }} · {{ $booking['branch_name'] ?? $booking['office_name'] ?? 'Head Office' }}</span><span>GENERAL / MULTI-SERVICE</span><span>Booking · {{ $customer['name'] ?? '—' }} · {{ $booking['branch_name'] ?? $booking['office_name'] ?? 'Head Office' }}</span></div><div class="et-booking-focus-actions"><span class="et-booking-focus-badge">{{ $lock['status'] }}</span><a href="{{ route('bookings.client-voucher-preview',['booking'=>$bookingId]) }}" target="_blank" rel="noopener noreferrer">Client Preview</a><button type="button" data-et-booking-focus-menu="1">☰ Menu</button><a href="{{ url('/operations/bookings') }}">Booking Register</a></div></header>
 <header class="et-product-workspace-head"><div><h1>{{ ucfirst($product) }} Workspace</h1><p>{{ $booking['booking_reference'] ?? $booking['booking_no'] ?? ('Booking #'.$bookingId) }} · {{ $customer['name'] ?? '—' }} · {{ $lock['status'] }}</p></div><nav><a href="{{ url('/operations/bookings/'.$bookingId) }}">← Back to Booking</a><a href="{{ route('bookings.review.show',['booking'=>$bookingId]) }}">Review Booking →</a></nav></header>
 <section class="et-product-runtime-card"><h2>{{ $product === 'other-services' ? 'Other Services' : ucfirst($product) }}</h2>@if($product === 'other-services')<p>Operational workspace not configured yet.</p>@else<div data-etgp-dedicated-product-host><div data-etgp-dedicated-product-body></div></div>@endif</section>
</main>
<link rel="stylesheet" href="{{ route('system.erp-assets.general-progressive-step1-css') }}?v={{ rawurlencode(config('et_erp_release.version', 'ERP-11.3')) }}">
<script src="{{ route('system.erp-assets.general-progressive-step1-js') }}?v={{ rawurlencode(config('et_erp_release.version', 'ERP-11.3')) }}" defer></script>
<script>document.addEventListener('DOMContentLoaded',function(){var root=document.querySelector('[data-etgp-dedicated-product="1"]');if(root&&window.etgpMountDedicatedProduct113305)window.etgpMountDedicatedProduct113305(root);});</script>
@endsection
