<?php
namespace App\Http\Controllers\Accounting;
use App\Http\Controllers\Controller;
use App\Services\Accounting\CashVoucherService;
use App\Services\Accounting\PartyAdvanceBalanceService;
use App\Services\Operations\NativeErpLayoutResolver;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

final class AdvanceAdjustmentController extends Controller
{
    public function __construct(private readonly CashVoucherService $service, private readonly PartyAdvanceBalanceService $partyAdvances, private readonly NativeErpLayoutResolver $layout) {}
    public function create(Request $request){abort_unless($this->service->canUseType($request->user(),'customer_advance','create')||$this->service->canUseType($request->user(),'supplier_advance','create'),403);return view('accounting.advance-adjustments.form',$this->formData(null,'create'));}
    public function store(Request $request){$data=$this->validateData($request);$source=$this->partyAdvances->advanceSourceSnapshot($data['advance_source_type'],(int)$data['advance_source_id']);$this->authorizeSource($request->user(),$source,$data['advance_source_type'],'create');$id=DB::transaction(function()use($request,$data):int{$payload=$this->resolvePayload($data);$now=now();$id=DB::table('advance_adjustments')->insertGetId(array_merge($payload,['adjustment_no'=>$this->service->nextAdjustmentNumber(),'adjustment_date'=>$data['adjustment_date'],'amount'=>round((float)$data['amount'],2),'remarks'=>$data['remarks']??null,'status'=>'draft','created_by'=>$request->user()?->id,'created_at'=>$now,'updated_at'=>$now]));$this->service->adjustmentActivity($id,'create',null,'draft',$request->user(),'Advance adjustment draft created.');return$id;});return redirect()->route('accounting.advance-adjustments.show',$id)->with('success','Advance adjustment draft created.');}
    public function show(Request $request,int $adjustment){$row=$this->find($adjustment);$sourceType=(string)($row->advance_source_type?:'cash_voucher');$source=$this->partyAdvances->advanceSourceSnapshot($sourceType,(int)($row->advance_source_id?:$row->advance_voucher_id));$this->authorizeSource($request->user(),$source,$sourceType,'view');$domain=$sourceType==='party_opening_balance'?'party_opening_balance':($source['party_type']==='supplier'?'supplier_advance':'customer_advance');return view('accounting.advance-adjustments.show',['row'=>$row,'source'=>$source,'availableNow'=>$row->status==='posted'?null:$source['available_amount'],'postings'=>DB::table('advance_adjustment_posting_lines')->where('advance_adjustment_id',$adjustment)->orderBy('id')->get(),'activities'=>DB::table('advance_adjustment_activities')->where('advance_adjustment_id',$adjustment)->orderByDesc('id')->get(),'layoutMeta'=>$this->layout->resolve(),'canApprove'=>$this->service->canUseType($request->user(),$domain,'approve'),'canPost'=>$this->service->canUseType($request->user(),$domain,'post'),'canReverse'=>$this->service->canUseType($request->user(),$domain,'reverse'),'canUpdate'=>$this->service->canUseType($request->user(),$domain,'update')]);}
    public function edit(Request $request,int $adjustment){$row=$this->find($adjustment);abort_unless($row->status==='draft',409);$source=$this->partyAdvances->advanceSourceSnapshot((string)($row->advance_source_type?:'cash_voucher'),(int)($row->advance_source_id?:$row->advance_voucher_id));$this->authorizeSource($request->user(),$source,(string)($row->advance_source_type?:'cash_voucher'),'update');return view('accounting.advance-adjustments.form',$this->formData($row,'update'));}
    public function update(Request $request,int $adjustment){$row=$this->find($adjustment);abort_unless($row->status==='draft',409);$oldType=(string)($row->advance_source_type?:'cash_voucher');$oldId=(int)($row->advance_source_id?:$row->advance_voucher_id);$oldSource=$this->partyAdvances->advanceSourceSnapshot($oldType,$oldId);$this->authorizeSource($request->user(),$oldSource,$oldType,'update');$data=$this->validateData($request);$source=$this->partyAdvances->advanceSourceSnapshot($data['advance_source_type'],(int)$data['advance_source_id']);$newSource=(object)$source;$this->service->assertPartyRole((int)$newSource->party_id,(string)$newSource->party_type);abort_unless($this->service->canUseType($request->user(), (string) $newSource->voucher_type, 'update'),403);$this->authorizeSource($request->user(),$source,$data['advance_source_type'],'update');$payload=$this->resolvePayload($data);DB::table('advance_adjustments')->where('id',$adjustment)->update(array_merge($payload,['adjustment_date'=>$data['adjustment_date'],'amount'=>round((float)$data['amount'],2),'remarks'=>$data['remarks']??null,'updated_at'=>now()]));$this->service->adjustmentActivity($adjustment,'update','draft','draft',$request->user(),'Advance adjustment draft updated.');return redirect()->route('accounting.advance-adjustments.show',$adjustment);}
    public function workflow(Request $request,int $adjustment,string $action){abort_unless(in_array($action,['submit','approve','post'],true),404);try{$this->service->transitionAdjustment($adjustment,$action,$request->user());}catch(\Throwable $e){return back()->withErrors(['workflow'=>$e->getMessage()]);}return back();}
    public function reverse(Request $request,int $adjustment){$data=$request->validate(['reason'=>['required','string','max:2000']]);try{$this->service->reverseAdjustment($adjustment,$request->user(),(string)$data['reason']);}catch(\Throwable $e){return back()->withErrors(['workflow'=>$e->getMessage()]);}return back();}
    private function formData(?object $row,string $action='view'):array{$source=null;$partyId=null;$partyType=null;if($row){$source=$this->partyAdvances->advanceSourceSnapshot((string)($row->advance_source_type?:'cash_voucher'),(int)($row->advance_source_id?:$row->advance_voucher_id));$partyId=(int)$source['party_id'];$partyType=(string)$source['party_type'];}$customerAllowed=$this->service->canUseType(request()->user(),'customer_advance',$action)&&($partyType===null||$partyType==='customer');$supplierAllowed=$this->service->canUseType(request()->user(),'supplier_advance',$action)&&($partyType===null||$partyType==='supplier');$openingAllowed=$this->service->canUseType(request()->user(),'party_opening_balance',$action);$sources=[];if($customerAllowed)$sources=array_merge($sources,$this->partyAdvances->advanceOptions('customer',$partyId));if($supplierAllowed)$sources=array_merge($sources,$this->partyAdvances->advanceOptions('supplier',$partyId));$a=array_values(array_filter($sources,fn(array $s):bool=>$openingAllowed||($s['advance_source_type']??null)!=='party_opening_balance'));$sales=$customerAllowed?array_merge($this->service->salesInvoiceOptions($partyId,'customer'),$openingAllowed?$this->service->openingReceivableOptions($partyId):[]):[];$supplier=$supplierAllowed?array_merge($this->service->supplierCostingOptions($partyId,'supplier'),$openingAllowed?$this->service->openingPayableOptions($partyId):[]):[];return['row'=>$row,'advances'=>$a,'salesInvoices'=>$sales,'supplierCostings'=>$supplier,'layoutMeta'=>$this->layout->resolve()];}
    private function validateData(Request $request):array{return$request->validate(['advance_source_type'=>['required','in:cash_voucher,party_opening_balance'],'advance_source_id'=>['required','integer','min:1'],'advance_voucher_id'=>['nullable','integer','min:1'],'target_type'=>['nullable','in:sales_invoice,party_opening_balance,supplier_costing,party_opening_payable'],'target_id'=>['required','integer','min:1'],'adjustment_date'=>['required','date'],'amount'=>['required','numeric','gt:0'],'remarks'=>['nullable','string','max:5000']]);}
    private function resolvePayload(array$data):array{$source=$this->partyAdvances->advanceSourceSnapshot($data['advance_source_type'],(int)$data['advance_source_id']);abort_if((float)$data['amount']>(float)$source['available_amount']+.005,422,'Adjustment exceeds available advance.');$targetType=(string)($data['target_type']??($source['party_type']==='supplier'?'supplier_costing':'sales_invoice'));$target=$this->documentSnapshot($targetType,(int)$data['target_id'],(int)$source['party_id'],(string)$source['party_type']);$this->assertPartyIdentity($source,$target);abort_if((float)$data['amount']>(float)$target['outstanding']+.005,422,'Adjustment exceeds target outstanding.');abort_if(strtoupper((string)$source['currency_code'])!==strtoupper((string)($target['currency_code']??'PKR')),422,'Currency mismatch.');return['advance_source_type'=>$data['advance_source_type'],'advance_source_id'=>(int)$data['advance_source_id'],'advance_voucher_id'=>$data['advance_source_type']==='cash_voucher'?(int)$data['advance_source_id']:null,'party_type'=>$source['party_type'],'party_id'=>$source['party_id'],'party_name'=>$source['party_name'],'target_type'=>$targetType,'target_id'=>(int)$target['id'],'target_number'=>$target['number'],'booking_id'=>$target['booking_id']??$source['booking_id'],'currency_code'=>$source['currency_code'],'exchange_rate'=>$source['exchange_rate']??1];}
    private function documentSnapshot(string $targetType,int $targetId,int $partyId,string $partyType):array{return $this->service->documentSnapshot($targetType,$targetId,$partyId,$partyType);}
    private function assertPartyIdentity(array $source,array $target):void{$source=(object)$source;$this->service->assertPartyRole((int)$source->party_id,(string)$source->party_type);abort_unless($source->party_id,422,'Advance source party is required.');abort_unless($target['party_id']??null,422,'Advance target party is required.');abort_if((int)$source->party_id!==(int)$target['party_id'],422,'Advance party does not match target.');}
    private function find(int$id):object{$row=DB::table('advance_adjustments')->where('id',$id)->first();abort_unless($row,404);return$row;}
    private function authorizeSource(mixed $user,array $source,string $type,string $action):void{$domain=$type==='party_opening_balance'?'party_opening_balance':($source['party_type']==='supplier'?'supplier_advance':'customer_advance');abort_unless($this->service->canUseType($user,$domain,$action),403);if($type==='party_opening_balance')abort_unless($this->service->canUseType($user,$source['party_type']==='supplier'?'supplier_advance':'customer_advance',$action),403);}
}
