<?php
namespace App\Http\Controllers\Accounting;

use App\Http\Controllers\Controller;
use App\Services\Accounting\PartyBalanceLifecycleService;
use App\Services\Accounting\PartyAdvanceReturnService;
use App\Services\Accounting\CashVoucherService;
use App\Services\Operations\NativeErpLayoutResolver;
use Illuminate\Http\Request;

final class PartyBalanceLifecycleController extends Controller
{
    public function __construct(private readonly PartyBalanceLifecycleService $service, private readonly PartyAdvanceReturnService $returns, private readonly CashVoucherService $cash, private readonly NativeErpLayoutResolver $layout) {}
    public function openingCreate(Request $request): mixed { $this->authorizeAny($request->user(),[['customer_advance','view'],['supplier_advance','view']]); return view('accounting.party-opening-balances.form',['layoutMeta'=>$this->layout->resolve(),'parties'=>$this->service->parties('customer'),'vendorParties'=>$this->service->parties('vendor'),'openingTypes'=>['customer_receivable'=>'Customer Receivable / Debit','customer_advance'=>'Customer Advance','vendor_payable'=>'Vendor Payable / Credit','vendor_advance'=>'Vendor Advance']]); }
    public function openingStore(Request $request): mixed { $data=$request->validate(['party_type'=>'required|in:customer,vendor','party_id'=>'required|integer|min:1','opening_type'=>'required|in:customer_receivable,customer_credit,customer_advance,vendor_payable,vendor_advance','opening_date'=>'required|date','amount'=>'required|numeric|gt:0','branch_id'=>'required|integer|min:1','currency_code'=>'required|string|max:12','exchange_rate'=>'nullable|numeric|gt:0','reference'=>'nullable|string|max:190','narration'=>'nullable|string|max:5000','supporting_document'=>'nullable|string|max:500']);$this->authorize($request->user(),$data['party_type']==='vendor'?'supplier_advance':'customer_advance','create');$this->service->assertBranchForUser((int)$data['branch_id'],$request->user());try{$id=$this->service->createOpening($data,$request->user());return redirect()->route('accounting.party-opening-balances.show',$id)->with('success','Party opening balance draft created.');}catch(\Throwable $e){return back()->withInput()->withErrors(['opening'=>$e->getMessage()]);} }
    public function openingShow(Request $request,int $id): mixed { $row=\DB::table('party_opening_balances')->where('id',$id)->first();abort_unless($row,404);$this->authorize($request->user(),$row->party_type==='vendor'?'supplier_advance':'customer_advance','view');return view('accounting.party-opening-balances.show',['layoutMeta'=>$this->layout->resolve(),'row'=>$row,'lines'=>\DB::table('party_opening_balance_posting_lines')->where('party_opening_balance_id',$id)->get()]); }
    public function openingWorkflow(Request $request,int $id,string $action): mixed { $row=\DB::table('party_opening_balances')->where('id',$id)->first();abort_unless($row,404);$this->authorize($request->user(),$row->party_type==='vendor'?'supplier_advance':'customer_advance',$action==='post'?'post':($action==='approve'?'approve':'create'));try{$this->service->transitionOpening($id,$action,$request->user());return back()->with('success','Opening balance workflow updated.');}catch(\Throwable $e){return back()->withErrors(['workflow'=>$e->getMessage()]);} }
    public function openingReverse(Request $request,int $id): mixed { $row=\DB::table('party_opening_balances')->where('id',$id)->first();abort_unless($row,404);$this->authorize($request->user(),$row->party_type==='vendor'?'supplier_advance':'customer_advance','reverse');$d=$request->validate(['reason'=>'required|string|max:2000']);try{$this->service->reverseOpening($id,$d['reason'],$request->user());return back()->with('success','Opening balance reversed.');}catch(\Throwable $e){return back()->withErrors(['workflow'=>$e->getMessage()]);} }
    public function paymentCreate(Request $request): mixed { $this->authorize($request->user(),'receipt','view'); return view('accounting.customer-payments.form',['layoutMeta'=>$this->layout->resolve(),'parties'=>$this->service->parties('customer')]); }
    public function paymentSources(Request $request): mixed { $this->authorize($request->user(),'receipt','view'); try{return response()->json(['sources'=>$this->service->creditSources((int)$request->query('party_id'))]);}catch(\Throwable $e){return response()->json(['sources'=>[],'message'=>$e->getMessage()],422);} }
    public function paymentStore(Request $request): mixed { $data=$request->validate(['party_id'=>'required|integer|min:1','payment_date'=>'required|date','amount'=>'required|numeric|gt:0','branch_id'=>'required|integer|min:1','currency_code'=>'required|string|max:12','exchange_rate'=>'nullable|numeric|gt:0','cash_bank_account'=>'required|string|max:80','payment_method'=>'nullable|string|max:80','reference'=>'nullable|string|max:190','reason'=>'required|string|max:190','narration'=>'nullable|string|max:5000','allocations'=>'required|array|min:1','allocations.*.source_type'=>'required|in:opening_credit,customer_advance','allocations.*.source_id'=>'required|integer|min:1','allocations.*.source_reference'=>'required|string','allocations.*.original_amount'=>'required|numeric','allocations.*.used_amount'=>'nullable|numeric','allocations.*.amount'=>'required|numeric|gt:0']);$this->authorize($request->user(),'receipt','create');$this->service->assertBranchForUser((int)$data['branch_id'],$request->user());try{$id=$this->service->createPayment($data,$request->user());return redirect()->route('accounting.customer-payments.show',$id)->with('success','Customer Payment / Refund draft created.');}catch(\Throwable $e){return back()->withInput()->withErrors(['payment'=>$e->getMessage()]);} }
    public function paymentShow(Request $request,int $id): mixed { $this->authorize($request->user(),'receipt','view');$row=\DB::table('customer_payments')->where('id',$id)->first();abort_unless($row,404);return view('accounting.customer-payments.show',['layoutMeta'=>$this->layout->resolve(),'row'=>$row,'allocations'=>\DB::table('customer_payment_allocations')->where('customer_payment_id',$id)->get(),'lines'=>\DB::table('customer_payment_posting_lines')->where('customer_payment_id',$id)->get()]); }
    public function paymentWorkflow(Request $request,int $id,string $action): mixed { $this->authorize($request->user(),'receipt',$action==='post'?'post':($action==='approve'?'approve':'create'));try{$this->service->transitionPayment($id,$action,$request->user());return back()->with('success','Customer Payment / Refund workflow updated.');}catch(\Throwable $e){return back()->withErrors(['workflow'=>$e->getMessage()]);} }
    public function paymentReverse(Request $request,int $id): mixed { $this->authorize($request->user(),'receipt','reverse');$d=$request->validate(['reason'=>'required|string|max:2000']);try{$this->service->reversePayment($id,$d['reason'],$request->user());return back()->with('success','Customer Payment / Refund reversed.');}catch(\Throwable $e){return back()->withErrors(['workflow'=>$e->getMessage()]);} }
    public function customerAdvanceReturnCreate(Request $request): mixed { $this->authorize($request->user(),'customer_advance_return','view'); return view('accounting.customer-advance-returns.form',['layoutMeta'=>$this->layout->resolve(),'parties'=>$this->service->parties('customer')]); }
    public function customerAdvanceReturnSources(Request $request): mixed { $this->authorize($request->user(),'customer_advance_return','view'); return response()->json(['sources'=>$this->returns->sourceOptions((int)$request->query('party_id'))]); }
    public function customerAdvanceReturnStore(Request $request): mixed { $data=$request->validate(['customer_party_id'=>'required|integer|min:1','return_date'=>'required|date','amount'=>'required|numeric|gt:0','branch_id'=>'required|integer|min:1','currency_code'=>'required|string|max:12','exchange_rate'=>'nullable|numeric|gt:0','cash_bank_account_code'=>'required|string|max:80','cash_bank_account_name'=>'required|string|max:255','payment_method'=>'nullable|string|max:80','transaction_reference'=>'nullable|string|max:190','narration'=>'nullable|string|max:5000','allocations'=>'required|array|min:1','allocations.*.advance_source_type'=>'required|in:cash_voucher,party_opening_balance','allocations.*.advance_source_id'=>'required|integer|min:1','allocations.*.amount'=>'required|numeric|gt:0']);$this->authorize($request->user(),'customer_advance_return','create');try{$id=$this->returns->create($data,$request->user());return redirect()->route('accounting.customer-advance-returns.show',$id)->with('success','Customer advance return draft created.');}catch(\Throwable $e){return back()->withInput()->withErrors(['return'=>$e->getMessage()]);} }
    public function customerAdvanceReturnShow(Request $request,int $id): mixed { $this->authorize($request->user(),'customer_advance_return','view');$row=\DB::table('customer_advance_returns')->where('id',$id)->first();abort_unless($row,404);return view('accounting.customer-advance-returns.show',['layoutMeta'=>$this->layout->resolve(),'row'=>$row,'allocations'=>\DB::table('customer_advance_return_allocations')->where('customer_advance_return_id',$id)->get()]); }
    public function customerAdvanceReturnWorkflow(Request $request,int $id,string $action): mixed { $this->authorize($request->user(),'customer_advance_return',$action==='post'?'post':($action==='approve'?'approve':'create'));try{$this->returns->transition($id,$action,$request->user());return back()->with('success','Customer advance return workflow updated.');}catch(\Throwable $e){return back()->withErrors(['workflow'=>$e->getMessage()]);} }
    public function customerAdvanceReturnReverse(Request $request,int $id): mixed { $this->authorize($request->user(),'customer_advance_return','reverse');$d=$request->validate(['reason'=>'required|string|max:2000']);try{$this->returns->reverse($id,$d['reason'],$request->user());return back()->with('success','Customer advance return reversed.');}catch(\Throwable $e){return back()->withErrors(['workflow'=>$e->getMessage()]);} }
    private function authorize(mixed $user,string $type,string $action): void { abort_unless($this->cash->canUseType($user,$type,$action),403); }
    private function authorizeAny(mixed $user,array $checks): void { foreach($checks as [$type,$action]) if($this->cash->canUseType($user,$type,$action)) return; abort(403); }
}
