<?php

namespace App\Http\Controllers\Accounting;

use App\Http\Controllers\Controller;
use App\Services\Accounting\CashVoucherService;
use App\Services\Accounting\PartyAdvanceReturnService;
use App\Services\Accounting\PartyBalanceLifecycleService;
use App\Services\Operations\NativeErpLayoutResolver;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

final class PartyBalanceLifecycleController extends Controller
{
    public function __construct(private readonly PartyBalanceLifecycleService $service, private readonly PartyAdvanceReturnService $returns, private readonly CashVoucherService $cash, private readonly NativeErpLayoutResolver $layout) {}
    public function openingCreate(Request $request): mixed { $this->authorize($request->user(),'party_opening_balance','create');$branch=$this->authorizedBranch($request->user());return view('accounting.party-opening-balances.form',['layoutMeta'=>$this->layout->resolve(),'parties'=>$this->service->parties('customer'),'vendorParties'=>$this->service->parties('vendor'),'branches'=>$branch,'openingDate'=>$this->financialYearStart()??now()->toDateString(),'openingTypes'=>['customer_receivable'=>'Customer Receivable / Debit','customer_advance'=>'Customer Advance','vendor_payable'=>'Vendor Payable / Credit','vendor_advance'=>'Vendor Advance']]); }
    public function openingIndex(Request $request): mixed { $this->authorize($request->user(),'party_opening_balance','view');$q=\DB::table('party_opening_balances')->orderByDesc('opening_date')->orderByDesc('id');foreach(['party_type','party_id','balance_type','status'] as $f)if($request->filled($f))$q->where($f,$request->input($f));if($request->filled('from'))$q->whereDate('opening_date','>=',$request->input('from'));if($request->filled('to'))$q->whereDate('opening_date','<=',$request->input('to'));if($request->filled('q'))$q->where(function($x)use($request){$x->where('opening_no','like','%'.$request->string('q').'%')->orWhere('party_name','like','%'.$request->string('q').'%');});return view('accounting.party-opening-balances.index',['layoutMeta'=>$this->layout->resolve(),'rows'=>$q->paginate(25),'filters'=>$request->all(),'parties'=>array_merge($this->service->parties('customer'),$this->service->parties('vendor'))]); }
    public function openingStore(Request $request): mixed { $data=$request->validate(['party_type'=>'required|in:customer,vendor','party_id'=>'required|integer|min:1','balance_type'=>'required|in:customer_receivable,customer_advance,vendor_payable,vendor_advance','opening_date'=>'required|date','amount'=>'required|numeric|gt:0','branch_id'=>'nullable|integer|min:1','currency_code'=>'required|string|max:12','exchange_rate'=>'nullable|numeric|gt:0','legacy_reference'=>'nullable|string|max:190','external_account_reference'=>'nullable|string|max:190','narration'=>'nullable|string|max:5000','supporting_document'=>'nullable|string|max:500']);$this->authorize($request->user(),'party_opening_balance','create');$data['branch_id']=$this->resolveBranch((int)($data['branch_id']??0),$request->user());$this->service->assertBranchForUser((int)$data['branch_id'],$request->user());try{$id=$this->service->createOpening($data,$request->user());return redirect()->route('accounting.party-opening-balances.show',$id)->with('success','Party opening balance draft created.');}catch(\Throwable $e){return back()->withInput()->withErrors(['opening'=>$e->getMessage()]);} }
    public function openingShow(Request $request,int $id): mixed { $this->authorize($request->user(),'party_opening_balance','view');$row=\DB::table('party_opening_balances')->where('id',$id)->first();abort_unless($row,404);return view('accounting.party-opening-balances.show',['layoutMeta'=>$this->layout->resolve(),'row'=>$row,'lines'=>\DB::table('party_opening_balance_posting_lines')->where('party_opening_balance_id',$id)->get(),'canUpdate'=>$this->cash->canUseType($request->user(),'party_opening_balance','update'),'canApprove'=>$this->cash->canUseType($request->user(),'party_opening_balance','approve'),'canPost'=>$this->cash->canUseType($request->user(),'party_opening_balance','post'),'canReverse'=>$this->cash->canUseType($request->user(),'party_opening_balance','reverse')]); }
    public function openingWorkflow(Request $request,int $id,string $action): mixed { $this->authorize($request->user(),'party_opening_balance',$action==='post'?'post':($action==='approve'?'approve':($action==='submit'?'update':'update')));try{$this->service->transitionOpening($id,$action,$request->user());return back()->with('success','Opening balance workflow updated.');}catch(\Throwable $e){return back()->withErrors(['workflow'=>$e->getMessage()]);} }
    public function openingReverse(Request $request,int $id): mixed { $this->authorize($request->user(),'party_opening_balance','reverse');$d=$request->validate(['reason'=>'required|string|max:2000']);try{$this->service->reverseOpening($id,$d['reason'],$request->user());return back()->with('success','Opening balance reversed.');}catch(\Throwable $e){return back()->withErrors(['workflow'=>$e->getMessage()]);} }
    public function customerAdvanceReturnCreate(Request $request): mixed { $this->authorize($request->user(),'customer_advance_return','create');return view('accounting.customer-advance-returns.form',['layoutMeta'=>$this->layout->resolve(),'parties'=>$this->service->parties('customer'),'branches'=>$this->authorizedBranch($request->user()),'cashBankAccounts'=>$this->cash->cashBankAccounts()]); }
    public function customerAdvanceReturnIndex(Request $request): mixed { $this->authorize($request->user(),'customer_advance_return','view');$q=\DB::table('customer_advance_returns')->orderByDesc('return_date')->orderByDesc('id');if($request->filled('customer_party_id'))$q->where('customer_party_id',$request->input('customer_party_id'));if($request->filled('status'))$q->where('status',$request->input('status'));if($request->filled('from'))$q->whereDate('return_date','>=',$request->input('from'));if($request->filled('to'))$q->whereDate('return_date','<=',$request->input('to'));if($request->filled('q'))$q->where(function($x)use($request){$x->where('return_no','like','%'.$request->string('q').'%')->orWhere('customer_name','like','%'.$request->string('q').'%');});return view('accounting.customer-advance-returns.index',['layoutMeta'=>$this->layout->resolve(),'rows'=>$q->paginate(25),'filters'=>$request->all(),'parties'=>$this->service->parties('customer')]); }
    public function customerAdvanceReturnSources(Request $request): mixed { $this->authorize($request->user(),'customer_advance_return','create');$partyId=(int)$request->query('party_id');abort_if($partyId<1,422,'A customer is required.');return response()->json(['sources'=>$this->returns->sourceOptions($partyId)]); }
    public function customerAdvanceReturnStore(Request $request): mixed { $data=$request->validate(['customer_party_id'=>'required|integer|min:1','return_date'=>'required|date','value_date'=>'nullable|date','amount'=>'required|numeric|gt:0','branch_id'=>'nullable|integer|min:1','currency_code'=>'required|string|max:12','exchange_rate'=>'nullable|numeric|gt:0','payment_method'=>'nullable|string|max:80','cash_bank_account_code'=>'required|string|max:80','bank_name'=>'nullable|string|max:190','transaction_reference'=>'nullable|string|max:190','instrument_no'=>'nullable|string|max:120','payment_proof'=>'nullable|file|max:'.(int)config('cash_vouchers.proof_max_kb',5120).'|mimes:pdf,jpg,jpeg,png,webp','narration'=>'nullable|string|max:5000','allocations'=>'required|array|min:1','allocations.*.advance_source_type'=>'required|in:cash_voucher,party_opening_balance','allocations.*.advance_source_id'=>'required|integer|min:1','allocations.*.amount'=>'required|numeric|gt:0']);$this->authorize($request->user(),'customer_advance_return','create');$data['branch_id']=$this->resolveBranch((int)($data['branch_id']??0),$request->user());$this->service->assertBranchForUser((int)$data['branch_id'],$request->user());$this->returns->assertSourceFxPolicy($data);if($request->hasFile('payment_proof')){$file=$request->file('payment_proof');$data['payment_proof_path']=$file->store('accounting/payment-proofs','local');$data['payment_proof_original_name']=$file->getClientOriginalName();}try{$id=$this->returns->create($data,$request->user());return redirect()->route('accounting.customer-advance-returns.show',$id)->with('success','Customer advance return draft created.');}catch(\Throwable $e){return back()->withInput()->withErrors(['return'=>$e->getMessage()]);} }
    public function customerAdvanceReturnShow(Request $request,int $id): mixed { $this->authorize($request->user(),'customer_advance_return','view');$row=\DB::table('customer_advance_returns')->where('id',$id)->first();abort_unless($row,404);return view('accounting.customer-advance-returns.show',['layoutMeta'=>$this->layout->resolve(),'row'=>$row,'allocations'=>\DB::table('customer_advance_return_allocations')->where('customer_advance_return_id',$id)->get(),'canUpdate'=>$this->cash->canUseType($request->user(),'customer_advance_return','update'),'canApprove'=>$this->cash->canUseType($request->user(),'customer_advance_return','approve'),'canPost'=>$this->cash->canUseType($request->user(),'customer_advance_return','post'),'canReverse'=>$this->cash->canUseType($request->user(),'customer_advance_return','reverse')]); }
    public function customerAdvanceReturnWorkflow(Request $request,int $id,string $action): mixed { $this->authorize($request->user(),'customer_advance_return',$action==='post'?'post':($action==='approve'?'approve':($action==='submit'?'update':'update')));try{$this->returns->transition($id,$action,$request->user());return back()->with('success','Customer advance return workflow updated.');}catch(\Throwable $e){return back()->withErrors(['workflow'=>$e->getMessage()]);} }
    public function customerAdvanceReturnReverse(Request $request,int $id): mixed { $this->authorize($request->user(),'customer_advance_return','reverse');$d=$request->validate(['reason'=>'required|string|max:2000']);try{$this->returns->reverse($id,$d['reason'],$request->user());return back()->with('success','Customer advance return reversed.');}catch(\Throwable $e){return back()->withErrors(['workflow'=>$e->getMessage()]);} }
    private function authorize(mixed $user,string $type,string $action): void { abort_unless($this->cash->canUseType($user,$type,$action),403); }
    private function resolveBranch(int $selected,mixed $user): int { return $this->service->authorizedBranchForUser($selected>0?$selected:null,$user); }
    private function authorizedBranch(mixed $user): array { $id=$this->resolveBranch(0,$user);return [['id'=>$id,'name'=>'Current authorized branch']]; }
    private function financialYearStart(): ?string { $today=now()->toDateString();foreach(['financial_years','fiscal_years','accounting_financial_years'] as $table){if(\Illuminate\Support\Facades\Schema::hasTable($table)){ $columns=\Illuminate\Support\Facades\Schema::getColumnListing($table);$start=collect(['start_date','from_date','opening_date'])->first(fn($c)=>in_array($c,$columns,true));$end=collect(['end_date','to_date','closing_date'])->first(fn($c)=>in_array($c,$columns,true));if($start){$q=\DB::table($table)->where($start,'<=',$today);if($end)$q->where($end,'>=',$today);$v=$q->orderBy($start)->value($start);if($v)return (string)$v;}}}return null; }
}
