<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use RuntimeException;

return new class extends Migration {
    public function up(): void
    {
        $s = $this->schema();
        if (!$s['control_type'] || !$s['parent']) throw new RuntimeException('Opening Balance Clearing account requires control_type and parent-account columns.');
        $existing = DB::table($s['table'])->whereRaw('UPPER('.$s['control_type'].') = ?', ['OPENING_BALANCE_CLEARING'])->get();
        if ($existing->count() > 1) throw new RuntimeException('Multiple OPENING_BALANCE_CLEARING accounts exist; migration stopped.');
        if ($existing->count() === 1) { $this->assertCompatible($existing->first(), $s); return; }
        $sameName = DB::table($s['table'])->whereRaw('LOWER(TRIM('.$s['name'].')) = ?', ['opening balance clearing'])->get();
        if ($sameName->count() > 0) throw new RuntimeException('An Opening Balance Clearing account already exists without the required control identity; migration stopped.');
        $parents = DB::table($s['table'])->get()->filter(fn($r): bool => $this->normalizeType((string)$r->{$s['type']}) === 'equity' && $this->isRoot($r, $s))->values();
        if ($parents->count() !== 1) throw new RuntimeException('Opening Balance Clearing parent selection is ambiguous; expected exactly one eligible Equity root.');
        $parent = $parents->first(); $code = $this->nextCodeForParentRow($parent, $s); $insert = [$s['code']=>$code,$s['name']=>'Opening Balance Clearing',$s['type']=>$this->storageType('equity',$s),$s['parent']=>$this->parentStorageValue($parent,$s)];
        if($s['subtype'])$insert[$s['subtype']]='Opening Balance / Migration Clearing'; if($s['normal'])$insert[$s['normal']]=$this->storageNormalBalance('credit',$s); if($s['posting'])$insert[$s['posting']]=1; if($s['control_flag'])$insert[$s['control_flag']]=1; $insert[$s['control_type']]='OPENING_BALANCE_CLEARING'; if($s['notes'])$insert[$s['notes']]='System-controlled migration clearing account for authoritative opening balance postings. Not for normal operational vouchers.'; if($s['status'])$insert[$s['status']]='active'; if($s['active'])$insert[$s['active']]=1; foreach(['company_id','branch_id','organization_id','tenant_id','legal_entity_id'] as $c)if(in_array($c,$s['columns'],true))$insert[$c]=$parent->{$c}??null; if($s['created_at'])$insert[$s['created_at']]=now(); if($s['updated_at'])$insert[$s['updated_at']]=now(); DB::table($s['table'])->insert($insert);
    }

    public function down(): void
    {
        $s=$this->schema(); if(!$s['control_type']||!$s['notes'])return; $q=DB::table($s['table'])->whereRaw('UPPER('.$s['control_type'].') = ?', ['OPENING_BALANCE_CLEARING'])->where($s['notes'],'like','System-controlled migration clearing account%'); $row=$q->first(); if(!$row)return;
        foreach(['party_opening_balance_posting_lines','journal_lines','cash_voucher_allocations','advance_adjustments'] as $table) if(Schema::hasTable($table)) { $column=Schema::hasColumn($table,'account_code')?'account_code':(Schema::hasColumn($table,'target_id')?'target_id':null); if($column==='account_code'&&DB::table($table)->where($column,$row->{$s['code']})->exists()) throw new RuntimeException('Opening Balance Clearing has dependent financial history; rollback preserved the account.'); }
        DB::table($s['table'])->where($s['id'],$row->{$s['id']})->delete();
    }

    private function schema(): array { foreach(['chart_of_accounts','chart_accounts','accounts','account_masters','gl_accounts'] as $table){if(!Schema::hasTable($table))continue;$c=Schema::getColumnListing($table);$first=fn(array $xs):?string=>collect($xs)->first(fn($x)=>in_array($x,$c,true));$s=['table'=>$table,'columns'=>$c,'id'=>$first(['id','account_id']),'code'=>$first(['code','account_code','gl_code','number','account_number']),'name'=>$first(['name','account_name','title']),'type'=>$first(['type','account_type','category','account_category']),'subtype'=>$first(['subtype','sub_type','account_subtype','account_sub_type']),'parent'=>$first(['parent_id','parent_account_id','parent_account','parent_code']),'normal'=>$first(['normal_balance','normal_side','balance_type']),'posting'=>$first(['allow_direct_journal_posting','allow_direct_posting','allow_posting','is_posting','posting_allowed','can_post']),'control_flag'=>$first(['is_control_account','is_control','control_account']),'control_type'=>$first(['control_type','control_code','control_key']),'notes'=>$first(['notes','memo','remarks','description']),'status'=>$first(['status','account_status']),'active'=>$first(['is_active','active','enabled']),'created_at'=>$first(['created_at']),'updated_at'=>$first(['updated_at'])];if($s['id']&&$s['code']&&$s['name']&&$s['type'])return $s;}throw new RuntimeException('Chart of Accounts table could not be resolved.'); }
    private function isRoot(object $row,array $s): bool { $v=$row->{$s['parent']}??null; return $v===null||$v===''||(is_numeric($v)&&(int)$v===0); }
    private function parentUsesId(array $s): bool { if(!$s['parent'])return true; if(str_ends_with(strtolower($s['parent']),'_id'))return true; $sample=DB::table($s['table'])->whereNotNull($s['parent'])->value($s['parent']); if($sample===null||$sample==='')return false; $matchesId=DB::table($s['table'])->where($s['id'],$sample)->exists();$matchesCode=DB::table($s['table'])->where($s['code'],(string)$sample)->exists();if($matchesId&&!$matchesCode)return true;if($matchesCode&&!$matchesId)return false;return str_contains(strtolower($s['parent']),'id'); }
    private function parentStorageValue(object $parent,array $s): mixed { return $this->parentUsesId($s)?$parent->{$s['id']}:$parent->{$s['code']}; }
    private function nextCodeForParentRow(object $parent,array $s): string { $pc=trim((string)$parent->{$s['code']});$children=DB::table($s['table'])->where($s['parent'],$this->parentStorageValue($parent,$s))->pluck($s['code'])->map(fn($v)=>trim((string)$v))->filter()->all();if(preg_match('/^\d+$/',$pc)){ $n=(int)$pc+1;foreach($children as $c)if(ctype_digit($c))$n=max($n,(int)$c+1);while(DB::table($s['table'])->where($s['code'],(string)$n)->exists())$n++;return(string)$n;} $max=0;foreach($children as $c)if(preg_match('/^'.preg_quote($pc,'/').'[-\.]?(\d+)$/i',$c,$m))$max=max($max,(int)$m[1]);do{$max++;$code=$pc.'-'.str_pad((string)$max,2,'0',STR_PAD_LEFT);}while(DB::table($s['table'])->where($s['code'],$code)->exists());return$code; }
    private function storageType(string $type,array $s): string { $sample=$s['type']?DB::table($s['table'])->whereNotNull($s['type'])->value($s['type']):null;$sample=is_string($sample)?trim($sample):'';return $sample!==''&&$sample===strtoupper($sample)?strtoupper($type):($sample!==''&&$sample===ucfirst(strtolower($sample))?ucfirst($type):strtolower($type)); }
    private function storageNormalBalance(string $type,array $s): string { $sample=$s['normal']?DB::table($s['table'])->whereNotNull($s['normal'])->value($s['normal']):null;$sample=is_string($sample)?trim($sample):'';return $sample!==''&&$sample===strtolower($sample)?strtolower($type):($sample!==''&&$sample===ucfirst(strtolower($sample))?ucfirst($type):strtoupper($type)); }
    private function normalizeType(string $value): string { $v=strtolower(trim($value));if(str_contains($v,'equity')||str_contains($v,'capital'))return'equity';if(str_contains($v,'asset'))return'asset';if(str_contains($v,'liab'))return'liability';if(str_contains($v,'income')||str_contains($v,'revenue'))return'income';if(str_contains($v,'expense')||str_contains($v,'cost'))return'expense';return$v; }
    private function assertCompatible(object $r,array $s): void { if(trim((string)$r->{$s['code']})===''||$this->norm((string)$r->{$s['name']})!=='opening balance clearing')throw new RuntimeException('Existing Opening Balance Clearing account has incompatible identity.');if($this->normalizeType((string)$r->{$s['type']})!=='equity')throw new RuntimeException('Existing Opening Balance Clearing account is not Equity.');if($s['subtype']&&$this->norm((string)($r->{$s['subtype']}??''))!=='opening balance / migration clearing')throw new RuntimeException('Existing Opening Balance Clearing account has incompatible subtype.');if($s['normal']&&strtolower(trim((string)($r->{$s['normal']}??'')))!=='credit')throw new RuntimeException('Existing Opening Balance Clearing account must have Credit normal balance.');if($s['active']&&!((bool)$r->{$s['active']}))throw new RuntimeException('Existing Opening Balance Clearing account is inactive.');if($s['status']&&!in_array(strtolower(trim((string)($r->{$s['status']}??'')),['active','enabled','open'],true))throw new RuntimeException('Existing Opening Balance Clearing account is not live.');if($s['posting']&&property_exists($r,$s['posting'])&&!((bool)$r->{$s['posting']}))throw new RuntimeException('Existing Opening Balance Clearing account is not posting-enabled.');if($s['control_flag']&&property_exists($r,$s['control_flag'])&&!((bool)$r->{$s['control_flag']}))throw new RuntimeException('Existing Opening Balance Clearing account is not a control account.');if($s['parent']&&($r->{$s['parent']}??null)!==null&&$r->{$s['parent']}!==''){$pv=$r->{$s['parent']};$parent=$this->parentUsesId($s)?DB::table($s['table'])->where($s['id'],$pv)->first():DB::table($s['table'])->where($s['code'],(string)$pv)->first();if(!$parent||$this->normalizeType((string)$parent->{$s['type']})!=='equity')throw new RuntimeException('Existing Opening Balance Clearing account has incompatible Equity parent.');} }
    private function norm(string $value): string { return strtolower((string)preg_replace('/\s+/',' ',trim($value))); }
};
