<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        if (!Schema::hasTable('customer_advance_returns')) Schema::create('customer_advance_returns', function (Blueprint $t): void {
            $t->id(); $t->string('return_no',60)->unique(); $t->unsignedBigInteger('customer_party_id')->index(); $t->string('customer_name'); $t->date('return_date')->index(); $t->date('value_date')->nullable(); $t->string('currency_code',12)->default('PKR'); $t->decimal('exchange_rate',18,8)->default(1); $t->decimal('amount',18,2); $t->string('payment_method',80)->nullable(); $t->string('cash_bank_account_code',80); $t->string('cash_bank_account_name',255); $t->string('bank_name',190)->nullable(); $t->string('transaction_reference',190)->nullable(); $t->string('instrument_no',120)->nullable(); $t->string('payment_proof_path',500)->nullable(); $t->string('payment_proof_original_name',255)->nullable(); $t->text('narration')->nullable(); $t->unsignedBigInteger('branch_id'); $t->unsignedBigInteger('company_id')->nullable(); $t->string('status',30)->default('draft')->index(); $t->unsignedBigInteger('created_by')->nullable(); $t->unsignedBigInteger('submitted_by')->nullable(); $t->timestamp('submitted_at')->nullable(); $t->unsignedBigInteger('approved_by')->nullable(); $t->timestamp('approved_at')->nullable(); $t->unsignedBigInteger('posted_by')->nullable(); $t->timestamp('posted_at')->nullable(); $t->string('posting_reference',90)->nullable()->unique(); $t->unsignedBigInteger('posting_journal_id')->nullable(); $t->unsignedBigInteger('reversed_by')->nullable(); $t->timestamp('reversed_at')->nullable(); $t->string('reversal_reference',90)->nullable()->unique(); $t->text('reversal_reason')->nullable(); $t->timestamps(); $t->index(['customer_party_id','status']);
        });
        if (!Schema::hasTable('customer_advance_return_allocations')) Schema::create('customer_advance_return_allocations', function (Blueprint $t): void { $t->id(); $t->foreignId('customer_advance_return_id')->constrained()->cascadeOnDelete(); $t->string('advance_source_type',40); $t->unsignedBigInteger('advance_source_id'); $t->string('source_number',120); $t->date('source_date')->nullable(); $t->unsignedBigInteger('booking_id')->nullable(); $t->decimal('available_before_snapshot',18,2); $t->decimal('amount',18,2); $t->unsignedInteger('line_no'); $t->string('currency_code',12); $t->unsignedBigInteger('customer_party_id'); $t->timestamps(); $t->unique(['customer_advance_return_id','line_no']); $t->unique(['customer_advance_return_id','advance_source_type','advance_source_id']); $t->index(['advance_source_type','advance_source_id']); });
        if (!Schema::hasTable('customer_advance_return_posting_lines')) Schema::create('customer_advance_return_posting_lines', function (Blueprint $t): void { $t->id(); $t->foreignId('customer_advance_return_id')->constrained()->cascadeOnDelete(); $t->unsignedInteger('line_no'); $t->string('account_code'); $t->string('account_name'); $t->string('party_type')->nullable(); $t->unsignedBigInteger('party_id')->nullable(); $t->decimal('debit',18,2)->default(0); $t->decimal('credit',18,2)->default(0); $t->decimal('base_debit',18,2)->default(0); $t->decimal('base_credit',18,2)->default(0); $t->string('currency_code',12); $t->decimal('exchange_rate',18,8)->default(1); $t->string('entry_type',20)->default('original'); $t->text('narration')->nullable(); $t->timestamps(); });
        if (!Schema::hasTable('customer_advance_return_activities')) Schema::create('customer_advance_return_activities', function (Blueprint $t): void { $t->id(); $t->foreignId('customer_advance_return_id')->constrained()->cascadeOnDelete(); $t->string('action',40); $t->string('from_status')->nullable(); $t->string('to_status')->nullable(); $t->unsignedBigInteger('user_id')->nullable(); $t->text('remarks')->nullable(); $t->timestamps(); });
        if (Schema::hasTable('advance_adjustments')) Schema::table('advance_adjustments', function (Blueprint $t): void { if (!Schema::hasColumn('advance_adjustments','advance_source_type')) $t->string('advance_source_type',40)->nullable()->index(); if (!Schema::hasColumn('advance_adjustments','advance_source_id')) $t->unsignedBigInteger('advance_source_id')->nullable()->index(); });
    }
    public function down(): void
    {
        // Deliberately non-destructive: posted return history must not be dropped by rollback.
    }
};
