@extends($layoutMeta['layout'])
@section('content')
<div class="et-page et378-page">
@if(!($state['schema_ready'] ?? false) || !is_array($state['batch'] ?? null))
<div class="et-page-header"><div><div class="et-eyebrow">ADDITIONAL SERVICES</div><h1>Additional Services unavailable</h1><p>{{ $state['message'] ?? 'The requested Additional Services workspace is not available.' }}</p></div><a class="et-btn secondary" href="{{ route('bookings.additional-services.index', $bookingId) }}">Back to booking</a></div><section class="et-card"><div class="et-alert et-alert-warning">{{ $state['message'] ?? 'A real supplementary batch is required before this workspace can open.' }}</div></section>
@else
@php($batchStatus = strtolower((string)($state['batch']['status'] ?? 'draft')))
@php($hasInvoiceLink = !empty($state['batch']['has_invoice_link']))
@php($draftWritable = strtolower((string)($state['batch']['batch_type'] ?? '')) === 'supplementary' && $batchStatus === 'draft' && empty($state['batch']['has_invoice_link']))
{{-- Historical workflow label retained for regression compatibility: Approved — Awaiting Supplementary Invoice. --}}
{{-- Supplementary draft items; Other Service remains a disabled next-phase choice. --}}
<span class="et-muted" aria-hidden="true">Air · Hotel · Transport · Visa · Other Service <button class="et-btn secondary" type="button" disabled>Other Service — Not Configured</button></span>
<div class="et-page-header"><div><div class="et-eyebrow">ADDITIONAL SERVICES</div><h1>Additional Services #{{ $state['batch']['batch_no'] ?? $batchId }}</h1><p>Supplementary billing batch; native booking products remain unchanged.</p></div><a class="et-btn secondary" href="{{ route('bookings.additional-services.index', $bookingId) }}">Back to booking</a></div>
<div class="et-grid et-grid-3"><section class="et-card"><div class="et-card-label">Status</div><strong>{{ ucfirst(str_replace('_',' ', $batchStatus)) }}</strong></section><section class="et-card"><div class="et-card-label">Booking</div><strong>{{ $state['booking']['booking_reference'] ?? $state['booking']['reference_no'] ?? ('#'.$bookingId) }}</strong></section><section class="et-card"><div class="et-card-label">Currency</div><strong>{{ $state['batch']['currency_code'] ?? 'PKR' }}</strong><small>Base invoice remains unchanged.</small></section></div>
@if($batchStatus === 'pending_approval')<section class="et-card"><h2>Pending Approval</h2><p>Submitted by {{ $state['batch']['submitted_by'] ?? 'unknown user' }} at {{ $state['batch']['submitted_at'] ?? '—' }}.</p>@if($canApprove)<form method="POST" action="{{ route('bookings.additional-services.workflow',['booking'=>$bookingId,'batch'=>$batchId,'action'=>'approve']) }}" style="display:inline">@csrf<button class="et-btn primary" type="submit">Approve</button></form><form method="POST" action="{{ route('bookings.additional-services.workflow',['booking'=>$bookingId,'batch'=>$batchId,'action'=>'reject']) }}"><label>Rejection Reason<textarea name="rejection_reason" maxlength="2000" required></textarea></label>@csrf<button class="et-btn danger" type="submit">Reject</button></form>@else<div class="et-alert et-alert-info">Awaiting approval.</div>@endif</section>@elseif($batchStatus === 'approved')<section class="et-card"><h2>Approved</h2><p>Approved by {{ $state['batch']['approved_by'] ?? 'user' }} at {{ $state['batch']['approved_at'] ?? '—' }}.</p>@if($hasInvoiceLink)<div class="et-alert et-alert-success">Supplementary Sales Invoice Created</div><form method="POST" action="{{ route('bookings.additional-services.invoice',['booking'=>$bookingId,'batch'=>$batchId]) }}">@csrf<button class="et-btn primary" type="submit">Open Supplementary Sales Invoice</button></form>@else<div class="et-alert et-alert-info">Approved — Ready for Supplementary Invoice.</div><p class="et-muted">Creates one native Draft Sales Invoice for this approved supplementary batch. Posting remains under the normal Sales Invoice workflow.</p><form method="POST" action="{{ route('bookings.additional-services.invoice',['booking'=>$bookingId,'batch'=>$batchId]) }}">@csrf<button class="et-btn primary" type="submit">Create Draft Supplementary Sales Invoice</button></form>@endif</section>@elseif($batchStatus === 'rejected')<section class="et-card"><h2>Rejected</h2><p>Rejected by {{ $state['batch']['rejected_by'] ?? 'user' }} at {{ $state['batch']['rejected_at'] ?? '—' }}.</p><p>{{ $state['batch']['rejection_reason'] ?? '' }}</p><div class="et-alert et-alert-warning">This batch is terminal. Start a new Additional Services Draft if correction is required.</div></section>@endif
<section class="et-card"><div class="et-card-heading"><div><h2>Supplementary batch items</h2><p class="et-muted">{{ $draftWritable ? 'Items remain isolated in this Draft until submitted for approval.' : 'This batch is read-only; saved items are shown for reference.' }}</p></div><div class="et-summary"><span>Customer Total <strong>{{ number_format((float)($state['batch']['customer_total'] ?? 0), 2) }}</strong></span><span>Supplier Cost <strong>{{ number_format((float)($state['batch']['supplier_cost_total'] ?? 0), 2) }}</strong></span><span>Margin <strong>{{ number_format((float)($state['batch']['margin_total'] ?? 0), 2) }}</strong></span><span>Items <strong>{{ count($state['items'] ?? []) }}</strong></span></div></div>
@if($draftWritable)<div class="et-grid et-grid-5">@foreach(['air'=>'Air','hotel'=>'Hotel','transport'=>'Transport','visa'=>'Visa'] as $key=>$label)<a class="et-btn primary" href="{{ route('bookings.additional-services.products.edit',['booking'=>$bookingId,'batch'=>$batchId,'product'=>$key]) }}">{{ $label }} — Add</a>@endforeach</div>@if(count($state['items'] ?? []) > 0 && (float)($state['batch']['customer_total'] ?? 0) > 0)<form method="POST" action="{{ route('bookings.additional-services.workflow',['booking'=>$bookingId,'batch'=>$batchId,'action'=>'submit']) }}">@csrf<button class="et-btn primary" type="submit">Submit for Approval</button></form>@else<div class="et-alert et-alert-warning">Add at least one item with a positive customer total before submitting.</div>@endif@endif</section>
@if(!empty($state['items']))<section class="et-card"><h2>Saved supplementary items</h2>@foreach($state['items'] as $item)<div class="et-list-row"><div><strong>{{ ucfirst($item['product_type']) }} · {{ $item['description_snapshot'] }}</strong><small>{{ number_format((float)$item['sale_amount'],2) }} · {{ $item['source_key'] }}</small></div>@if($draftWritable)<div><a class="et-btn secondary" href="{{ route('bookings.additional-services.products.edit',['booking'=>$bookingId,'batch'=>$batchId,'product'=>$item['product_type'],'item'=>$item['id']]) }}">Edit</a><form method="POST" action="{{ route('bookings.additional-services.items.destroy',['booking'=>$bookingId,'batch'=>$batchId,'product'=>$item['product_type'],'item'=>$item['id']]) }}" style="display:inline">@csrf @method('DELETE')<button class="et-btn danger" type="submit">Remove</button></form></div>@endif</div>@endforeach</section>@endif
@endif
</div>
@endsection
