@extends($layoutMeta['layout'])

@section('content')
<div class="et-page et378-page">
    @if(!($state['schema_ready'] ?? false) || !is_array($state['batch'] ?? null))
        <div class="et-page-header"><div><div class="et-eyebrow">ADDITIONAL SERVICES</div><h1>Additional Services unavailable</h1><p>{{ $state['message'] ?? 'The requested Additional Services workspace is not available.' }}</p></div><a class="et-btn secondary" href="{{ route('bookings.additional-services.index', $bookingId) }}">Back to booking</a></div>
        <section class="et-card"><div class="et-alert et-alert-warning">{{ $state['message'] ?? 'A real supplementary batch is required before this workspace can open.' }}</div></section>
    @else
    <div class="et-page-header"><div><div class="et-eyebrow">ADDITIONAL SERVICES</div><h1>Additional Services #{{ $state['batch']['batch_no'] ?? $batchId }}</h1><p>Draft workspace for a supplementary billing batch.</p></div><a class="et-btn secondary" href="{{ route('bookings.additional-services.index', $bookingId) }}">Back to booking</a></div>
    <div class="et-grid et-grid-3"><section class="et-card"><div class="et-card-label">Status</div><strong>{{ ucfirst(str_replace('_',' ', $state['batch']['status'] ?? 'draft')) }}</strong></section><section class="et-card"><div class="et-card-label">Booking</div><strong>{{ $state['booking']['booking_reference'] ?? $state['booking']['reference_no'] ?? ('#'.$bookingId) }}</strong></section><section class="et-card"><div class="et-card-label">Currency</div><strong>{{ $state['batch']['currency_code'] ?? 'PKR' }}</strong><small>Base invoice remains unchanged.</small></section></div>
    @php($draftWritable = strtolower((string)($state['batch']['batch_type'] ?? '')) === 'supplementary' && strtolower((string)($state['batch']['status'] ?? '')) === 'draft' && empty($state['batch']['has_invoice_link']))
    <section class="et-card"><div class="et-card-heading"><div><h2>Supplementary draft items</h2><p class="et-muted">Items remain isolated in this Draft until a later approval/materialization phase.</p></div><div class="et-summary"><span>Customer Total <strong>{{ number_format((float)($state['batch']['customer_total'] ?? 0), 2) }}</strong></span><span>Supplier Cost <strong>{{ number_format((float)($state['batch']['supplier_cost_total'] ?? 0), 2) }}</strong></span><span>Margin <strong>{{ number_format((float)($state['batch']['margin_total'] ?? 0), 2) }}</strong></span><span>Items <strong>{{ count($state['items'] ?? []) }}</strong></span></div></div>@if($draftWritable)<div class="et-grid et-grid-5">@foreach(['air'=>'Air','hotel'=>'Hotel','transport'=>'Transport','visa'=>'Visa'] as $key=>$label)<a class="et-btn primary" href="{{ route('bookings.additional-services.products.edit',['booking'=>$bookingId,'batch'=>$batchId,'product'=>$key]) }}">{{ $label }} — Add</a>@endforeach<button class="et-btn secondary" type="button" disabled>Other Service — Not Configured</button></div>@else<div class="et-alert et-alert-info">This batch is read-only; saved items are shown for reference.</div>@endif</section>
    @if(!empty($state['items']))<section class="et-card"><h2>Saved draft items</h2>@foreach($state['items'] as $item)<div class="et-list-row"><div><strong>{{ ucfirst($item['product_type']) }} · {{ $item['description_snapshot'] }}</strong><small>{{ number_format((float)$item['sale_amount'],2) }} · {{ $item['source_key'] }}</small></div>@if($draftWritable)<div><a class="et-btn secondary" href="{{ route('bookings.additional-services.products.edit',['booking'=>$bookingId,'batch'=>$batchId,'product'=>$item['product_type'],'item'=>$item['id']]) }}">Edit</a><form method="POST" action="{{ route('bookings.additional-services.items.destroy',['booking'=>$bookingId,'batch'=>$batchId,'product'=>$item['product_type'],'item'=>$item['id']]) }}" style="display:inline">@csrf @method('DELETE')<button class="et-btn danger" type="submit">Remove</button></form></div>@endif</div>@endforeach</section>@endif
    @endif
</div>
@endsection
