@extends($layoutMeta['layout'])
@section($layoutMeta['title_section'] ?? 'title','Arrival Report')
@section($layoutMeta['content_section'] ?? 'content')
<style>
.et-arrival-report{width:100%;max-width:none;min-width:0;overflow-x:hidden;color:#17243a}.et-arrival-report *{box-sizing:border-box}.et-arrival-card{background:#fff;border:1px solid #dfe7f0;border-radius:8px;padding:14px;margin-bottom:12px}.et-arrival-title{font-size:20px;font-weight:800;margin:3px 0}.et-arrival-sub{font-size:11px;color:#718096}.et-arrival-tabs,.et-arrival-filters{display:flex;gap:7px;flex-wrap:wrap;align-items:center}.et-arrival-tabs{overflow-x:auto;flex-wrap:nowrap}.et-arrival-tabs a{white-space:nowrap;padding:7px 10px;border:1px solid #d7e1ec;border-radius:6px;color:#315273;text-decoration:none;font-size:10px;font-weight:700}.et-arrival-tabs a.active{background:#1769d2;border-color:#1769d2;color:#fff}.et-arrival-filters label{font-size:10px;font-weight:700;color:#52627a}.et-arrival-filters input{display:block;margin-top:3px;min-height:31px;border:1px solid #cdd8e5;border-radius:5px;padding:5px 7px}.et-arrival-btn{display:inline-block;padding:8px 11px;border-radius:5px;border:1px solid #1769d2;background:#1769d2;color:#fff;text-decoration:none;font-size:10px;font-weight:700}.et-arrival-btn.secondary{background:#fff;color:#315273;border-color:#cdd8e5}.et-arrival-scroll{width:100%;max-width:100%;overflow-x:auto;-webkit-overflow-scrolling:touch}.et-arrival-table{width:100%;min-width:1650px;border-collapse:collapse;font-size:10px}.et-arrival-table th,.et-arrival-table td{padding:7px 8px;border-bottom:1px solid #e8eef5;text-align:left;white-space:nowrap}.et-arrival-table th{background:#f4f7fb;font-size:9px}.et-arrival-badge{display:inline-block;padding:3px 7px;border-radius:999px;background:#eef5ff;color:#1769d2;font-weight:700}@media(max-width:760px){.et-arrival-filters label{flex:1 1 140px}.et-arrival-filters input{width:100%}}@media print{.sidebar,.navbar,.et-arrival-tabs,.et-arrival-filters,.et-arrival-print-hide{display:none!important}.et-arrival-report{overflow:visible}.et-arrival-scroll{overflow:visible}.et-arrival-table{min-width:0;font-size:9px}}
</style>
<div class="et-arrival-report" data-et-arrival-report="1">
 <div class="et-arrival-card"><div class="et-arrival-sub">Travel Reports / Movement Reports / Arrival</div><div class="et-arrival-title">Arrival Report</div><div class="et-arrival-sub">Operational inbound arrival movement reporting. No financial data.</div></div>
 <div class="et-arrival-card et-arrival-tabs" aria-label="Movement Reports">
  @foreach($movements as $movementKey=>$movementLabel)<a class="{{ $movementKey==='arrival'?'active':'' }}" href="{{ route('travel-reports.group-umrah.'.$movementKey) }}">{{ $movementKey==='arrival'?'Arrival':$movementLabel }}</a>@endforeach
 </div>
 <div class="et-arrival-card et-arrival-filters et-arrival-print-hide"><form class="et-arrival-filters" method="get"><label>From Date<input type="date" name="from" value="{{ request('from') }}"></label><label>To Date<input type="date" name="to" value="{{ request('to') }}"></label><label>Status<input type="text" name="status" value="{{ request('status') }}"></label><label>Branch ID<input inputmode="numeric" type="text" name="branch" value="{{ request('branch') }}"></label><label>Customer ID<input inputmode="numeric" type="text" name="customer" value="{{ request('customer') }}"></label><button class="et-arrival-btn" type="submit">Apply Filters</button><a class="et-arrival-btn secondary" href="{{ route('travel-reports.group-umrah.arrival') }}">Reset</a><a class="et-arrival-btn secondary" href="{{ route('travel-reports.group-umrah.arrival.export',request()->query()) }}">Export CSV</a><button class="et-arrival-btn secondary" type="button" onclick="window.print()">Print</button></form></div>
 <div class="et-arrival-card"><strong>Arrival Results</strong> <span class="et-arrival-sub">{{ method_exists($rows,'total')?$rows->total():0 }} records</span></div>
 <div class="et-arrival-card"><div class="et-arrival-scroll"><table class="et-arrival-table"><thead><tr><th>Arrival Date</th><th>Arrival Time</th><th>Booking No.</th><th>Customer / Group</th><th>Total Pax</th><th>Adult</th><th>Child</th><th>Infant</th><th>Flight</th><th>Sector</th><th>Makkah Hotel</th><th>Transport</th><th>Saudi Company</th><th>Pakistani IATA</th><th>Status</th><th>Branch</th><th>Agent / Salesperson</th><th>View</th></tr></thead><tbody>@forelse($rows as $row)<tr><td>{{ $row['arrival']??'—' }}</td><td>{{ $row['arrival_time']??'—' }}</td><td>{{ $row['booking_no']??'—' }}</td><td>{{ $row['customer']??'—' }}</td><td>{{ $row['total_pax']??'—' }}</td><td>{{ $row['adult']??'—' }}</td><td>{{ $row['child']??'—' }}</td><td>{{ $row['infant']??'—' }}</td><td>{{ $row['flight']??'—' }}</td><td>{{ $row['sector']??'—' }}</td><td>{{ $row['makkah_hotel']??'—' }}</td><td>{{ $row['transport']??'—' }}</td><td>{{ $row['saudi_company']??'—' }}</td><td>{{ $row['pakistani_iata']??'—' }}</td><td><span class="et-arrival-badge">{{ $row['status']??'—' }}</span></td><td>{{ $row['branch']??'—' }}</td><td>{{ $row['agent_salesperson']??'—' }}</td><td>@if(($row['action']??'—')!=='—')<a href="{{ $row['action'] }}">View</a>@else—@endif</td></tr>@empty<tr><td colspan="18">No arrival records match the selected filters.</td></tr>@endforelse</tbody></table></div>@if(is_object($rows) && method_exists($rows,'links')){{ $rows->links() }}@endif</div>
</div>
@endsection
